// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_latency_ap_fixed_ap_fixed_config11_0_0_0_HH_
#define _dense_latency_ap_fixed_ap_fixed_config11_0_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dense_latency_ap_fixed_ap_fixed_config11_0_0_0 : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<24> > data_0_V_read;
    sc_in< sc_lv<24> > data_1_V_read;
    sc_in< sc_lv<24> > data_2_V_read;
    sc_in< sc_lv<24> > data_3_V_read;
    sc_in< sc_lv<24> > data_4_V_read;
    sc_in< sc_lv<24> > data_5_V_read;
    sc_in< sc_lv<24> > data_6_V_read;
    sc_in< sc_lv<24> > data_7_V_read;
    sc_in< sc_lv<24> > data_8_V_read;
    sc_in< sc_lv<24> > data_9_V_read;
    sc_in< sc_lv<24> > data_10_V_read;
    sc_in< sc_lv<24> > data_11_V_read;
    sc_in< sc_lv<24> > data_12_V_read;
    sc_in< sc_lv<24> > data_13_V_read;
    sc_in< sc_lv<24> > data_14_V_read;
    sc_in< sc_lv<24> > data_15_V_read;
    sc_out< sc_lv<24> > ap_return_0;
    sc_out< sc_lv<24> > ap_return_1;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    dense_latency_ap_fixed_ap_fixed_config11_0_0_0(sc_module_name name);
    SC_HAS_PROCESS(dense_latency_ap_fixed_ap_fixed_config11_0_0_0);

    ~dense_latency_ap_fixed_ap_fixed_config11_0_0_0();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<18> > trunc_ln703_1_reg_1705;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<18> > trunc_ln703_2_reg_1710;
    sc_signal< sc_lv<18> > trunc_ln703_9_reg_1715;
    sc_signal< sc_lv<18> > trunc_ln703_10_reg_1720;
    sc_signal< sc_lv<18> > add_ln731_1_fu_1591_p2;
    sc_signal< sc_lv<18> > add_ln731_1_reg_1725;
    sc_signal< sc_lv<18> > add_ln731_4_fu_1597_p2;
    sc_signal< sc_lv<18> > add_ln731_4_reg_1730;
    sc_signal< sc_lv<18> > add_ln731_6_fu_1609_p2;
    sc_signal< sc_lv<18> > add_ln731_6_reg_1735;
    sc_signal< sc_lv<18> > add_ln731_8_fu_1615_p2;
    sc_signal< sc_lv<18> > add_ln731_8_reg_1740;
    sc_signal< sc_lv<18> > add_ln731_11_fu_1621_p2;
    sc_signal< sc_lv<18> > add_ln731_11_reg_1745;
    sc_signal< sc_lv<18> > add_ln731_13_fu_1633_p2;
    sc_signal< sc_lv<18> > add_ln731_13_reg_1750;
    sc_signal< sc_lv<24> > mul_ln1118_15_fu_198_p0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<24> > mul_ln1118_fu_199_p0;
    sc_signal< sc_lv<24> > mul_ln1118_9_fu_200_p0;
    sc_signal< sc_lv<24> > mul_ln1118_4_fu_201_p0;
    sc_signal< sc_lv<24> > mul_ln1118_5_fu_202_p0;
    sc_signal< sc_lv<24> > mul_ln1118_1_fu_203_p0;
    sc_signal< sc_lv<24> > mul_ln1118_6_fu_204_p0;
    sc_signal< sc_lv<24> > mul_ln1118_11_fu_205_p0;
    sc_signal< sc_lv<24> > mul_ln1118_3_fu_206_p0;
    sc_signal< sc_lv<24> > mul_ln1118_8_fu_207_p0;
    sc_signal< sc_lv<24> > mul_ln1118_10_fu_208_p0;
    sc_signal< sc_lv<24> > mul_ln1118_12_fu_209_p0;
    sc_signal< sc_lv<24> > mul_ln1118_7_fu_210_p0;
    sc_signal< sc_lv<24> > mul_ln1118_13_fu_211_p0;
    sc_signal< sc_lv<24> > mul_ln1118_14_fu_212_p0;
    sc_signal< sc_lv<24> > mul_ln1118_2_fu_213_p0;
    sc_signal< sc_lv<40> > mul_ln1118_fu_199_p2;
    sc_signal< sc_lv<40> > mul_ln1118_1_fu_203_p2;
    sc_signal< sc_lv<40> > mul_ln1118_2_fu_213_p2;
    sc_signal< sc_lv<40> > mul_ln1118_3_fu_206_p2;
    sc_signal< sc_lv<40> > mul_ln1118_4_fu_201_p2;
    sc_signal< sc_lv<40> > mul_ln1118_5_fu_202_p2;
    sc_signal< sc_lv<40> > mul_ln1118_6_fu_204_p2;
    sc_signal< sc_lv<40> > mul_ln1118_7_fu_210_p2;
    sc_signal< sc_lv<40> > mul_ln1118_8_fu_207_p2;
    sc_signal< sc_lv<40> > mul_ln1118_9_fu_200_p2;
    sc_signal< sc_lv<40> > mul_ln1118_10_fu_208_p2;
    sc_signal< sc_lv<40> > mul_ln1118_11_fu_205_p2;
    sc_signal< sc_lv<40> > mul_ln1118_12_fu_209_p2;
    sc_signal< sc_lv<40> > mul_ln1118_13_fu_211_p2;
    sc_signal< sc_lv<40> > mul_ln1118_14_fu_212_p2;
    sc_signal< sc_lv<40> > mul_ln1118_15_fu_198_p2;
    sc_signal< sc_lv<18> > trunc_ln703_s_fu_1441_p4;
    sc_signal< sc_lv<18> > trunc_ln_fu_1431_p4;
    sc_signal< sc_lv<18> > trunc_ln703_4_fu_1481_p4;
    sc_signal< sc_lv<18> > trunc_ln703_3_fu_1471_p4;
    sc_signal< sc_lv<18> > trunc_ln703_6_fu_1501_p4;
    sc_signal< sc_lv<18> > trunc_ln703_5_fu_1491_p4;
    sc_signal< sc_lv<18> > add_ln731_5_fu_1603_p2;
    sc_signal< sc_lv<18> > trunc_ln703_8_fu_1521_p4;
    sc_signal< sc_lv<18> > trunc_ln703_7_fu_1511_p4;
    sc_signal< sc_lv<18> > trunc_ln703_12_fu_1561_p4;
    sc_signal< sc_lv<18> > trunc_ln703_11_fu_1551_p4;
    sc_signal< sc_lv<18> > trunc_ln703_14_fu_1581_p4;
    sc_signal< sc_lv<18> > trunc_ln703_13_fu_1571_p4;
    sc_signal< sc_lv<18> > add_ln731_12_fu_1627_p2;
    sc_signal< sc_lv<18> > add_ln731_2_fu_1639_p2;
    sc_signal< sc_lv<18> > add_ln731_3_fu_1643_p2;
    sc_signal< sc_lv<18> > add_ln731_7_fu_1648_p2;
    sc_signal< sc_lv<18> > add_ln731_fu_1652_p2;
    sc_signal< sc_lv<18> > add_ln731_9_fu_1666_p2;
    sc_signal< sc_lv<18> > add_ln731_10_fu_1670_p2;
    sc_signal< sc_lv<18> > add_ln731_14_fu_1675_p2;
    sc_signal< sc_lv<18> > add_ln731_15_fu_1679_p2;
    sc_signal< sc_lv<24> > res_0_V_write_assign_fu_1658_p3;
    sc_signal< sc_lv<24> > res_1_V_write_assign_fu_1685_p3;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<24> > ap_return_0_int_reg;
    sc_signal< sc_lv<24> > ap_return_1_int_reg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<40> ap_const_lv40_24F4A3;
    static const sc_lv<40> ap_const_lv40_140B0;
    static const sc_lv<40> ap_const_lv40_D1D4C;
    static const sc_lv<40> ap_const_lv40_FFFFF7D459;
    static const sc_lv<40> ap_const_lv40_FFFFFF5EC8;
    static const sc_lv<40> ap_const_lv40_21C23;
    static const sc_lv<40> ap_const_lv40_36CD2;
    static const sc_lv<40> ap_const_lv40_FFFFEAB402;
    static const sc_lv<40> ap_const_lv40_FFFFFBE035;
    static const sc_lv<40> ap_const_lv40_249452;
    static const sc_lv<40> ap_const_lv40_DB36F;
    static const sc_lv<40> ap_const_lv40_FFFFF9AAD0;
    static const sc_lv<40> ap_const_lv40_5A124;
    static const sc_lv<40> ap_const_lv40_FFFFE9EAD7;
    static const sc_lv<40> ap_const_lv40_960A1;
    static const sc_lv<40> ap_const_lv40_8B842;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<18> ap_const_lv18_12B1;
    static const sc_lv<18> ap_const_lv18_1523;
    static const sc_lv<6> ap_const_lv6_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln731_10_fu_1670_p2();
    void thread_add_ln731_11_fu_1621_p2();
    void thread_add_ln731_12_fu_1627_p2();
    void thread_add_ln731_13_fu_1633_p2();
    void thread_add_ln731_14_fu_1675_p2();
    void thread_add_ln731_15_fu_1679_p2();
    void thread_add_ln731_1_fu_1591_p2();
    void thread_add_ln731_2_fu_1639_p2();
    void thread_add_ln731_3_fu_1643_p2();
    void thread_add_ln731_4_fu_1597_p2();
    void thread_add_ln731_5_fu_1603_p2();
    void thread_add_ln731_6_fu_1609_p2();
    void thread_add_ln731_7_fu_1648_p2();
    void thread_add_ln731_8_fu_1615_p2();
    void thread_add_ln731_9_fu_1666_p2();
    void thread_add_ln731_fu_1652_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_mul_ln1118_10_fu_208_p0();
    void thread_mul_ln1118_10_fu_208_p2();
    void thread_mul_ln1118_11_fu_205_p0();
    void thread_mul_ln1118_11_fu_205_p2();
    void thread_mul_ln1118_12_fu_209_p0();
    void thread_mul_ln1118_12_fu_209_p2();
    void thread_mul_ln1118_13_fu_211_p0();
    void thread_mul_ln1118_13_fu_211_p2();
    void thread_mul_ln1118_14_fu_212_p0();
    void thread_mul_ln1118_14_fu_212_p2();
    void thread_mul_ln1118_15_fu_198_p0();
    void thread_mul_ln1118_15_fu_198_p2();
    void thread_mul_ln1118_1_fu_203_p0();
    void thread_mul_ln1118_1_fu_203_p2();
    void thread_mul_ln1118_2_fu_213_p0();
    void thread_mul_ln1118_2_fu_213_p2();
    void thread_mul_ln1118_3_fu_206_p0();
    void thread_mul_ln1118_3_fu_206_p2();
    void thread_mul_ln1118_4_fu_201_p0();
    void thread_mul_ln1118_4_fu_201_p2();
    void thread_mul_ln1118_5_fu_202_p0();
    void thread_mul_ln1118_5_fu_202_p2();
    void thread_mul_ln1118_6_fu_204_p0();
    void thread_mul_ln1118_6_fu_204_p2();
    void thread_mul_ln1118_7_fu_210_p0();
    void thread_mul_ln1118_7_fu_210_p2();
    void thread_mul_ln1118_8_fu_207_p0();
    void thread_mul_ln1118_8_fu_207_p2();
    void thread_mul_ln1118_9_fu_200_p0();
    void thread_mul_ln1118_9_fu_200_p2();
    void thread_mul_ln1118_fu_199_p0();
    void thread_mul_ln1118_fu_199_p2();
    void thread_res_0_V_write_assign_fu_1658_p3();
    void thread_res_1_V_write_assign_fu_1685_p3();
    void thread_trunc_ln703_11_fu_1551_p4();
    void thread_trunc_ln703_12_fu_1561_p4();
    void thread_trunc_ln703_13_fu_1571_p4();
    void thread_trunc_ln703_14_fu_1581_p4();
    void thread_trunc_ln703_3_fu_1471_p4();
    void thread_trunc_ln703_4_fu_1481_p4();
    void thread_trunc_ln703_5_fu_1491_p4();
    void thread_trunc_ln703_6_fu_1501_p4();
    void thread_trunc_ln703_7_fu_1511_p4();
    void thread_trunc_ln703_8_fu_1521_p4();
    void thread_trunc_ln703_s_fu_1441_p4();
    void thread_trunc_ln_fu_1431_p4();
};

}

using namespace ap_rtl;

#endif
