// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_ap_fixed_config11_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_boolean_1 = true;
const bool dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_boolean_0 = false;
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_24F4A3 = "1001001111010010100011";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_140B0 = "10100000010110000";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_D1D4C = "11010001110101001100";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_FFFFF7D459 = "1111111111111111111101111101010001011001";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_FFFFFF5EC8 = "1111111111111111111111110101111011001000";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_21C23 = "100001110000100011";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_36CD2 = "110110110011010010";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_FFFFEAB402 = "1111111111111111111010101011010000000010";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_FFFFFBE035 = "1111111111111111111110111110000000110101";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_249452 = "1001001001010001010010";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_DB36F = "11011011001101101111";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_FFFFF9AAD0 = "1111111111111111111110011010101011010000";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_5A124 = "1011010000100100100";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_FFFFE9EAD7 = "1111111111111111111010011110101011010111";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_960A1 = "10010110000010100001";
const sc_lv<40> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv40_8B842 = "10001011100001000010";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv32_16 = "10110";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv32_27 = "100111";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv18_12B1 = "1001010110001";
const sc_lv<18> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv18_1523 = "1010100100011";
const sc_lv<6> dense_latency_ap_fixed_ap_fixed_config11_0_0_0::ap_const_lv6_0 = "000000";

dense_latency_ap_fixed_ap_fixed_config11_0_0_0::dense_latency_ap_fixed_ap_fixed_config11_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln731_10_fu_1670_p2);
    sensitive << ( add_ln731_8_reg_1740 );
    sensitive << ( add_ln731_9_fu_1666_p2 );

    SC_METHOD(thread_add_ln731_11_fu_1621_p2);
    sensitive << ( trunc_ln703_12_fu_1561_p4 );
    sensitive << ( trunc_ln703_11_fu_1551_p4 );

    SC_METHOD(thread_add_ln731_12_fu_1627_p2);
    sensitive << ( trunc_ln703_14_fu_1581_p4 );

    SC_METHOD(thread_add_ln731_13_fu_1633_p2);
    sensitive << ( trunc_ln703_13_fu_1571_p4 );
    sensitive << ( add_ln731_12_fu_1627_p2 );

    SC_METHOD(thread_add_ln731_14_fu_1675_p2);
    sensitive << ( add_ln731_11_reg_1745 );
    sensitive << ( add_ln731_13_reg_1750 );

    SC_METHOD(thread_add_ln731_15_fu_1679_p2);
    sensitive << ( add_ln731_10_fu_1670_p2 );
    sensitive << ( add_ln731_14_fu_1675_p2 );

    SC_METHOD(thread_add_ln731_1_fu_1591_p2);
    sensitive << ( trunc_ln703_s_fu_1441_p4 );
    sensitive << ( trunc_ln_fu_1431_p4 );

    SC_METHOD(thread_add_ln731_2_fu_1639_p2);
    sensitive << ( trunc_ln703_1_reg_1705 );
    sensitive << ( trunc_ln703_2_reg_1710 );

    SC_METHOD(thread_add_ln731_3_fu_1643_p2);
    sensitive << ( add_ln731_1_reg_1725 );
    sensitive << ( add_ln731_2_fu_1639_p2 );

    SC_METHOD(thread_add_ln731_4_fu_1597_p2);
    sensitive << ( trunc_ln703_4_fu_1481_p4 );
    sensitive << ( trunc_ln703_3_fu_1471_p4 );

    SC_METHOD(thread_add_ln731_5_fu_1603_p2);
    sensitive << ( trunc_ln703_6_fu_1501_p4 );

    SC_METHOD(thread_add_ln731_6_fu_1609_p2);
    sensitive << ( trunc_ln703_5_fu_1491_p4 );
    sensitive << ( add_ln731_5_fu_1603_p2 );

    SC_METHOD(thread_add_ln731_7_fu_1648_p2);
    sensitive << ( add_ln731_4_reg_1730 );
    sensitive << ( add_ln731_6_reg_1735 );

    SC_METHOD(thread_add_ln731_8_fu_1615_p2);
    sensitive << ( trunc_ln703_8_fu_1521_p4 );
    sensitive << ( trunc_ln703_7_fu_1511_p4 );

    SC_METHOD(thread_add_ln731_9_fu_1666_p2);
    sensitive << ( trunc_ln703_9_reg_1715 );
    sensitive << ( trunc_ln703_10_reg_1720 );

    SC_METHOD(thread_add_ln731_fu_1652_p2);
    sensitive << ( add_ln731_3_fu_1643_p2 );
    sensitive << ( add_ln731_7_fu_1648_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( res_0_V_write_assign_fu_1658_p3 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( res_1_V_write_assign_fu_1685_p3 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_mul_ln1118_10_fu_208_p0);
    sensitive << ( data_10_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_10_fu_208_p2);
    sensitive << ( mul_ln1118_10_fu_208_p0 );

    SC_METHOD(thread_mul_ln1118_11_fu_205_p0);
    sensitive << ( data_11_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_11_fu_205_p2);
    sensitive << ( mul_ln1118_11_fu_205_p0 );

    SC_METHOD(thread_mul_ln1118_12_fu_209_p0);
    sensitive << ( data_12_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_12_fu_209_p2);
    sensitive << ( mul_ln1118_12_fu_209_p0 );

    SC_METHOD(thread_mul_ln1118_13_fu_211_p0);
    sensitive << ( data_13_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_13_fu_211_p2);
    sensitive << ( mul_ln1118_13_fu_211_p0 );

    SC_METHOD(thread_mul_ln1118_14_fu_212_p0);
    sensitive << ( data_14_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_14_fu_212_p2);
    sensitive << ( mul_ln1118_14_fu_212_p0 );

    SC_METHOD(thread_mul_ln1118_15_fu_198_p0);
    sensitive << ( data_15_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_15_fu_198_p2);
    sensitive << ( mul_ln1118_15_fu_198_p0 );

    SC_METHOD(thread_mul_ln1118_1_fu_203_p0);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_1_fu_203_p2);
    sensitive << ( mul_ln1118_1_fu_203_p0 );

    SC_METHOD(thread_mul_ln1118_2_fu_213_p0);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_2_fu_213_p2);
    sensitive << ( mul_ln1118_2_fu_213_p0 );

    SC_METHOD(thread_mul_ln1118_3_fu_206_p0);
    sensitive << ( data_3_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_3_fu_206_p2);
    sensitive << ( mul_ln1118_3_fu_206_p0 );

    SC_METHOD(thread_mul_ln1118_4_fu_201_p0);
    sensitive << ( data_4_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_4_fu_201_p2);
    sensitive << ( mul_ln1118_4_fu_201_p0 );

    SC_METHOD(thread_mul_ln1118_5_fu_202_p0);
    sensitive << ( data_5_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_5_fu_202_p2);
    sensitive << ( mul_ln1118_5_fu_202_p0 );

    SC_METHOD(thread_mul_ln1118_6_fu_204_p0);
    sensitive << ( data_6_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_6_fu_204_p2);
    sensitive << ( mul_ln1118_6_fu_204_p0 );

    SC_METHOD(thread_mul_ln1118_7_fu_210_p0);
    sensitive << ( data_7_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_7_fu_210_p2);
    sensitive << ( mul_ln1118_7_fu_210_p0 );

    SC_METHOD(thread_mul_ln1118_8_fu_207_p0);
    sensitive << ( data_8_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_8_fu_207_p2);
    sensitive << ( mul_ln1118_8_fu_207_p0 );

    SC_METHOD(thread_mul_ln1118_9_fu_200_p0);
    sensitive << ( data_9_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_9_fu_200_p2);
    sensitive << ( mul_ln1118_9_fu_200_p0 );

    SC_METHOD(thread_mul_ln1118_fu_199_p0);
    sensitive << ( data_0_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_fu_199_p2);
    sensitive << ( mul_ln1118_fu_199_p0 );

    SC_METHOD(thread_res_0_V_write_assign_fu_1658_p3);
    sensitive << ( add_ln731_fu_1652_p2 );

    SC_METHOD(thread_res_1_V_write_assign_fu_1685_p3);
    sensitive << ( add_ln731_15_fu_1679_p2 );

    SC_METHOD(thread_trunc_ln703_11_fu_1551_p4);
    sensitive << ( mul_ln1118_12_fu_209_p2 );

    SC_METHOD(thread_trunc_ln703_12_fu_1561_p4);
    sensitive << ( mul_ln1118_13_fu_211_p2 );

    SC_METHOD(thread_trunc_ln703_13_fu_1571_p4);
    sensitive << ( mul_ln1118_14_fu_212_p2 );

    SC_METHOD(thread_trunc_ln703_14_fu_1581_p4);
    sensitive << ( mul_ln1118_15_fu_198_p2 );

    SC_METHOD(thread_trunc_ln703_3_fu_1471_p4);
    sensitive << ( mul_ln1118_4_fu_201_p2 );

    SC_METHOD(thread_trunc_ln703_4_fu_1481_p4);
    sensitive << ( mul_ln1118_5_fu_202_p2 );

    SC_METHOD(thread_trunc_ln703_5_fu_1491_p4);
    sensitive << ( mul_ln1118_6_fu_204_p2 );

    SC_METHOD(thread_trunc_ln703_6_fu_1501_p4);
    sensitive << ( mul_ln1118_7_fu_210_p2 );

    SC_METHOD(thread_trunc_ln703_7_fu_1511_p4);
    sensitive << ( mul_ln1118_8_fu_207_p2 );

    SC_METHOD(thread_trunc_ln703_8_fu_1521_p4);
    sensitive << ( mul_ln1118_9_fu_200_p2 );

    SC_METHOD(thread_trunc_ln703_s_fu_1441_p4);
    sensitive << ( mul_ln1118_1_fu_203_p2 );

    SC_METHOD(thread_trunc_ln_fu_1431_p4);
    sensitive << ( mul_ln1118_fu_199_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_ap_fixed_config11_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, trunc_ln703_1_reg_1705, "trunc_ln703_1_reg_1705");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, trunc_ln703_2_reg_1710, "trunc_ln703_2_reg_1710");
    sc_trace(mVcdFile, trunc_ln703_9_reg_1715, "trunc_ln703_9_reg_1715");
    sc_trace(mVcdFile, trunc_ln703_10_reg_1720, "trunc_ln703_10_reg_1720");
    sc_trace(mVcdFile, add_ln731_1_fu_1591_p2, "add_ln731_1_fu_1591_p2");
    sc_trace(mVcdFile, add_ln731_1_reg_1725, "add_ln731_1_reg_1725");
    sc_trace(mVcdFile, add_ln731_4_fu_1597_p2, "add_ln731_4_fu_1597_p2");
    sc_trace(mVcdFile, add_ln731_4_reg_1730, "add_ln731_4_reg_1730");
    sc_trace(mVcdFile, add_ln731_6_fu_1609_p2, "add_ln731_6_fu_1609_p2");
    sc_trace(mVcdFile, add_ln731_6_reg_1735, "add_ln731_6_reg_1735");
    sc_trace(mVcdFile, add_ln731_8_fu_1615_p2, "add_ln731_8_fu_1615_p2");
    sc_trace(mVcdFile, add_ln731_8_reg_1740, "add_ln731_8_reg_1740");
    sc_trace(mVcdFile, add_ln731_11_fu_1621_p2, "add_ln731_11_fu_1621_p2");
    sc_trace(mVcdFile, add_ln731_11_reg_1745, "add_ln731_11_reg_1745");
    sc_trace(mVcdFile, add_ln731_13_fu_1633_p2, "add_ln731_13_fu_1633_p2");
    sc_trace(mVcdFile, add_ln731_13_reg_1750, "add_ln731_13_reg_1750");
    sc_trace(mVcdFile, mul_ln1118_15_fu_198_p0, "mul_ln1118_15_fu_198_p0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln1118_fu_199_p0, "mul_ln1118_fu_199_p0");
    sc_trace(mVcdFile, mul_ln1118_9_fu_200_p0, "mul_ln1118_9_fu_200_p0");
    sc_trace(mVcdFile, mul_ln1118_4_fu_201_p0, "mul_ln1118_4_fu_201_p0");
    sc_trace(mVcdFile, mul_ln1118_5_fu_202_p0, "mul_ln1118_5_fu_202_p0");
    sc_trace(mVcdFile, mul_ln1118_1_fu_203_p0, "mul_ln1118_1_fu_203_p0");
    sc_trace(mVcdFile, mul_ln1118_6_fu_204_p0, "mul_ln1118_6_fu_204_p0");
    sc_trace(mVcdFile, mul_ln1118_11_fu_205_p0, "mul_ln1118_11_fu_205_p0");
    sc_trace(mVcdFile, mul_ln1118_3_fu_206_p0, "mul_ln1118_3_fu_206_p0");
    sc_trace(mVcdFile, mul_ln1118_8_fu_207_p0, "mul_ln1118_8_fu_207_p0");
    sc_trace(mVcdFile, mul_ln1118_10_fu_208_p0, "mul_ln1118_10_fu_208_p0");
    sc_trace(mVcdFile, mul_ln1118_12_fu_209_p0, "mul_ln1118_12_fu_209_p0");
    sc_trace(mVcdFile, mul_ln1118_7_fu_210_p0, "mul_ln1118_7_fu_210_p0");
    sc_trace(mVcdFile, mul_ln1118_13_fu_211_p0, "mul_ln1118_13_fu_211_p0");
    sc_trace(mVcdFile, mul_ln1118_14_fu_212_p0, "mul_ln1118_14_fu_212_p0");
    sc_trace(mVcdFile, mul_ln1118_2_fu_213_p0, "mul_ln1118_2_fu_213_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_199_p2, "mul_ln1118_fu_199_p2");
    sc_trace(mVcdFile, mul_ln1118_1_fu_203_p2, "mul_ln1118_1_fu_203_p2");
    sc_trace(mVcdFile, mul_ln1118_2_fu_213_p2, "mul_ln1118_2_fu_213_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_206_p2, "mul_ln1118_3_fu_206_p2");
    sc_trace(mVcdFile, mul_ln1118_4_fu_201_p2, "mul_ln1118_4_fu_201_p2");
    sc_trace(mVcdFile, mul_ln1118_5_fu_202_p2, "mul_ln1118_5_fu_202_p2");
    sc_trace(mVcdFile, mul_ln1118_6_fu_204_p2, "mul_ln1118_6_fu_204_p2");
    sc_trace(mVcdFile, mul_ln1118_7_fu_210_p2, "mul_ln1118_7_fu_210_p2");
    sc_trace(mVcdFile, mul_ln1118_8_fu_207_p2, "mul_ln1118_8_fu_207_p2");
    sc_trace(mVcdFile, mul_ln1118_9_fu_200_p2, "mul_ln1118_9_fu_200_p2");
    sc_trace(mVcdFile, mul_ln1118_10_fu_208_p2, "mul_ln1118_10_fu_208_p2");
    sc_trace(mVcdFile, mul_ln1118_11_fu_205_p2, "mul_ln1118_11_fu_205_p2");
    sc_trace(mVcdFile, mul_ln1118_12_fu_209_p2, "mul_ln1118_12_fu_209_p2");
    sc_trace(mVcdFile, mul_ln1118_13_fu_211_p2, "mul_ln1118_13_fu_211_p2");
    sc_trace(mVcdFile, mul_ln1118_14_fu_212_p2, "mul_ln1118_14_fu_212_p2");
    sc_trace(mVcdFile, mul_ln1118_15_fu_198_p2, "mul_ln1118_15_fu_198_p2");
    sc_trace(mVcdFile, trunc_ln703_s_fu_1441_p4, "trunc_ln703_s_fu_1441_p4");
    sc_trace(mVcdFile, trunc_ln_fu_1431_p4, "trunc_ln_fu_1431_p4");
    sc_trace(mVcdFile, trunc_ln703_4_fu_1481_p4, "trunc_ln703_4_fu_1481_p4");
    sc_trace(mVcdFile, trunc_ln703_3_fu_1471_p4, "trunc_ln703_3_fu_1471_p4");
    sc_trace(mVcdFile, trunc_ln703_6_fu_1501_p4, "trunc_ln703_6_fu_1501_p4");
    sc_trace(mVcdFile, trunc_ln703_5_fu_1491_p4, "trunc_ln703_5_fu_1491_p4");
    sc_trace(mVcdFile, add_ln731_5_fu_1603_p2, "add_ln731_5_fu_1603_p2");
    sc_trace(mVcdFile, trunc_ln703_8_fu_1521_p4, "trunc_ln703_8_fu_1521_p4");
    sc_trace(mVcdFile, trunc_ln703_7_fu_1511_p4, "trunc_ln703_7_fu_1511_p4");
    sc_trace(mVcdFile, trunc_ln703_12_fu_1561_p4, "trunc_ln703_12_fu_1561_p4");
    sc_trace(mVcdFile, trunc_ln703_11_fu_1551_p4, "trunc_ln703_11_fu_1551_p4");
    sc_trace(mVcdFile, trunc_ln703_14_fu_1581_p4, "trunc_ln703_14_fu_1581_p4");
    sc_trace(mVcdFile, trunc_ln703_13_fu_1571_p4, "trunc_ln703_13_fu_1571_p4");
    sc_trace(mVcdFile, add_ln731_12_fu_1627_p2, "add_ln731_12_fu_1627_p2");
    sc_trace(mVcdFile, add_ln731_2_fu_1639_p2, "add_ln731_2_fu_1639_p2");
    sc_trace(mVcdFile, add_ln731_3_fu_1643_p2, "add_ln731_3_fu_1643_p2");
    sc_trace(mVcdFile, add_ln731_7_fu_1648_p2, "add_ln731_7_fu_1648_p2");
    sc_trace(mVcdFile, add_ln731_fu_1652_p2, "add_ln731_fu_1652_p2");
    sc_trace(mVcdFile, add_ln731_9_fu_1666_p2, "add_ln731_9_fu_1666_p2");
    sc_trace(mVcdFile, add_ln731_10_fu_1670_p2, "add_ln731_10_fu_1670_p2");
    sc_trace(mVcdFile, add_ln731_14_fu_1675_p2, "add_ln731_14_fu_1675_p2");
    sc_trace(mVcdFile, add_ln731_15_fu_1679_p2, "add_ln731_15_fu_1679_p2");
    sc_trace(mVcdFile, res_0_V_write_assign_fu_1658_p3, "res_0_V_write_assign_fu_1658_p3");
    sc_trace(mVcdFile, res_1_V_write_assign_fu_1685_p3, "res_1_V_write_assign_fu_1685_p3");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
#endif

    }
}

dense_latency_ap_fixed_ap_fixed_config11_0_0_0::~dense_latency_ap_fixed_ap_fixed_config11_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        add_ln731_11_reg_1745 = add_ln731_11_fu_1621_p2.read();
        add_ln731_13_reg_1750 = add_ln731_13_fu_1633_p2.read();
        add_ln731_1_reg_1725 = add_ln731_1_fu_1591_p2.read();
        add_ln731_4_reg_1730 = add_ln731_4_fu_1597_p2.read();
        add_ln731_6_reg_1735 = add_ln731_6_fu_1609_p2.read();
        add_ln731_8_reg_1740 = add_ln731_8_fu_1615_p2.read();
        trunc_ln703_10_reg_1720 = mul_ln1118_11_fu_205_p2.read().range(39, 22);
        trunc_ln703_1_reg_1705 = mul_ln1118_2_fu_213_p2.read().range(39, 22);
        trunc_ln703_2_reg_1710 = mul_ln1118_3_fu_206_p2.read().range(39, 22);
        trunc_ln703_9_reg_1715 = mul_ln1118_10_fu_208_p2.read().range(39, 22);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = res_0_V_write_assign_fu_1658_p3.read();
        ap_return_1_int_reg = res_1_V_write_assign_fu_1685_p3.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_10_fu_1670_p2() {
    add_ln731_10_fu_1670_p2 = (!add_ln731_8_reg_1740.read().is_01() || !add_ln731_9_fu_1666_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln731_8_reg_1740.read()) + sc_biguint<18>(add_ln731_9_fu_1666_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_11_fu_1621_p2() {
    add_ln731_11_fu_1621_p2 = (!trunc_ln703_12_fu_1561_p4.read().is_01() || !trunc_ln703_11_fu_1551_p4.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_12_fu_1561_p4.read()) + sc_biguint<18>(trunc_ln703_11_fu_1551_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_12_fu_1627_p2() {
    add_ln731_12_fu_1627_p2 = (!trunc_ln703_14_fu_1581_p4.read().is_01() || !ap_const_lv18_1523.is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_14_fu_1581_p4.read()) + sc_biguint<18>(ap_const_lv18_1523));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_13_fu_1633_p2() {
    add_ln731_13_fu_1633_p2 = (!trunc_ln703_13_fu_1571_p4.read().is_01() || !add_ln731_12_fu_1627_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_13_fu_1571_p4.read()) + sc_biguint<18>(add_ln731_12_fu_1627_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_14_fu_1675_p2() {
    add_ln731_14_fu_1675_p2 = (!add_ln731_11_reg_1745.read().is_01() || !add_ln731_13_reg_1750.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln731_11_reg_1745.read()) + sc_biguint<18>(add_ln731_13_reg_1750.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_15_fu_1679_p2() {
    add_ln731_15_fu_1679_p2 = (!add_ln731_10_fu_1670_p2.read().is_01() || !add_ln731_14_fu_1675_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln731_10_fu_1670_p2.read()) + sc_biguint<18>(add_ln731_14_fu_1675_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_1_fu_1591_p2() {
    add_ln731_1_fu_1591_p2 = (!trunc_ln703_s_fu_1441_p4.read().is_01() || !trunc_ln_fu_1431_p4.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_s_fu_1441_p4.read()) + sc_biguint<18>(trunc_ln_fu_1431_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_2_fu_1639_p2() {
    add_ln731_2_fu_1639_p2 = (!trunc_ln703_2_reg_1710.read().is_01() || !trunc_ln703_1_reg_1705.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_2_reg_1710.read()) + sc_biguint<18>(trunc_ln703_1_reg_1705.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_3_fu_1643_p2() {
    add_ln731_3_fu_1643_p2 = (!add_ln731_1_reg_1725.read().is_01() || !add_ln731_2_fu_1639_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln731_1_reg_1725.read()) + sc_biguint<18>(add_ln731_2_fu_1639_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_4_fu_1597_p2() {
    add_ln731_4_fu_1597_p2 = (!trunc_ln703_4_fu_1481_p4.read().is_01() || !trunc_ln703_3_fu_1471_p4.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_4_fu_1481_p4.read()) + sc_biguint<18>(trunc_ln703_3_fu_1471_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_5_fu_1603_p2() {
    add_ln731_5_fu_1603_p2 = (!trunc_ln703_6_fu_1501_p4.read().is_01() || !ap_const_lv18_12B1.is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_6_fu_1501_p4.read()) + sc_biguint<18>(ap_const_lv18_12B1));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_6_fu_1609_p2() {
    add_ln731_6_fu_1609_p2 = (!trunc_ln703_5_fu_1491_p4.read().is_01() || !add_ln731_5_fu_1603_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_5_fu_1491_p4.read()) + sc_biguint<18>(add_ln731_5_fu_1603_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_7_fu_1648_p2() {
    add_ln731_7_fu_1648_p2 = (!add_ln731_4_reg_1730.read().is_01() || !add_ln731_6_reg_1735.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln731_4_reg_1730.read()) + sc_biguint<18>(add_ln731_6_reg_1735.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_8_fu_1615_p2() {
    add_ln731_8_fu_1615_p2 = (!trunc_ln703_8_fu_1521_p4.read().is_01() || !trunc_ln703_7_fu_1511_p4.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_8_fu_1521_p4.read()) + sc_biguint<18>(trunc_ln703_7_fu_1511_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_9_fu_1666_p2() {
    add_ln731_9_fu_1666_p2 = (!trunc_ln703_10_reg_1720.read().is_01() || !trunc_ln703_9_reg_1715.read().is_01())? sc_lv<18>(): (sc_biguint<18>(trunc_ln703_10_reg_1720.read()) + sc_biguint<18>(trunc_ln703_9_reg_1715.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_add_ln731_fu_1652_p2() {
    add_ln731_fu_1652_p2 = (!add_ln731_3_fu_1643_p2.read().is_01() || !add_ln731_7_fu_1648_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln731_3_fu_1643_p2.read()) + sc_biguint<18>(add_ln731_7_fu_1648_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = res_0_V_write_assign_fu_1658_p3.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = res_1_V_write_assign_fu_1685_p3.read();
    }
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_10_fu_208_p0() {
    mul_ln1118_10_fu_208_p0 = data_10_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_10_fu_208_p2() {
    mul_ln1118_10_fu_208_p2 = (!mul_ln1118_10_fu_208_p0.read().is_01() || !ap_const_lv40_DB36F.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_10_fu_208_p0.read()) * sc_biguint<40>(ap_const_lv40_DB36F);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_11_fu_205_p0() {
    mul_ln1118_11_fu_205_p0 = data_11_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_11_fu_205_p2() {
    mul_ln1118_11_fu_205_p2 = (!mul_ln1118_11_fu_205_p0.read().is_01() || !ap_const_lv40_FFFFEAB402.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_11_fu_205_p0.read()) * sc_bigint<40>(ap_const_lv40_FFFFEAB402);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_12_fu_209_p0() {
    mul_ln1118_12_fu_209_p0 = data_12_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_12_fu_209_p2() {
    mul_ln1118_12_fu_209_p2 = (!mul_ln1118_12_fu_209_p0.read().is_01() || !ap_const_lv40_FFFFF9AAD0.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_12_fu_209_p0.read()) * sc_bigint<40>(ap_const_lv40_FFFFF9AAD0);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_13_fu_211_p0() {
    mul_ln1118_13_fu_211_p0 = data_13_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_13_fu_211_p2() {
    mul_ln1118_13_fu_211_p2 = (!mul_ln1118_13_fu_211_p0.read().is_01() || !ap_const_lv40_FFFFE9EAD7.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_13_fu_211_p0.read()) * sc_bigint<40>(ap_const_lv40_FFFFE9EAD7);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_14_fu_212_p0() {
    mul_ln1118_14_fu_212_p0 = data_14_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_14_fu_212_p2() {
    mul_ln1118_14_fu_212_p2 = (!mul_ln1118_14_fu_212_p0.read().is_01() || !ap_const_lv40_960A1.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_14_fu_212_p0.read()) * sc_biguint<40>(ap_const_lv40_960A1);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_15_fu_198_p0() {
    mul_ln1118_15_fu_198_p0 = data_15_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_15_fu_198_p2() {
    mul_ln1118_15_fu_198_p2 = (!mul_ln1118_15_fu_198_p0.read().is_01() || !ap_const_lv40_24F4A3.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_15_fu_198_p0.read()) * sc_biguint<40>(ap_const_lv40_24F4A3);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_1_fu_203_p0() {
    mul_ln1118_1_fu_203_p0 = data_1_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_1_fu_203_p2() {
    mul_ln1118_1_fu_203_p2 = (!mul_ln1118_1_fu_203_p0.read().is_01() || !ap_const_lv40_21C23.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_1_fu_203_p0.read()) * sc_biguint<40>(ap_const_lv40_21C23);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_2_fu_213_p0() {
    mul_ln1118_2_fu_213_p0 = data_2_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_2_fu_213_p2() {
    mul_ln1118_2_fu_213_p2 = (!mul_ln1118_2_fu_213_p0.read().is_01() || !ap_const_lv40_8B842.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_2_fu_213_p0.read()) * sc_biguint<40>(ap_const_lv40_8B842);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_3_fu_206_p0() {
    mul_ln1118_3_fu_206_p0 = data_3_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_3_fu_206_p2() {
    mul_ln1118_3_fu_206_p2 = (!mul_ln1118_3_fu_206_p0.read().is_01() || !ap_const_lv40_FFFFFBE035.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_3_fu_206_p0.read()) * sc_bigint<40>(ap_const_lv40_FFFFFBE035);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_4_fu_201_p0() {
    mul_ln1118_4_fu_201_p0 = data_4_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_4_fu_201_p2() {
    mul_ln1118_4_fu_201_p2 = (!mul_ln1118_4_fu_201_p0.read().is_01() || !ap_const_lv40_FFFFF7D459.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_4_fu_201_p0.read()) * sc_bigint<40>(ap_const_lv40_FFFFF7D459);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_5_fu_202_p0() {
    mul_ln1118_5_fu_202_p0 = data_5_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_5_fu_202_p2() {
    mul_ln1118_5_fu_202_p2 = (!mul_ln1118_5_fu_202_p0.read().is_01() || !ap_const_lv40_FFFFFF5EC8.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_5_fu_202_p0.read()) * sc_bigint<40>(ap_const_lv40_FFFFFF5EC8);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_6_fu_204_p0() {
    mul_ln1118_6_fu_204_p0 = data_6_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_6_fu_204_p2() {
    mul_ln1118_6_fu_204_p2 = (!mul_ln1118_6_fu_204_p0.read().is_01() || !ap_const_lv40_36CD2.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_6_fu_204_p0.read()) * sc_biguint<40>(ap_const_lv40_36CD2);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_7_fu_210_p0() {
    mul_ln1118_7_fu_210_p0 = data_7_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_7_fu_210_p2() {
    mul_ln1118_7_fu_210_p2 = (!mul_ln1118_7_fu_210_p0.read().is_01() || !ap_const_lv40_5A124.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_7_fu_210_p0.read()) * sc_biguint<40>(ap_const_lv40_5A124);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_8_fu_207_p0() {
    mul_ln1118_8_fu_207_p0 = data_8_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_8_fu_207_p2() {
    mul_ln1118_8_fu_207_p2 = (!mul_ln1118_8_fu_207_p0.read().is_01() || !ap_const_lv40_249452.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_8_fu_207_p0.read()) * sc_biguint<40>(ap_const_lv40_249452);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_9_fu_200_p0() {
    mul_ln1118_9_fu_200_p0 = data_9_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_9_fu_200_p2() {
    mul_ln1118_9_fu_200_p2 = (!mul_ln1118_9_fu_200_p0.read().is_01() || !ap_const_lv40_D1D4C.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_9_fu_200_p0.read()) * sc_biguint<40>(ap_const_lv40_D1D4C);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_fu_199_p0() {
    mul_ln1118_fu_199_p0 = data_0_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_mul_ln1118_fu_199_p2() {
    mul_ln1118_fu_199_p2 = (!mul_ln1118_fu_199_p0.read().is_01() || !ap_const_lv40_140B0.is_01())? sc_lv<40>(): sc_bigint<24>(mul_ln1118_fu_199_p0.read()) * sc_biguint<40>(ap_const_lv40_140B0);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_res_0_V_write_assign_fu_1658_p3() {
    res_0_V_write_assign_fu_1658_p3 = esl_concat<18,6>(add_ln731_fu_1652_p2.read(), ap_const_lv6_0);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_res_1_V_write_assign_fu_1685_p3() {
    res_1_V_write_assign_fu_1685_p3 = esl_concat<18,6>(add_ln731_15_fu_1679_p2.read(), ap_const_lv6_0);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_11_fu_1551_p4() {
    trunc_ln703_11_fu_1551_p4 = mul_ln1118_12_fu_209_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_12_fu_1561_p4() {
    trunc_ln703_12_fu_1561_p4 = mul_ln1118_13_fu_211_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_13_fu_1571_p4() {
    trunc_ln703_13_fu_1571_p4 = mul_ln1118_14_fu_212_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_14_fu_1581_p4() {
    trunc_ln703_14_fu_1581_p4 = mul_ln1118_15_fu_198_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_3_fu_1471_p4() {
    trunc_ln703_3_fu_1471_p4 = mul_ln1118_4_fu_201_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_4_fu_1481_p4() {
    trunc_ln703_4_fu_1481_p4 = mul_ln1118_5_fu_202_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_5_fu_1491_p4() {
    trunc_ln703_5_fu_1491_p4 = mul_ln1118_6_fu_204_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_6_fu_1501_p4() {
    trunc_ln703_6_fu_1501_p4 = mul_ln1118_7_fu_210_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_7_fu_1511_p4() {
    trunc_ln703_7_fu_1511_p4 = mul_ln1118_8_fu_207_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_8_fu_1521_p4() {
    trunc_ln703_8_fu_1521_p4 = mul_ln1118_9_fu_200_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln703_s_fu_1441_p4() {
    trunc_ln703_s_fu_1441_p4 = mul_ln1118_1_fu_203_p2.read().range(39, 22);
}

void dense_latency_ap_fixed_ap_fixed_config11_0_0_0::thread_trunc_ln_fu_1431_p4() {
    trunc_ln_fu_1431_p4 = mul_ln1118_fu_199_p2.read().range(39, 22);
}

}

