// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="emtfptnn,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx690t-ffg1927-2,HLS_INPUT_CLOCK=7.692000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=8.473500,HLS_SYN_LAT=13,HLS_SYN_TPT=1,HLS_SYN_MEM=18,HLS_SYN_DSP=796,HLS_SYN_FF=11969,HLS_SYN_LUT=52811,HLS_VERSION=2020_1}" *)

module emtfptnn (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input1_0_V,
        input1_1_V,
        input1_2_V,
        input1_3_V,
        input1_4_V,
        input1_5_V,
        input1_6_V,
        input1_7_V,
        input1_8_V,
        input1_9_V,
        input1_10_V,
        input1_11_V,
        input1_12_V,
        input1_13_V,
        input1_14_V,
        input1_15_V,
        input1_16_V,
        input1_17_V,
        input1_18_V,
        input1_19_V,
        input1_20_V,
        input1_21_V,
        input1_22_V,
        input1_23_V,
        input1_24_V,
        input1_25_V,
        input1_26_V,
        input1_27_V,
        input1_28_V,
        layer12_out_0_V,
        layer12_out_0_V_ap_vld,
        layer12_out_1_V,
        layer12_out_1_V_ap_vld,
        const_size_in_1,
        const_size_in_1_ap_vld,
        const_size_out_1,
        const_size_out_1_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [12:0] input1_0_V;
input  [12:0] input1_1_V;
input  [12:0] input1_2_V;
input  [12:0] input1_3_V;
input  [12:0] input1_4_V;
input  [12:0] input1_5_V;
input  [12:0] input1_6_V;
input  [12:0] input1_7_V;
input  [12:0] input1_8_V;
input  [12:0] input1_9_V;
input  [12:0] input1_10_V;
input  [12:0] input1_11_V;
input  [12:0] input1_12_V;
input  [12:0] input1_13_V;
input  [12:0] input1_14_V;
input  [12:0] input1_15_V;
input  [12:0] input1_16_V;
input  [12:0] input1_17_V;
input  [12:0] input1_18_V;
input  [12:0] input1_19_V;
input  [12:0] input1_20_V;
input  [12:0] input1_21_V;
input  [12:0] input1_22_V;
input  [12:0] input1_23_V;
input  [12:0] input1_24_V;
input  [12:0] input1_25_V;
input  [12:0] input1_26_V;
input  [12:0] input1_27_V;
input  [12:0] input1_28_V;
output  [7:0] layer12_out_0_V;
output   layer12_out_0_V_ap_vld;
output  [7:0] layer12_out_1_V;
output   layer12_out_1_V_ap_vld;
output  [15:0] const_size_in_1;
output   const_size_in_1_ap_vld;
output  [15:0] const_size_out_1;
output   const_size_out_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer12_out_0_V_ap_vld;
reg layer12_out_1_V_ap_vld;
reg const_size_in_1_ap_vld;
reg const_size_out_1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_11001;
reg   [23:0] layer2_out_0_V_reg_957;
reg   [23:0] layer2_out_1_V_reg_962;
reg   [23:0] layer2_out_2_V_reg_967;
reg   [23:0] layer2_out_3_V_reg_972;
reg   [23:0] layer2_out_4_V_reg_977;
reg   [23:0] layer2_out_5_V_reg_982;
reg   [23:0] layer2_out_6_V_reg_987;
reg   [23:0] layer2_out_7_V_reg_992;
reg   [23:0] layer2_out_8_V_reg_997;
reg   [23:0] layer2_out_9_V_reg_1002;
reg   [23:0] layer2_out_10_V_reg_1007;
reg   [23:0] layer2_out_11_V_reg_1012;
reg   [23:0] layer2_out_12_V_reg_1017;
reg   [23:0] layer2_out_13_V_reg_1022;
reg   [23:0] layer2_out_14_V_reg_1027;
reg   [23:0] layer2_out_15_V_reg_1032;
reg   [23:0] layer2_out_16_V_reg_1037;
reg   [23:0] layer2_out_17_V_reg_1042;
reg   [23:0] layer2_out_18_V_reg_1047;
reg   [23:0] layer2_out_19_V_reg_1052;
reg   [23:0] layer2_out_20_V_reg_1057;
reg   [23:0] layer2_out_21_V_reg_1062;
reg   [23:0] layer2_out_22_V_reg_1067;
reg   [23:0] layer2_out_23_V_reg_1072;
reg   [23:0] layer2_out_24_V_reg_1077;
reg   [23:0] layer2_out_25_V_reg_1082;
reg   [23:0] layer2_out_26_V_reg_1087;
reg   [23:0] layer2_out_27_V_reg_1092;
reg   [23:0] layer2_out_28_V_reg_1097;
reg   [23:0] layer3_out_0_V_reg_1102;
reg   [23:0] layer3_out_1_V_reg_1107;
reg   [23:0] layer3_out_2_V_reg_1112;
reg   [23:0] layer3_out_3_V_reg_1117;
reg   [23:0] layer3_out_4_V_reg_1122;
reg   [23:0] layer3_out_5_V_reg_1127;
reg   [23:0] layer3_out_6_V_reg_1132;
reg   [23:0] layer3_out_7_V_reg_1137;
reg   [23:0] layer3_out_8_V_reg_1142;
reg   [23:0] layer3_out_9_V_reg_1147;
reg   [23:0] layer3_out_10_V_reg_1152;
reg   [23:0] layer3_out_11_V_reg_1157;
reg   [23:0] layer3_out_12_V_reg_1162;
reg   [23:0] layer3_out_13_V_reg_1167;
reg   [23:0] layer3_out_14_V_reg_1172;
reg   [23:0] layer3_out_15_V_reg_1177;
reg   [23:0] layer3_out_16_V_reg_1182;
reg   [23:0] layer3_out_17_V_reg_1187;
reg   [23:0] layer3_out_18_V_reg_1192;
reg   [23:0] layer3_out_19_V_reg_1197;
reg   [23:0] layer6_out_0_V_reg_1202;
reg   [23:0] layer6_out_1_V_reg_1207;
reg   [23:0] layer6_out_2_V_reg_1212;
reg   [23:0] layer6_out_3_V_reg_1217;
reg   [23:0] layer6_out_4_V_reg_1222;
reg   [23:0] layer6_out_5_V_reg_1227;
reg   [23:0] layer6_out_6_V_reg_1232;
reg   [23:0] layer6_out_7_V_reg_1237;
reg   [23:0] layer6_out_8_V_reg_1242;
reg   [23:0] layer6_out_9_V_reg_1247;
reg   [23:0] layer6_out_10_V_reg_1252;
reg   [23:0] layer6_out_11_V_reg_1257;
reg   [23:0] layer6_out_12_V_reg_1262;
reg   [23:0] layer6_out_13_V_reg_1267;
reg   [23:0] layer6_out_14_V_reg_1272;
reg   [23:0] layer6_out_15_V_reg_1277;
reg   [23:0] layer6_out_16_V_reg_1282;
reg   [23:0] layer6_out_17_V_reg_1287;
reg   [23:0] layer6_out_18_V_reg_1292;
reg   [23:0] layer6_out_19_V_reg_1297;
reg   [23:0] layer7_out_0_V_reg_1302;
reg   [23:0] layer7_out_1_V_reg_1307;
reg   [23:0] layer7_out_2_V_reg_1312;
reg   [23:0] layer7_out_3_V_reg_1317;
reg   [23:0] layer7_out_4_V_reg_1322;
reg   [23:0] layer7_out_5_V_reg_1327;
reg   [23:0] layer7_out_6_V_reg_1332;
reg   [23:0] layer7_out_7_V_reg_1337;
reg   [23:0] layer7_out_8_V_reg_1342;
reg   [23:0] layer7_out_9_V_reg_1347;
reg   [23:0] layer7_out_10_V_reg_1352;
reg   [23:0] layer7_out_11_V_reg_1357;
reg   [23:0] layer7_out_12_V_reg_1362;
reg   [23:0] layer7_out_13_V_reg_1367;
reg   [23:0] layer7_out_14_V_reg_1372;
reg   [23:0] layer7_out_15_V_reg_1377;
reg    ap_block_pp0_stage0_subdone;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_0;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_1;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_2;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_3;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_4;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_5;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_6;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_7;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_8;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_9;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_10;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_11;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_12;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_13;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_14;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_15;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_16;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_17;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_18;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_19;
reg    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call99;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call99;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call99;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call99;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call99;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call99;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call99;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call99;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call99;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call99;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call99;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call99;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call99;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call99;
reg    ap_block_pp0_stage0_11001_ignoreCallOp74;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_0;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_1;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_2;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_3;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_4;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_5;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_6;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_7;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_8;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_9;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_10;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_11;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_12;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_13;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_14;
wire   [23:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_15;
reg    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call141;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call141;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call141;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call141;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call141;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call141;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call141;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call141;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call141;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call141;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call141;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call141;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call141;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call141;
reg    ap_block_pp0_stage0_11001_ignoreCallOp121;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_done;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_idle;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_ready;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_0;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_1;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_2;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_3;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_4;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_5;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_6;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_7;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_8;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_9;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_10;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_11;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_12;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_13;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_14;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_15;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_16;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_17;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_18;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_19;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_done;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_idle;
wire    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_ready;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_0;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_1;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_2;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_3;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_4;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_5;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_6;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_7;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_8;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_9;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_10;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_11;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_12;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_13;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_14;
wire   [23:0] grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_15;
wire   [23:0] grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_return_0;
wire   [23:0] grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_return_1;
reg    grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call175;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call175;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call175;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call175;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call175;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call175;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call175;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call175;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call175;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call175;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call175;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call175;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call175;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call175;
reg    ap_block_pp0_stage0_11001_ignoreCallOp158;
wire    call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_ready;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_0;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_1;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_2;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_3;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_4;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_5;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_6;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_7;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_8;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_9;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_10;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_11;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_12;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_13;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_14;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_15;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_16;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_17;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_18;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_19;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_20;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_21;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_22;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_23;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_24;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_25;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_26;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_27;
wire   [23:0] call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_28;
wire    call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_ready;
wire   [7:0] call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_return_0;
wire   [7:0] call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_return_1;
wire    ap_block_pp0_stage0;
reg    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start_reg;
reg    grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start_reg;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to12;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start_reg = 1'b0;
#0 grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start_reg = 1'b0;
end

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0 grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(layer2_out_0_V_reg_957),
    .data_1_V_read(layer2_out_1_V_reg_962),
    .data_2_V_read(layer2_out_2_V_reg_967),
    .data_3_V_read(layer2_out_3_V_reg_972),
    .data_4_V_read(layer2_out_4_V_reg_977),
    .data_5_V_read(layer2_out_5_V_reg_982),
    .data_6_V_read(layer2_out_6_V_reg_987),
    .data_7_V_read(layer2_out_7_V_reg_992),
    .data_8_V_read(layer2_out_8_V_reg_997),
    .data_9_V_read(layer2_out_9_V_reg_1002),
    .data_10_V_read(layer2_out_10_V_reg_1007),
    .data_11_V_read(layer2_out_11_V_reg_1012),
    .data_12_V_read(layer2_out_12_V_reg_1017),
    .data_13_V_read(layer2_out_13_V_reg_1022),
    .data_14_V_read(layer2_out_14_V_reg_1027),
    .data_15_V_read(layer2_out_15_V_reg_1032),
    .data_16_V_read(layer2_out_16_V_reg_1037),
    .data_17_V_read(layer2_out_17_V_reg_1042),
    .data_18_V_read(layer2_out_18_V_reg_1047),
    .data_19_V_read(layer2_out_19_V_reg_1052),
    .data_20_V_read(layer2_out_20_V_reg_1057),
    .data_21_V_read(layer2_out_21_V_reg_1062),
    .data_22_V_read(layer2_out_22_V_reg_1067),
    .data_23_V_read(layer2_out_23_V_reg_1072),
    .data_24_V_read(layer2_out_24_V_reg_1077),
    .data_25_V_read(layer2_out_25_V_reg_1082),
    .data_26_V_read(layer2_out_26_V_reg_1087),
    .data_27_V_read(layer2_out_27_V_reg_1092),
    .data_28_V_read(layer2_out_28_V_reg_1097),
    .ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_13),
    .ap_return_14(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_14),
    .ap_return_15(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_15),
    .ap_return_16(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_16),
    .ap_return_17(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_17),
    .ap_return_18(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_18),
    .ap_return_19(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_19),
    .ap_ce(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_ce)
);

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0 grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(layer6_out_0_V_reg_1202),
    .data_1_V_read(layer6_out_1_V_reg_1207),
    .data_2_V_read(layer6_out_2_V_reg_1212),
    .data_3_V_read(layer6_out_3_V_reg_1217),
    .data_4_V_read(layer6_out_4_V_reg_1222),
    .data_5_V_read(layer6_out_5_V_reg_1227),
    .data_6_V_read(layer6_out_6_V_reg_1232),
    .data_7_V_read(layer6_out_7_V_reg_1237),
    .data_8_V_read(layer6_out_8_V_reg_1242),
    .data_9_V_read(layer6_out_9_V_reg_1247),
    .data_10_V_read(layer6_out_10_V_reg_1252),
    .data_11_V_read(layer6_out_11_V_reg_1257),
    .data_12_V_read(layer6_out_12_V_reg_1262),
    .data_13_V_read(layer6_out_13_V_reg_1267),
    .data_14_V_read(layer6_out_14_V_reg_1272),
    .data_15_V_read(layer6_out_15_V_reg_1277),
    .data_16_V_read(layer6_out_16_V_reg_1282),
    .data_17_V_read(layer6_out_17_V_reg_1287),
    .data_18_V_read(layer6_out_18_V_reg_1292),
    .data_19_V_read(layer6_out_19_V_reg_1297),
    .ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_13),
    .ap_return_14(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_14),
    .ap_return_15(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_15),
    .ap_ce(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_ce)
);

tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start),
    .ap_done(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_done),
    .ap_idle(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_idle),
    .ap_ready(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_ready),
    .data_0_V_read(layer3_out_0_V_reg_1102),
    .data_1_V_read(layer3_out_1_V_reg_1107),
    .data_2_V_read(layer3_out_2_V_reg_1112),
    .data_3_V_read(layer3_out_3_V_reg_1117),
    .data_4_V_read(layer3_out_4_V_reg_1122),
    .data_5_V_read(layer3_out_5_V_reg_1127),
    .data_6_V_read(layer3_out_6_V_reg_1132),
    .data_7_V_read(layer3_out_7_V_reg_1137),
    .data_8_V_read(layer3_out_8_V_reg_1142),
    .data_9_V_read(layer3_out_9_V_reg_1147),
    .data_10_V_read(layer3_out_10_V_reg_1152),
    .data_11_V_read(layer3_out_11_V_reg_1157),
    .data_12_V_read(layer3_out_12_V_reg_1162),
    .data_13_V_read(layer3_out_13_V_reg_1167),
    .data_14_V_read(layer3_out_14_V_reg_1172),
    .data_15_V_read(layer3_out_15_V_reg_1177),
    .data_16_V_read(layer3_out_16_V_reg_1182),
    .data_17_V_read(layer3_out_17_V_reg_1187),
    .data_18_V_read(layer3_out_18_V_reg_1192),
    .data_19_V_read(layer3_out_19_V_reg_1197),
    .ap_return_0(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_0),
    .ap_return_1(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_1),
    .ap_return_2(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_2),
    .ap_return_3(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_3),
    .ap_return_4(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_4),
    .ap_return_5(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_5),
    .ap_return_6(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_6),
    .ap_return_7(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_7),
    .ap_return_8(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_8),
    .ap_return_9(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_9),
    .ap_return_10(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_10),
    .ap_return_11(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_11),
    .ap_return_12(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_12),
    .ap_return_13(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_13),
    .ap_return_14(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_14),
    .ap_return_15(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_15),
    .ap_return_16(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_16),
    .ap_return_17(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_17),
    .ap_return_18(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_18),
    .ap_return_19(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_19)
);

tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start),
    .ap_done(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_done),
    .ap_idle(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_idle),
    .ap_ready(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_ready),
    .data_0_V_read(layer7_out_0_V_reg_1302),
    .data_1_V_read(layer7_out_1_V_reg_1307),
    .data_2_V_read(layer7_out_2_V_reg_1312),
    .data_3_V_read(layer7_out_3_V_reg_1317),
    .data_4_V_read(layer7_out_4_V_reg_1322),
    .data_5_V_read(layer7_out_5_V_reg_1327),
    .data_6_V_read(layer7_out_6_V_reg_1332),
    .data_7_V_read(layer7_out_7_V_reg_1337),
    .data_8_V_read(layer7_out_8_V_reg_1342),
    .data_9_V_read(layer7_out_9_V_reg_1347),
    .data_10_V_read(layer7_out_10_V_reg_1352),
    .data_11_V_read(layer7_out_11_V_reg_1357),
    .data_12_V_read(layer7_out_12_V_reg_1362),
    .data_13_V_read(layer7_out_13_V_reg_1367),
    .data_14_V_read(layer7_out_14_V_reg_1372),
    .data_15_V_read(layer7_out_15_V_reg_1377),
    .ap_return_0(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_0),
    .ap_return_1(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_1),
    .ap_return_2(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_2),
    .ap_return_3(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_3),
    .ap_return_4(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_4),
    .ap_return_5(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_5),
    .ap_return_6(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_6),
    .ap_return_7(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_7),
    .ap_return_8(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_8),
    .ap_return_9(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_9),
    .ap_return_10(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_10),
    .ap_return_11(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_11),
    .ap_return_12(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_12),
    .ap_return_13(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_13),
    .ap_return_14(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_14),
    .ap_return_15(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_15)
);

dense_latency_ap_fixed_ap_fixed_config11_0_0_0 grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_0),
    .data_1_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_1),
    .data_2_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_2),
    .data_3_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_3),
    .data_4_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_4),
    .data_5_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_5),
    .data_6_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_6),
    .data_7_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_7),
    .data_8_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_8),
    .data_9_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_9),
    .data_10_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_10),
    .data_11_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_11),
    .data_12_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_12),
    .data_13_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_13),
    .data_14_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_14),
    .data_15_V_read(grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_return_15),
    .ap_return_0(grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_return_1),
    .ap_ce(grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_ce)
);

normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449(
    .ap_ready(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_ready),
    .data_0_V_read(input1_0_V),
    .data_1_V_read(input1_1_V),
    .data_2_V_read(input1_2_V),
    .data_3_V_read(input1_3_V),
    .data_4_V_read(input1_4_V),
    .data_5_V_read(input1_5_V),
    .data_6_V_read(input1_6_V),
    .data_7_V_read(input1_7_V),
    .data_8_V_read(input1_8_V),
    .data_9_V_read(input1_9_V),
    .data_10_V_read(input1_10_V),
    .data_11_V_read(input1_11_V),
    .data_12_V_read(input1_12_V),
    .data_13_V_read(input1_13_V),
    .data_14_V_read(input1_14_V),
    .data_15_V_read(input1_15_V),
    .data_16_V_read(input1_16_V),
    .data_17_V_read(input1_17_V),
    .data_18_V_read(input1_18_V),
    .data_19_V_read(input1_19_V),
    .data_20_V_read(input1_20_V),
    .data_21_V_read(input1_21_V),
    .data_22_V_read(input1_22_V),
    .data_23_V_read(input1_23_V),
    .data_24_V_read(input1_24_V),
    .data_25_V_read(input1_25_V),
    .data_26_V_read(input1_26_V),
    .data_27_V_read(input1_27_V),
    .data_28_V_read(input1_28_V),
    .ap_return_0(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_0),
    .ap_return_1(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_1),
    .ap_return_2(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_2),
    .ap_return_3(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_3),
    .ap_return_4(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_4),
    .ap_return_5(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_5),
    .ap_return_6(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_6),
    .ap_return_7(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_7),
    .ap_return_8(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_8),
    .ap_return_9(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_9),
    .ap_return_10(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_10),
    .ap_return_11(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_11),
    .ap_return_12(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_12),
    .ap_return_13(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_13),
    .ap_return_14(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_14),
    .ap_return_15(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_15),
    .ap_return_16(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_16),
    .ap_return_17(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_17),
    .ap_return_18(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_18),
    .ap_return_19(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_19),
    .ap_return_20(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_20),
    .ap_return_21(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_21),
    .ap_return_22(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_22),
    .ap_return_23(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_23),
    .ap_return_24(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_24),
    .ap_return_25(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_25),
    .ap_return_26(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_26),
    .ap_return_27(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_27),
    .ap_return_28(call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_28)
);

relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511(
    .ap_ready(call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_ready),
    .data_0_V_read(grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_return_0),
    .data_1_V_read(grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_return_1),
    .ap_return_0(call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_return_0),
    .ap_return_1(call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
            grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start_reg <= 1'b1;
        end else if ((grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_ready == 1'b1)) begin
            grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
            grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start_reg <= 1'b1;
        end else if ((grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_ready == 1'b1)) begin
            grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_0_V_reg_957 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_0;
        layer2_out_10_V_reg_1007 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_10;
        layer2_out_11_V_reg_1012 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_11;
        layer2_out_12_V_reg_1017 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_12;
        layer2_out_13_V_reg_1022 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_13;
        layer2_out_14_V_reg_1027 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_14;
        layer2_out_15_V_reg_1032 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_15;
        layer2_out_16_V_reg_1037 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_16;
        layer2_out_17_V_reg_1042 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_17;
        layer2_out_18_V_reg_1047 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_18;
        layer2_out_19_V_reg_1052 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_19;
        layer2_out_1_V_reg_962 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_1;
        layer2_out_20_V_reg_1057 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_20;
        layer2_out_21_V_reg_1062 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_21;
        layer2_out_22_V_reg_1067 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_22;
        layer2_out_23_V_reg_1072 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_23;
        layer2_out_24_V_reg_1077 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_24;
        layer2_out_25_V_reg_1082 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_25;
        layer2_out_26_V_reg_1087 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_26;
        layer2_out_27_V_reg_1092 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_27;
        layer2_out_28_V_reg_1097 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_28;
        layer2_out_2_V_reg_967 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_2;
        layer2_out_3_V_reg_972 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_3;
        layer2_out_4_V_reg_977 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_4;
        layer2_out_5_V_reg_982 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_5;
        layer2_out_6_V_reg_987 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_6;
        layer2_out_7_V_reg_992 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_7;
        layer2_out_8_V_reg_997 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_8;
        layer2_out_9_V_reg_1002 <= call_ret1_normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s_fu_449_ap_return_9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        layer3_out_0_V_reg_1102 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_0;
        layer3_out_10_V_reg_1152 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_10;
        layer3_out_11_V_reg_1157 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_11;
        layer3_out_12_V_reg_1162 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_12;
        layer3_out_13_V_reg_1167 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_13;
        layer3_out_14_V_reg_1172 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_14;
        layer3_out_15_V_reg_1177 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_15;
        layer3_out_16_V_reg_1182 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_16;
        layer3_out_17_V_reg_1187 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_17;
        layer3_out_18_V_reg_1192 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_18;
        layer3_out_19_V_reg_1197 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_19;
        layer3_out_1_V_reg_1107 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_1;
        layer3_out_2_V_reg_1112 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_2;
        layer3_out_3_V_reg_1117 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_3;
        layer3_out_4_V_reg_1122 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_4;
        layer3_out_5_V_reg_1127 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_5;
        layer3_out_6_V_reg_1132 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_6;
        layer3_out_7_V_reg_1137 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_7;
        layer3_out_8_V_reg_1142 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_8;
        layer3_out_9_V_reg_1147 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_return_9;
        layer6_out_0_V_reg_1202 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_0;
        layer6_out_10_V_reg_1252 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_10;
        layer6_out_11_V_reg_1257 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_11;
        layer6_out_12_V_reg_1262 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_12;
        layer6_out_13_V_reg_1267 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_13;
        layer6_out_14_V_reg_1272 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_14;
        layer6_out_15_V_reg_1277 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_15;
        layer6_out_16_V_reg_1282 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_16;
        layer6_out_17_V_reg_1287 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_17;
        layer6_out_18_V_reg_1292 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_18;
        layer6_out_19_V_reg_1297 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_19;
        layer6_out_1_V_reg_1207 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_1;
        layer6_out_2_V_reg_1212 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_2;
        layer6_out_3_V_reg_1217 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_3;
        layer6_out_4_V_reg_1222 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_4;
        layer6_out_5_V_reg_1227 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_5;
        layer6_out_6_V_reg_1232 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_6;
        layer6_out_7_V_reg_1237 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_7;
        layer6_out_8_V_reg_1242 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_8;
        layer6_out_9_V_reg_1247 <= grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_return_9;
        layer7_out_0_V_reg_1302 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_0;
        layer7_out_10_V_reg_1352 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_10;
        layer7_out_11_V_reg_1357 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_11;
        layer7_out_12_V_reg_1362 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_12;
        layer7_out_13_V_reg_1367 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_13;
        layer7_out_14_V_reg_1372 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_14;
        layer7_out_15_V_reg_1377 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_15;
        layer7_out_1_V_reg_1307 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_1;
        layer7_out_2_V_reg_1312 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_2;
        layer7_out_3_V_reg_1317 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_3;
        layer7_out_4_V_reg_1322 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_4;
        layer7_out_5_V_reg_1327 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_5;
        layer7_out_6_V_reg_1332 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_6;
        layer7_out_7_V_reg_1337 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_7;
        layer7_out_8_V_reg_1342 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_8;
        layer7_out_9_V_reg_1347 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_return_9;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to12 = 1'b1;
    end else begin
        ap_idle_pp0_0to12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to12 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        const_size_in_1_ap_vld = 1'b1;
    end else begin
        const_size_in_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        const_size_out_1_ap_vld = 1'b1;
    end else begin
        const_size_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp74) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_324_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp121) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_fu_357_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp158) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_ap_fixed_config11_0_0_0_fu_429_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        layer12_out_0_V_ap_vld = 1'b1;
    end else begin
        layer12_out_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        layer12_out_1_V_ap_vld = 1'b1;
    end else begin
        layer12_out_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp121 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp158 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp74 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call99 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call141 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call175 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call99 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call141 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call175 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign const_size_in_1 = 16'd29;

assign const_size_out_1 = 16'd2;

assign grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start = grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_fu_407_ap_start_reg;

assign grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start = grp_tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_fu_381_ap_start_reg;

assign layer12_out_0_V = call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_return_0;

assign layer12_out_1_V = call_ret_relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s_fu_511_ap_return_1;

endmodule //emtfptnn
