// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] data_0_V_read;
input  [23:0] data_1_V_read;
input  [23:0] data_2_V_read;
input  [23:0] data_3_V_read;
input  [23:0] data_4_V_read;
input  [23:0] data_5_V_read;
input  [23:0] data_6_V_read;
input  [23:0] data_7_V_read;
input  [23:0] data_8_V_read;
input  [23:0] data_9_V_read;
input  [23:0] data_10_V_read;
input  [23:0] data_11_V_read;
input  [23:0] data_12_V_read;
input  [23:0] data_13_V_read;
input  [23:0] data_14_V_read;
input  [23:0] data_15_V_read;
output  [23:0] ap_return_0;
output  [23:0] ap_return_1;
output  [23:0] ap_return_2;
output  [23:0] ap_return_3;
output  [23:0] ap_return_4;
output  [23:0] ap_return_5;
output  [23:0] ap_return_6;
output  [23:0] ap_return_7;
output  [23:0] ap_return_8;
output  [23:0] ap_return_9;
output  [23:0] ap_return_10;
output  [23:0] ap_return_11;
output  [23:0] ap_return_12;
output  [23:0] ap_return_13;
output  [23:0] ap_return_14;
output  [23:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] tanh_table3_address0;
reg    tanh_table3_ce0;
wire   [10:0] tanh_table3_q0;
wire   [9:0] tanh_table3_address1;
reg    tanh_table3_ce1;
wire   [10:0] tanh_table3_q1;
wire   [9:0] tanh_table3_address2;
reg    tanh_table3_ce2;
wire   [10:0] tanh_table3_q2;
wire   [9:0] tanh_table3_address3;
reg    tanh_table3_ce3;
wire   [10:0] tanh_table3_q3;
wire   [9:0] tanh_table3_address4;
reg    tanh_table3_ce4;
wire   [10:0] tanh_table3_q4;
wire   [9:0] tanh_table3_address5;
reg    tanh_table3_ce5;
wire   [10:0] tanh_table3_q5;
wire   [9:0] tanh_table3_address6;
reg    tanh_table3_ce6;
wire   [10:0] tanh_table3_q6;
wire   [9:0] tanh_table3_address7;
reg    tanh_table3_ce7;
wire   [10:0] tanh_table3_q7;
wire   [9:0] tanh_table3_address8;
reg    tanh_table3_ce8;
wire   [10:0] tanh_table3_q8;
wire   [9:0] tanh_table3_address9;
reg    tanh_table3_ce9;
wire   [10:0] tanh_table3_q9;
wire   [9:0] tanh_table3_address10;
reg    tanh_table3_ce10;
wire   [10:0] tanh_table3_q10;
wire   [9:0] tanh_table3_address11;
reg    tanh_table3_ce11;
wire   [10:0] tanh_table3_q11;
wire   [9:0] tanh_table3_address12;
reg    tanh_table3_ce12;
wire   [10:0] tanh_table3_q12;
wire   [9:0] tanh_table3_address13;
reg    tanh_table3_ce13;
wire   [10:0] tanh_table3_q13;
wire   [9:0] tanh_table3_address14;
reg    tanh_table3_ce14;
wire   [10:0] tanh_table3_q14;
wire   [9:0] tanh_table3_address15;
reg    tanh_table3_ce15;
wire   [10:0] tanh_table3_q15;
wire   [9:0] select_ln476_fu_509_p3;
reg   [9:0] select_ln476_reg_2789;
wire   [9:0] select_ln476_1_fu_637_p3;
reg   [9:0] select_ln476_1_reg_2794;
wire   [9:0] select_ln476_2_fu_765_p3;
reg   [9:0] select_ln476_2_reg_2799;
wire   [9:0] select_ln476_3_fu_893_p3;
reg   [9:0] select_ln476_3_reg_2804;
wire   [9:0] select_ln476_4_fu_1021_p3;
reg   [9:0] select_ln476_4_reg_2809;
wire   [9:0] select_ln476_5_fu_1149_p3;
reg   [9:0] select_ln476_5_reg_2814;
wire   [9:0] select_ln476_6_fu_1277_p3;
reg   [9:0] select_ln476_6_reg_2819;
wire   [9:0] select_ln476_7_fu_1405_p3;
reg   [9:0] select_ln476_7_reg_2824;
wire   [9:0] select_ln476_8_fu_1533_p3;
reg   [9:0] select_ln476_8_reg_2829;
wire   [9:0] select_ln476_9_fu_1661_p3;
reg   [9:0] select_ln476_9_reg_2834;
wire   [9:0] select_ln476_10_fu_1789_p3;
reg   [9:0] select_ln476_10_reg_2839;
wire   [9:0] select_ln476_11_fu_1917_p3;
reg   [9:0] select_ln476_11_reg_2844;
wire   [9:0] select_ln476_12_fu_2045_p3;
reg   [9:0] select_ln476_12_reg_2849;
wire   [9:0] select_ln476_13_fu_2173_p3;
reg   [9:0] select_ln476_13_reg_2854;
wire   [9:0] select_ln476_14_fu_2301_p3;
reg   [9:0] select_ln476_14_reg_2859;
wire   [9:0] select_ln476_15_fu_2429_p3;
reg   [9:0] select_ln476_15_reg_2864;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln477_fu_2437_p1;
wire   [63:0] zext_ln477_20_fu_2441_p1;
wire   [63:0] zext_ln477_21_fu_2445_p1;
wire   [63:0] zext_ln477_22_fu_2449_p1;
wire   [63:0] zext_ln477_23_fu_2453_p1;
wire   [63:0] zext_ln477_24_fu_2457_p1;
wire   [63:0] zext_ln477_25_fu_2461_p1;
wire   [63:0] zext_ln477_26_fu_2465_p1;
wire   [63:0] zext_ln477_27_fu_2469_p1;
wire   [63:0] zext_ln477_28_fu_2473_p1;
wire   [63:0] zext_ln477_29_fu_2477_p1;
wire   [63:0] zext_ln477_30_fu_2481_p1;
wire   [63:0] zext_ln477_31_fu_2485_p1;
wire   [63:0] zext_ln477_32_fu_2489_p1;
wire   [63:0] zext_ln477_33_fu_2493_p1;
wire   [63:0] zext_ln477_34_fu_2497_p1;
wire   [14:0] tmp_s_fu_397_p4;
wire   [33:0] shl_ln_fu_389_p3;
wire   [8:0] trunc_ln851_fu_417_p1;
wire   [15:0] p_Result_4_fu_421_p3;
wire  signed [15:0] sext_ln850_fu_407_p1;
wire   [0:0] icmp_ln851_fu_429_p2;
wire   [15:0] add_ln700_fu_435_p2;
wire   [0:0] icmp_ln850_fu_411_p2;
wire   [15:0] select_ln851_fu_441_p3;
wire   [15:0] select_ln850_fu_449_p3;
wire   [14:0] trunc_ln473_fu_457_p1;
wire   [15:0] add_ln473_fu_461_p2;
wire   [0:0] tmp_87_fu_473_p3;
wire   [14:0] add_ln473_40_fu_467_p2;
wire   [14:0] select_ln475_fu_481_p3;
wire   [4:0] tmp_88_fu_493_p4;
wire   [0:0] icmp_ln476_fu_503_p2;
wire   [9:0] trunc_ln475_fu_489_p1;
wire   [14:0] tmp_41_fu_525_p4;
wire   [33:0] shl_ln1118_s_fu_517_p3;
wire   [8:0] trunc_ln851_20_fu_545_p1;
wire   [15:0] p_Result_4_1_fu_549_p3;
wire  signed [15:0] sext_ln850_20_fu_535_p1;
wire   [0:0] icmp_ln851_1_fu_557_p2;
wire   [15:0] add_ln700_20_fu_563_p2;
wire   [0:0] icmp_ln850_20_fu_539_p2;
wire   [15:0] select_ln851_1_fu_569_p3;
wire   [15:0] select_ln850_20_fu_577_p3;
wire   [14:0] trunc_ln473_20_fu_585_p1;
wire   [15:0] add_ln473_20_fu_589_p2;
wire   [0:0] tmp_89_fu_601_p3;
wire   [14:0] add_ln473_41_fu_595_p2;
wire   [14:0] select_ln475_1_fu_609_p3;
wire   [4:0] tmp_90_fu_621_p4;
wire   [0:0] icmp_ln476_20_fu_631_p2;
wire   [9:0] trunc_ln475_20_fu_617_p1;
wire   [14:0] tmp_43_fu_653_p4;
wire   [33:0] shl_ln1118_19_fu_645_p3;
wire   [8:0] trunc_ln851_21_fu_673_p1;
wire   [15:0] p_Result_4_2_fu_677_p3;
wire  signed [15:0] sext_ln850_21_fu_663_p1;
wire   [0:0] icmp_ln851_2_fu_685_p2;
wire   [15:0] add_ln700_21_fu_691_p2;
wire   [0:0] icmp_ln850_21_fu_667_p2;
wire   [15:0] select_ln851_2_fu_697_p3;
wire   [15:0] select_ln850_21_fu_705_p3;
wire   [14:0] trunc_ln473_21_fu_713_p1;
wire   [15:0] add_ln473_21_fu_717_p2;
wire   [0:0] tmp_91_fu_729_p3;
wire   [14:0] add_ln473_42_fu_723_p2;
wire   [14:0] select_ln475_2_fu_737_p3;
wire   [4:0] tmp_92_fu_749_p4;
wire   [0:0] icmp_ln476_21_fu_759_p2;
wire   [9:0] trunc_ln475_21_fu_745_p1;
wire   [14:0] tmp_45_fu_781_p4;
wire   [33:0] shl_ln1118_20_fu_773_p3;
wire   [8:0] trunc_ln851_22_fu_801_p1;
wire   [15:0] p_Result_4_3_fu_805_p3;
wire  signed [15:0] sext_ln850_22_fu_791_p1;
wire   [0:0] icmp_ln851_3_fu_813_p2;
wire   [15:0] add_ln700_22_fu_819_p2;
wire   [0:0] icmp_ln850_22_fu_795_p2;
wire   [15:0] select_ln851_3_fu_825_p3;
wire   [15:0] select_ln850_22_fu_833_p3;
wire   [14:0] trunc_ln473_22_fu_841_p1;
wire   [15:0] add_ln473_22_fu_845_p2;
wire   [0:0] tmp_93_fu_857_p3;
wire   [14:0] add_ln473_43_fu_851_p2;
wire   [14:0] select_ln475_3_fu_865_p3;
wire   [4:0] tmp_94_fu_877_p4;
wire   [0:0] icmp_ln476_22_fu_887_p2;
wire   [9:0] trunc_ln475_22_fu_873_p1;
wire   [14:0] tmp_47_fu_909_p4;
wire   [33:0] shl_ln1118_21_fu_901_p3;
wire   [8:0] trunc_ln851_23_fu_929_p1;
wire   [15:0] p_Result_4_4_fu_933_p3;
wire  signed [15:0] sext_ln850_23_fu_919_p1;
wire   [0:0] icmp_ln851_4_fu_941_p2;
wire   [15:0] add_ln700_23_fu_947_p2;
wire   [0:0] icmp_ln850_23_fu_923_p2;
wire   [15:0] select_ln851_4_fu_953_p3;
wire   [15:0] select_ln850_23_fu_961_p3;
wire   [14:0] trunc_ln473_23_fu_969_p1;
wire   [15:0] add_ln473_23_fu_973_p2;
wire   [0:0] tmp_95_fu_985_p3;
wire   [14:0] add_ln473_44_fu_979_p2;
wire   [14:0] select_ln475_4_fu_993_p3;
wire   [4:0] tmp_96_fu_1005_p4;
wire   [0:0] icmp_ln476_23_fu_1015_p2;
wire   [9:0] trunc_ln475_23_fu_1001_p1;
wire   [14:0] tmp_49_fu_1037_p4;
wire   [33:0] shl_ln1118_22_fu_1029_p3;
wire   [8:0] trunc_ln851_24_fu_1057_p1;
wire   [15:0] p_Result_4_5_fu_1061_p3;
wire  signed [15:0] sext_ln850_24_fu_1047_p1;
wire   [0:0] icmp_ln851_5_fu_1069_p2;
wire   [15:0] add_ln700_24_fu_1075_p2;
wire   [0:0] icmp_ln850_24_fu_1051_p2;
wire   [15:0] select_ln851_5_fu_1081_p3;
wire   [15:0] select_ln850_24_fu_1089_p3;
wire   [14:0] trunc_ln473_24_fu_1097_p1;
wire   [15:0] add_ln473_24_fu_1101_p2;
wire   [0:0] tmp_97_fu_1113_p3;
wire   [14:0] add_ln473_45_fu_1107_p2;
wire   [14:0] select_ln475_5_fu_1121_p3;
wire   [4:0] tmp_98_fu_1133_p4;
wire   [0:0] icmp_ln476_24_fu_1143_p2;
wire   [9:0] trunc_ln475_24_fu_1129_p1;
wire   [14:0] tmp_51_fu_1165_p4;
wire   [33:0] shl_ln1118_23_fu_1157_p3;
wire   [8:0] trunc_ln851_25_fu_1185_p1;
wire   [15:0] p_Result_4_6_fu_1189_p3;
wire  signed [15:0] sext_ln850_25_fu_1175_p1;
wire   [0:0] icmp_ln851_6_fu_1197_p2;
wire   [15:0] add_ln700_25_fu_1203_p2;
wire   [0:0] icmp_ln850_25_fu_1179_p2;
wire   [15:0] select_ln851_6_fu_1209_p3;
wire   [15:0] select_ln850_25_fu_1217_p3;
wire   [14:0] trunc_ln473_25_fu_1225_p1;
wire   [15:0] add_ln473_25_fu_1229_p2;
wire   [0:0] tmp_99_fu_1241_p3;
wire   [14:0] add_ln473_46_fu_1235_p2;
wire   [14:0] select_ln475_6_fu_1249_p3;
wire   [4:0] tmp_100_fu_1261_p4;
wire   [0:0] icmp_ln476_25_fu_1271_p2;
wire   [9:0] trunc_ln475_25_fu_1257_p1;
wire   [14:0] tmp_53_fu_1293_p4;
wire   [33:0] shl_ln1118_24_fu_1285_p3;
wire   [8:0] trunc_ln851_26_fu_1313_p1;
wire   [15:0] p_Result_4_7_fu_1317_p3;
wire  signed [15:0] sext_ln850_26_fu_1303_p1;
wire   [0:0] icmp_ln851_7_fu_1325_p2;
wire   [15:0] add_ln700_26_fu_1331_p2;
wire   [0:0] icmp_ln850_26_fu_1307_p2;
wire   [15:0] select_ln851_7_fu_1337_p3;
wire   [15:0] select_ln850_26_fu_1345_p3;
wire   [14:0] trunc_ln473_26_fu_1353_p1;
wire   [15:0] add_ln473_26_fu_1357_p2;
wire   [0:0] tmp_101_fu_1369_p3;
wire   [14:0] add_ln473_47_fu_1363_p2;
wire   [14:0] select_ln475_7_fu_1377_p3;
wire   [4:0] tmp_102_fu_1389_p4;
wire   [0:0] icmp_ln476_26_fu_1399_p2;
wire   [9:0] trunc_ln475_26_fu_1385_p1;
wire   [14:0] tmp_55_fu_1421_p4;
wire   [33:0] shl_ln1118_25_fu_1413_p3;
wire   [8:0] trunc_ln851_27_fu_1441_p1;
wire   [15:0] p_Result_4_8_fu_1445_p3;
wire  signed [15:0] sext_ln850_27_fu_1431_p1;
wire   [0:0] icmp_ln851_8_fu_1453_p2;
wire   [15:0] add_ln700_27_fu_1459_p2;
wire   [0:0] icmp_ln850_27_fu_1435_p2;
wire   [15:0] select_ln851_8_fu_1465_p3;
wire   [15:0] select_ln850_27_fu_1473_p3;
wire   [14:0] trunc_ln473_27_fu_1481_p1;
wire   [15:0] add_ln473_27_fu_1485_p2;
wire   [0:0] tmp_103_fu_1497_p3;
wire   [14:0] add_ln473_48_fu_1491_p2;
wire   [14:0] select_ln475_8_fu_1505_p3;
wire   [4:0] tmp_104_fu_1517_p4;
wire   [0:0] icmp_ln476_27_fu_1527_p2;
wire   [9:0] trunc_ln475_27_fu_1513_p1;
wire   [14:0] tmp_57_fu_1549_p4;
wire   [33:0] shl_ln1118_26_fu_1541_p3;
wire   [8:0] trunc_ln851_28_fu_1569_p1;
wire   [15:0] p_Result_4_9_fu_1573_p3;
wire  signed [15:0] sext_ln850_28_fu_1559_p1;
wire   [0:0] icmp_ln851_9_fu_1581_p2;
wire   [15:0] add_ln700_28_fu_1587_p2;
wire   [0:0] icmp_ln850_28_fu_1563_p2;
wire   [15:0] select_ln851_9_fu_1593_p3;
wire   [15:0] select_ln850_28_fu_1601_p3;
wire   [14:0] trunc_ln473_28_fu_1609_p1;
wire   [15:0] add_ln473_28_fu_1613_p2;
wire   [0:0] tmp_105_fu_1625_p3;
wire   [14:0] add_ln473_49_fu_1619_p2;
wire   [14:0] select_ln475_9_fu_1633_p3;
wire   [4:0] tmp_106_fu_1645_p4;
wire   [0:0] icmp_ln476_28_fu_1655_p2;
wire   [9:0] trunc_ln475_28_fu_1641_p1;
wire   [14:0] tmp_59_fu_1677_p4;
wire   [33:0] shl_ln1118_27_fu_1669_p3;
wire   [8:0] trunc_ln851_29_fu_1697_p1;
wire   [15:0] p_Result_4_s_fu_1701_p3;
wire  signed [15:0] sext_ln850_29_fu_1687_p1;
wire   [0:0] icmp_ln851_10_fu_1709_p2;
wire   [15:0] add_ln700_29_fu_1715_p2;
wire   [0:0] icmp_ln850_29_fu_1691_p2;
wire   [15:0] select_ln851_10_fu_1721_p3;
wire   [15:0] select_ln850_29_fu_1729_p3;
wire   [14:0] trunc_ln473_29_fu_1737_p1;
wire   [15:0] add_ln473_29_fu_1741_p2;
wire   [0:0] tmp_107_fu_1753_p3;
wire   [14:0] add_ln473_50_fu_1747_p2;
wire   [14:0] select_ln475_10_fu_1761_p3;
wire   [4:0] tmp_108_fu_1773_p4;
wire   [0:0] icmp_ln476_29_fu_1783_p2;
wire   [9:0] trunc_ln475_29_fu_1769_p1;
wire   [14:0] tmp_61_fu_1805_p4;
wire   [33:0] shl_ln1118_28_fu_1797_p3;
wire   [8:0] trunc_ln851_30_fu_1825_p1;
wire   [15:0] p_Result_4_10_fu_1829_p3;
wire  signed [15:0] sext_ln850_30_fu_1815_p1;
wire   [0:0] icmp_ln851_11_fu_1837_p2;
wire   [15:0] add_ln700_30_fu_1843_p2;
wire   [0:0] icmp_ln850_30_fu_1819_p2;
wire   [15:0] select_ln851_11_fu_1849_p3;
wire   [15:0] select_ln850_30_fu_1857_p3;
wire   [14:0] trunc_ln473_30_fu_1865_p1;
wire   [15:0] add_ln473_30_fu_1869_p2;
wire   [0:0] tmp_109_fu_1881_p3;
wire   [14:0] add_ln473_51_fu_1875_p2;
wire   [14:0] select_ln475_11_fu_1889_p3;
wire   [4:0] tmp_110_fu_1901_p4;
wire   [0:0] icmp_ln476_30_fu_1911_p2;
wire   [9:0] trunc_ln475_30_fu_1897_p1;
wire   [14:0] tmp_63_fu_1933_p4;
wire   [33:0] shl_ln1118_29_fu_1925_p3;
wire   [8:0] trunc_ln851_31_fu_1953_p1;
wire   [15:0] p_Result_4_11_fu_1957_p3;
wire  signed [15:0] sext_ln850_31_fu_1943_p1;
wire   [0:0] icmp_ln851_12_fu_1965_p2;
wire   [15:0] add_ln700_31_fu_1971_p2;
wire   [0:0] icmp_ln850_31_fu_1947_p2;
wire   [15:0] select_ln851_12_fu_1977_p3;
wire   [15:0] select_ln850_31_fu_1985_p3;
wire   [14:0] trunc_ln473_31_fu_1993_p1;
wire   [15:0] add_ln473_31_fu_1997_p2;
wire   [0:0] tmp_111_fu_2009_p3;
wire   [14:0] add_ln473_52_fu_2003_p2;
wire   [14:0] select_ln475_12_fu_2017_p3;
wire   [4:0] tmp_112_fu_2029_p4;
wire   [0:0] icmp_ln476_31_fu_2039_p2;
wire   [9:0] trunc_ln475_31_fu_2025_p1;
wire   [14:0] tmp_65_fu_2061_p4;
wire   [33:0] shl_ln1118_30_fu_2053_p3;
wire   [8:0] trunc_ln851_32_fu_2081_p1;
wire   [15:0] p_Result_4_12_fu_2085_p3;
wire  signed [15:0] sext_ln850_32_fu_2071_p1;
wire   [0:0] icmp_ln851_13_fu_2093_p2;
wire   [15:0] add_ln700_32_fu_2099_p2;
wire   [0:0] icmp_ln850_32_fu_2075_p2;
wire   [15:0] select_ln851_13_fu_2105_p3;
wire   [15:0] select_ln850_32_fu_2113_p3;
wire   [14:0] trunc_ln473_32_fu_2121_p1;
wire   [15:0] add_ln473_32_fu_2125_p2;
wire   [0:0] tmp_113_fu_2137_p3;
wire   [14:0] add_ln473_53_fu_2131_p2;
wire   [14:0] select_ln475_13_fu_2145_p3;
wire   [4:0] tmp_114_fu_2157_p4;
wire   [0:0] icmp_ln476_32_fu_2167_p2;
wire   [9:0] trunc_ln475_32_fu_2153_p1;
wire   [14:0] tmp_67_fu_2189_p4;
wire   [33:0] shl_ln1118_31_fu_2181_p3;
wire   [8:0] trunc_ln851_33_fu_2209_p1;
wire   [15:0] p_Result_4_13_fu_2213_p3;
wire  signed [15:0] sext_ln850_33_fu_2199_p1;
wire   [0:0] icmp_ln851_14_fu_2221_p2;
wire   [15:0] add_ln700_33_fu_2227_p2;
wire   [0:0] icmp_ln850_33_fu_2203_p2;
wire   [15:0] select_ln851_14_fu_2233_p3;
wire   [15:0] select_ln850_33_fu_2241_p3;
wire   [14:0] trunc_ln473_33_fu_2249_p1;
wire   [15:0] add_ln473_33_fu_2253_p2;
wire   [0:0] tmp_115_fu_2265_p3;
wire   [14:0] add_ln473_54_fu_2259_p2;
wire   [14:0] select_ln475_14_fu_2273_p3;
wire   [4:0] tmp_116_fu_2285_p4;
wire   [0:0] icmp_ln476_33_fu_2295_p2;
wire   [9:0] trunc_ln475_33_fu_2281_p1;
wire   [14:0] tmp_69_fu_2317_p4;
wire   [33:0] shl_ln1118_32_fu_2309_p3;
wire   [8:0] trunc_ln851_34_fu_2337_p1;
wire   [15:0] p_Result_4_14_fu_2341_p3;
wire  signed [15:0] sext_ln850_34_fu_2327_p1;
wire   [0:0] icmp_ln851_15_fu_2349_p2;
wire   [15:0] add_ln700_34_fu_2355_p2;
wire   [0:0] icmp_ln850_34_fu_2331_p2;
wire   [15:0] select_ln851_15_fu_2361_p3;
wire   [15:0] select_ln850_34_fu_2369_p3;
wire   [14:0] trunc_ln473_34_fu_2377_p1;
wire   [15:0] add_ln473_34_fu_2381_p2;
wire   [0:0] tmp_117_fu_2393_p3;
wire   [14:0] add_ln473_55_fu_2387_p2;
wire   [14:0] select_ln475_15_fu_2401_p3;
wire   [4:0] tmp_118_fu_2413_p4;
wire   [0:0] icmp_ln476_34_fu_2423_p2;
wire   [9:0] trunc_ln475_34_fu_2409_p1;
wire   [16:0] tmp_60_fu_2501_p3;
wire   [16:0] tmp_62_fu_2513_p3;
wire   [16:0] tmp_64_fu_2525_p3;
wire   [16:0] tmp_66_fu_2537_p3;
wire   [16:0] tmp_68_fu_2549_p3;
wire   [16:0] tmp_70_fu_2561_p3;
wire   [16:0] tmp_71_fu_2573_p3;
wire   [16:0] tmp_72_fu_2585_p3;
wire   [16:0] tmp_73_fu_2597_p3;
wire   [16:0] tmp_74_fu_2609_p3;
wire   [16:0] tmp_75_fu_2621_p3;
wire   [16:0] tmp_76_fu_2633_p3;
wire   [16:0] tmp_77_fu_2645_p3;
wire   [16:0] tmp_78_fu_2657_p3;
wire   [16:0] tmp_79_fu_2669_p3;
wire   [16:0] tmp_80_fu_2681_p3;
wire  signed [23:0] sext_ln728_fu_2509_p1;
wire  signed [23:0] sext_ln728_20_fu_2521_p1;
wire  signed [23:0] sext_ln728_21_fu_2533_p1;
wire  signed [23:0] sext_ln728_22_fu_2545_p1;
wire  signed [23:0] sext_ln728_23_fu_2557_p1;
wire  signed [23:0] sext_ln728_24_fu_2569_p1;
wire  signed [23:0] sext_ln728_25_fu_2581_p1;
wire  signed [23:0] sext_ln728_26_fu_2593_p1;
wire  signed [23:0] sext_ln728_27_fu_2605_p1;
wire  signed [23:0] sext_ln728_28_fu_2617_p1;
wire  signed [23:0] sext_ln728_29_fu_2629_p1;
wire  signed [23:0] sext_ln728_30_fu_2641_p1;
wire  signed [23:0] sext_ln728_31_fu_2653_p1;
wire  signed [23:0] sext_ln728_32_fu_2665_p1;
wire  signed [23:0] sext_ln728_33_fu_2677_p1;
wire  signed [23:0] sext_ln728_34_fu_2689_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s_tanh_tacud #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tanh_table3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tanh_table3_address0),
    .ce0(tanh_table3_ce0),
    .q0(tanh_table3_q0),
    .address1(tanh_table3_address1),
    .ce1(tanh_table3_ce1),
    .q1(tanh_table3_q1),
    .address2(tanh_table3_address2),
    .ce2(tanh_table3_ce2),
    .q2(tanh_table3_q2),
    .address3(tanh_table3_address3),
    .ce3(tanh_table3_ce3),
    .q3(tanh_table3_q3),
    .address4(tanh_table3_address4),
    .ce4(tanh_table3_ce4),
    .q4(tanh_table3_q4),
    .address5(tanh_table3_address5),
    .ce5(tanh_table3_ce5),
    .q5(tanh_table3_q5),
    .address6(tanh_table3_address6),
    .ce6(tanh_table3_ce6),
    .q6(tanh_table3_q6),
    .address7(tanh_table3_address7),
    .ce7(tanh_table3_ce7),
    .q7(tanh_table3_q7),
    .address8(tanh_table3_address8),
    .ce8(tanh_table3_ce8),
    .q8(tanh_table3_q8),
    .address9(tanh_table3_address9),
    .ce9(tanh_table3_ce9),
    .q9(tanh_table3_q9),
    .address10(tanh_table3_address10),
    .ce10(tanh_table3_ce10),
    .q10(tanh_table3_q10),
    .address11(tanh_table3_address11),
    .ce11(tanh_table3_ce11),
    .q11(tanh_table3_q11),
    .address12(tanh_table3_address12),
    .ce12(tanh_table3_ce12),
    .q12(tanh_table3_q12),
    .address13(tanh_table3_address13),
    .ce13(tanh_table3_ce13),
    .q13(tanh_table3_q13),
    .address14(tanh_table3_address14),
    .ce14(tanh_table3_ce14),
    .q14(tanh_table3_q14),
    .address15(tanh_table3_address15),
    .ce15(tanh_table3_ce15),
    .q15(tanh_table3_q15)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln476_10_reg_2839 <= select_ln476_10_fu_1789_p3;
        select_ln476_11_reg_2844 <= select_ln476_11_fu_1917_p3;
        select_ln476_12_reg_2849 <= select_ln476_12_fu_2045_p3;
        select_ln476_13_reg_2854 <= select_ln476_13_fu_2173_p3;
        select_ln476_14_reg_2859 <= select_ln476_14_fu_2301_p3;
        select_ln476_15_reg_2864 <= select_ln476_15_fu_2429_p3;
        select_ln476_1_reg_2794 <= select_ln476_1_fu_637_p3;
        select_ln476_2_reg_2799 <= select_ln476_2_fu_765_p3;
        select_ln476_3_reg_2804 <= select_ln476_3_fu_893_p3;
        select_ln476_4_reg_2809 <= select_ln476_4_fu_1021_p3;
        select_ln476_5_reg_2814 <= select_ln476_5_fu_1149_p3;
        select_ln476_6_reg_2819 <= select_ln476_6_fu_1277_p3;
        select_ln476_7_reg_2824 <= select_ln476_7_fu_1405_p3;
        select_ln476_8_reg_2829 <= select_ln476_8_fu_1533_p3;
        select_ln476_9_reg_2834 <= select_ln476_9_fu_1661_p3;
        select_ln476_reg_2789 <= select_ln476_fu_509_p3;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce0 = 1'b1;
    end else begin
        tanh_table3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce1 = 1'b1;
    end else begin
        tanh_table3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce10 = 1'b1;
    end else begin
        tanh_table3_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce11 = 1'b1;
    end else begin
        tanh_table3_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce12 = 1'b1;
    end else begin
        tanh_table3_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce13 = 1'b1;
    end else begin
        tanh_table3_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce14 = 1'b1;
    end else begin
        tanh_table3_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce15 = 1'b1;
    end else begin
        tanh_table3_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce2 = 1'b1;
    end else begin
        tanh_table3_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce3 = 1'b1;
    end else begin
        tanh_table3_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce4 = 1'b1;
    end else begin
        tanh_table3_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce5 = 1'b1;
    end else begin
        tanh_table3_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce6 = 1'b1;
    end else begin
        tanh_table3_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce7 = 1'b1;
    end else begin
        tanh_table3_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce8 = 1'b1;
    end else begin
        tanh_table3_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table3_ce9 = 1'b1;
    end else begin
        tanh_table3_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln473_20_fu_589_p2 = (16'd512 + select_ln850_20_fu_577_p3);

assign add_ln473_21_fu_717_p2 = (16'd512 + select_ln850_21_fu_705_p3);

assign add_ln473_22_fu_845_p2 = (16'd512 + select_ln850_22_fu_833_p3);

assign add_ln473_23_fu_973_p2 = (16'd512 + select_ln850_23_fu_961_p3);

assign add_ln473_24_fu_1101_p2 = (16'd512 + select_ln850_24_fu_1089_p3);

assign add_ln473_25_fu_1229_p2 = (16'd512 + select_ln850_25_fu_1217_p3);

assign add_ln473_26_fu_1357_p2 = (16'd512 + select_ln850_26_fu_1345_p3);

assign add_ln473_27_fu_1485_p2 = (16'd512 + select_ln850_27_fu_1473_p3);

assign add_ln473_28_fu_1613_p2 = (16'd512 + select_ln850_28_fu_1601_p3);

assign add_ln473_29_fu_1741_p2 = (16'd512 + select_ln850_29_fu_1729_p3);

assign add_ln473_30_fu_1869_p2 = (16'd512 + select_ln850_30_fu_1857_p3);

assign add_ln473_31_fu_1997_p2 = (16'd512 + select_ln850_31_fu_1985_p3);

assign add_ln473_32_fu_2125_p2 = (16'd512 + select_ln850_32_fu_2113_p3);

assign add_ln473_33_fu_2253_p2 = (16'd512 + select_ln850_33_fu_2241_p3);

assign add_ln473_34_fu_2381_p2 = (16'd512 + select_ln850_34_fu_2369_p3);

assign add_ln473_40_fu_467_p2 = (15'd512 + trunc_ln473_fu_457_p1);

assign add_ln473_41_fu_595_p2 = (15'd512 + trunc_ln473_20_fu_585_p1);

assign add_ln473_42_fu_723_p2 = (15'd512 + trunc_ln473_21_fu_713_p1);

assign add_ln473_43_fu_851_p2 = (15'd512 + trunc_ln473_22_fu_841_p1);

assign add_ln473_44_fu_979_p2 = (15'd512 + trunc_ln473_23_fu_969_p1);

assign add_ln473_45_fu_1107_p2 = (15'd512 + trunc_ln473_24_fu_1097_p1);

assign add_ln473_46_fu_1235_p2 = (15'd512 + trunc_ln473_25_fu_1225_p1);

assign add_ln473_47_fu_1363_p2 = (15'd512 + trunc_ln473_26_fu_1353_p1);

assign add_ln473_48_fu_1491_p2 = (15'd512 + trunc_ln473_27_fu_1481_p1);

assign add_ln473_49_fu_1619_p2 = (15'd512 + trunc_ln473_28_fu_1609_p1);

assign add_ln473_50_fu_1747_p2 = (15'd512 + trunc_ln473_29_fu_1737_p1);

assign add_ln473_51_fu_1875_p2 = (15'd512 + trunc_ln473_30_fu_1865_p1);

assign add_ln473_52_fu_2003_p2 = (15'd512 + trunc_ln473_31_fu_1993_p1);

assign add_ln473_53_fu_2131_p2 = (15'd512 + trunc_ln473_32_fu_2121_p1);

assign add_ln473_54_fu_2259_p2 = (15'd512 + trunc_ln473_33_fu_2249_p1);

assign add_ln473_55_fu_2387_p2 = (15'd512 + trunc_ln473_34_fu_2377_p1);

assign add_ln473_fu_461_p2 = (16'd512 + select_ln850_fu_449_p3);

assign add_ln700_20_fu_563_p2 = ($signed(16'd1) + $signed(sext_ln850_20_fu_535_p1));

assign add_ln700_21_fu_691_p2 = ($signed(16'd1) + $signed(sext_ln850_21_fu_663_p1));

assign add_ln700_22_fu_819_p2 = ($signed(16'd1) + $signed(sext_ln850_22_fu_791_p1));

assign add_ln700_23_fu_947_p2 = ($signed(16'd1) + $signed(sext_ln850_23_fu_919_p1));

assign add_ln700_24_fu_1075_p2 = ($signed(16'd1) + $signed(sext_ln850_24_fu_1047_p1));

assign add_ln700_25_fu_1203_p2 = ($signed(16'd1) + $signed(sext_ln850_25_fu_1175_p1));

assign add_ln700_26_fu_1331_p2 = ($signed(16'd1) + $signed(sext_ln850_26_fu_1303_p1));

assign add_ln700_27_fu_1459_p2 = ($signed(16'd1) + $signed(sext_ln850_27_fu_1431_p1));

assign add_ln700_28_fu_1587_p2 = ($signed(16'd1) + $signed(sext_ln850_28_fu_1559_p1));

assign add_ln700_29_fu_1715_p2 = ($signed(16'd1) + $signed(sext_ln850_29_fu_1687_p1));

assign add_ln700_30_fu_1843_p2 = ($signed(16'd1) + $signed(sext_ln850_30_fu_1815_p1));

assign add_ln700_31_fu_1971_p2 = ($signed(16'd1) + $signed(sext_ln850_31_fu_1943_p1));

assign add_ln700_32_fu_2099_p2 = ($signed(16'd1) + $signed(sext_ln850_32_fu_2071_p1));

assign add_ln700_33_fu_2227_p2 = ($signed(16'd1) + $signed(sext_ln850_33_fu_2199_p1));

assign add_ln700_34_fu_2355_p2 = ($signed(16'd1) + $signed(sext_ln850_34_fu_2327_p1));

assign add_ln700_fu_435_p2 = ($signed(16'd1) + $signed(sext_ln850_fu_407_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln728_fu_2509_p1;

assign ap_return_1 = sext_ln728_20_fu_2521_p1;

assign ap_return_10 = sext_ln728_29_fu_2629_p1;

assign ap_return_11 = sext_ln728_30_fu_2641_p1;

assign ap_return_12 = sext_ln728_31_fu_2653_p1;

assign ap_return_13 = sext_ln728_32_fu_2665_p1;

assign ap_return_14 = sext_ln728_33_fu_2677_p1;

assign ap_return_15 = sext_ln728_34_fu_2689_p1;

assign ap_return_2 = sext_ln728_21_fu_2533_p1;

assign ap_return_3 = sext_ln728_22_fu_2545_p1;

assign ap_return_4 = sext_ln728_23_fu_2557_p1;

assign ap_return_5 = sext_ln728_24_fu_2569_p1;

assign ap_return_6 = sext_ln728_25_fu_2581_p1;

assign ap_return_7 = sext_ln728_26_fu_2593_p1;

assign ap_return_8 = sext_ln728_27_fu_2605_p1;

assign ap_return_9 = sext_ln728_28_fu_2617_p1;

assign icmp_ln476_20_fu_631_p2 = ((tmp_90_fu_621_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_21_fu_759_p2 = ((tmp_92_fu_749_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_22_fu_887_p2 = ((tmp_94_fu_877_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_23_fu_1015_p2 = ((tmp_96_fu_1005_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_24_fu_1143_p2 = ((tmp_98_fu_1133_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_25_fu_1271_p2 = ((tmp_100_fu_1261_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_26_fu_1399_p2 = ((tmp_102_fu_1389_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_27_fu_1527_p2 = ((tmp_104_fu_1517_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_28_fu_1655_p2 = ((tmp_106_fu_1645_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_29_fu_1783_p2 = ((tmp_108_fu_1773_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_30_fu_1911_p2 = ((tmp_110_fu_1901_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_31_fu_2039_p2 = ((tmp_112_fu_2029_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_32_fu_2167_p2 = ((tmp_114_fu_2157_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_33_fu_2295_p2 = ((tmp_116_fu_2285_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_34_fu_2423_p2 = ((tmp_118_fu_2413_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_fu_503_p2 = ((tmp_88_fu_493_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln850_20_fu_539_p2 = (($signed(shl_ln1118_s_fu_517_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_21_fu_667_p2 = (($signed(shl_ln1118_19_fu_645_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_22_fu_795_p2 = (($signed(shl_ln1118_20_fu_773_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_23_fu_923_p2 = (($signed(shl_ln1118_21_fu_901_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_24_fu_1051_p2 = (($signed(shl_ln1118_22_fu_1029_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_25_fu_1179_p2 = (($signed(shl_ln1118_23_fu_1157_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_26_fu_1307_p2 = (($signed(shl_ln1118_24_fu_1285_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_27_fu_1435_p2 = (($signed(shl_ln1118_25_fu_1413_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_28_fu_1563_p2 = (($signed(shl_ln1118_26_fu_1541_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_29_fu_1691_p2 = (($signed(shl_ln1118_27_fu_1669_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_30_fu_1819_p2 = (($signed(shl_ln1118_28_fu_1797_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_31_fu_1947_p2 = (($signed(shl_ln1118_29_fu_1925_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_32_fu_2075_p2 = (($signed(shl_ln1118_30_fu_2053_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_33_fu_2203_p2 = (($signed(shl_ln1118_31_fu_2181_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_34_fu_2331_p2 = (($signed(shl_ln1118_32_fu_2309_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_fu_411_p2 = (($signed(shl_ln_fu_389_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln851_10_fu_1709_p2 = ((p_Result_4_s_fu_1701_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_11_fu_1837_p2 = ((p_Result_4_10_fu_1829_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_12_fu_1965_p2 = ((p_Result_4_11_fu_1957_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_13_fu_2093_p2 = ((p_Result_4_12_fu_2085_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_14_fu_2221_p2 = ((p_Result_4_13_fu_2213_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_15_fu_2349_p2 = ((p_Result_4_14_fu_2341_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_1_fu_557_p2 = ((p_Result_4_1_fu_549_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_2_fu_685_p2 = ((p_Result_4_2_fu_677_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_3_fu_813_p2 = ((p_Result_4_3_fu_805_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_4_fu_941_p2 = ((p_Result_4_4_fu_933_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_5_fu_1069_p2 = ((p_Result_4_5_fu_1061_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_6_fu_1197_p2 = ((p_Result_4_6_fu_1189_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_7_fu_1325_p2 = ((p_Result_4_7_fu_1317_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_8_fu_1453_p2 = ((p_Result_4_8_fu_1445_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_9_fu_1581_p2 = ((p_Result_4_9_fu_1573_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_fu_429_p2 = ((p_Result_4_fu_421_p3 == 16'd0) ? 1'b1 : 1'b0);

assign p_Result_4_10_fu_1829_p3 = {{trunc_ln851_30_fu_1825_p1}, {7'd0}};

assign p_Result_4_11_fu_1957_p3 = {{trunc_ln851_31_fu_1953_p1}, {7'd0}};

assign p_Result_4_12_fu_2085_p3 = {{trunc_ln851_32_fu_2081_p1}, {7'd0}};

assign p_Result_4_13_fu_2213_p3 = {{trunc_ln851_33_fu_2209_p1}, {7'd0}};

assign p_Result_4_14_fu_2341_p3 = {{trunc_ln851_34_fu_2337_p1}, {7'd0}};

assign p_Result_4_1_fu_549_p3 = {{trunc_ln851_20_fu_545_p1}, {7'd0}};

assign p_Result_4_2_fu_677_p3 = {{trunc_ln851_21_fu_673_p1}, {7'd0}};

assign p_Result_4_3_fu_805_p3 = {{trunc_ln851_22_fu_801_p1}, {7'd0}};

assign p_Result_4_4_fu_933_p3 = {{trunc_ln851_23_fu_929_p1}, {7'd0}};

assign p_Result_4_5_fu_1061_p3 = {{trunc_ln851_24_fu_1057_p1}, {7'd0}};

assign p_Result_4_6_fu_1189_p3 = {{trunc_ln851_25_fu_1185_p1}, {7'd0}};

assign p_Result_4_7_fu_1317_p3 = {{trunc_ln851_26_fu_1313_p1}, {7'd0}};

assign p_Result_4_8_fu_1445_p3 = {{trunc_ln851_27_fu_1441_p1}, {7'd0}};

assign p_Result_4_9_fu_1573_p3 = {{trunc_ln851_28_fu_1569_p1}, {7'd0}};

assign p_Result_4_fu_421_p3 = {{trunc_ln851_fu_417_p1}, {7'd0}};

assign p_Result_4_s_fu_1701_p3 = {{trunc_ln851_29_fu_1697_p1}, {7'd0}};

assign select_ln475_10_fu_1761_p3 = ((tmp_107_fu_1753_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_50_fu_1747_p2);

assign select_ln475_11_fu_1889_p3 = ((tmp_109_fu_1881_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_51_fu_1875_p2);

assign select_ln475_12_fu_2017_p3 = ((tmp_111_fu_2009_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_52_fu_2003_p2);

assign select_ln475_13_fu_2145_p3 = ((tmp_113_fu_2137_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_53_fu_2131_p2);

assign select_ln475_14_fu_2273_p3 = ((tmp_115_fu_2265_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_54_fu_2259_p2);

assign select_ln475_15_fu_2401_p3 = ((tmp_117_fu_2393_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_55_fu_2387_p2);

assign select_ln475_1_fu_609_p3 = ((tmp_89_fu_601_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_41_fu_595_p2);

assign select_ln475_2_fu_737_p3 = ((tmp_91_fu_729_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_42_fu_723_p2);

assign select_ln475_3_fu_865_p3 = ((tmp_93_fu_857_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_43_fu_851_p2);

assign select_ln475_4_fu_993_p3 = ((tmp_95_fu_985_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_44_fu_979_p2);

assign select_ln475_5_fu_1121_p3 = ((tmp_97_fu_1113_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_45_fu_1107_p2);

assign select_ln475_6_fu_1249_p3 = ((tmp_99_fu_1241_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_46_fu_1235_p2);

assign select_ln475_7_fu_1377_p3 = ((tmp_101_fu_1369_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_47_fu_1363_p2);

assign select_ln475_8_fu_1505_p3 = ((tmp_103_fu_1497_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_48_fu_1491_p2);

assign select_ln475_9_fu_1633_p3 = ((tmp_105_fu_1625_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_49_fu_1619_p2);

assign select_ln475_fu_481_p3 = ((tmp_87_fu_473_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_40_fu_467_p2);

assign select_ln476_10_fu_1789_p3 = ((icmp_ln476_29_fu_1783_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_29_fu_1769_p1);

assign select_ln476_11_fu_1917_p3 = ((icmp_ln476_30_fu_1911_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_30_fu_1897_p1);

assign select_ln476_12_fu_2045_p3 = ((icmp_ln476_31_fu_2039_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_31_fu_2025_p1);

assign select_ln476_13_fu_2173_p3 = ((icmp_ln476_32_fu_2167_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_32_fu_2153_p1);

assign select_ln476_14_fu_2301_p3 = ((icmp_ln476_33_fu_2295_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_33_fu_2281_p1);

assign select_ln476_15_fu_2429_p3 = ((icmp_ln476_34_fu_2423_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_34_fu_2409_p1);

assign select_ln476_1_fu_637_p3 = ((icmp_ln476_20_fu_631_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_20_fu_617_p1);

assign select_ln476_2_fu_765_p3 = ((icmp_ln476_21_fu_759_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_21_fu_745_p1);

assign select_ln476_3_fu_893_p3 = ((icmp_ln476_22_fu_887_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_22_fu_873_p1);

assign select_ln476_4_fu_1021_p3 = ((icmp_ln476_23_fu_1015_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_23_fu_1001_p1);

assign select_ln476_5_fu_1149_p3 = ((icmp_ln476_24_fu_1143_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_24_fu_1129_p1);

assign select_ln476_6_fu_1277_p3 = ((icmp_ln476_25_fu_1271_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_25_fu_1257_p1);

assign select_ln476_7_fu_1405_p3 = ((icmp_ln476_26_fu_1399_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_26_fu_1385_p1);

assign select_ln476_8_fu_1533_p3 = ((icmp_ln476_27_fu_1527_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_27_fu_1513_p1);

assign select_ln476_9_fu_1661_p3 = ((icmp_ln476_28_fu_1655_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_28_fu_1641_p1);

assign select_ln476_fu_509_p3 = ((icmp_ln476_fu_503_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_fu_489_p1);

assign select_ln850_20_fu_577_p3 = ((icmp_ln850_20_fu_539_p2[0:0] === 1'b1) ? select_ln851_1_fu_569_p3 : sext_ln850_20_fu_535_p1);

assign select_ln850_21_fu_705_p3 = ((icmp_ln850_21_fu_667_p2[0:0] === 1'b1) ? select_ln851_2_fu_697_p3 : sext_ln850_21_fu_663_p1);

assign select_ln850_22_fu_833_p3 = ((icmp_ln850_22_fu_795_p2[0:0] === 1'b1) ? select_ln851_3_fu_825_p3 : sext_ln850_22_fu_791_p1);

assign select_ln850_23_fu_961_p3 = ((icmp_ln850_23_fu_923_p2[0:0] === 1'b1) ? select_ln851_4_fu_953_p3 : sext_ln850_23_fu_919_p1);

assign select_ln850_24_fu_1089_p3 = ((icmp_ln850_24_fu_1051_p2[0:0] === 1'b1) ? select_ln851_5_fu_1081_p3 : sext_ln850_24_fu_1047_p1);

assign select_ln850_25_fu_1217_p3 = ((icmp_ln850_25_fu_1179_p2[0:0] === 1'b1) ? select_ln851_6_fu_1209_p3 : sext_ln850_25_fu_1175_p1);

assign select_ln850_26_fu_1345_p3 = ((icmp_ln850_26_fu_1307_p2[0:0] === 1'b1) ? select_ln851_7_fu_1337_p3 : sext_ln850_26_fu_1303_p1);

assign select_ln850_27_fu_1473_p3 = ((icmp_ln850_27_fu_1435_p2[0:0] === 1'b1) ? select_ln851_8_fu_1465_p3 : sext_ln850_27_fu_1431_p1);

assign select_ln850_28_fu_1601_p3 = ((icmp_ln850_28_fu_1563_p2[0:0] === 1'b1) ? select_ln851_9_fu_1593_p3 : sext_ln850_28_fu_1559_p1);

assign select_ln850_29_fu_1729_p3 = ((icmp_ln850_29_fu_1691_p2[0:0] === 1'b1) ? select_ln851_10_fu_1721_p3 : sext_ln850_29_fu_1687_p1);

assign select_ln850_30_fu_1857_p3 = ((icmp_ln850_30_fu_1819_p2[0:0] === 1'b1) ? select_ln851_11_fu_1849_p3 : sext_ln850_30_fu_1815_p1);

assign select_ln850_31_fu_1985_p3 = ((icmp_ln850_31_fu_1947_p2[0:0] === 1'b1) ? select_ln851_12_fu_1977_p3 : sext_ln850_31_fu_1943_p1);

assign select_ln850_32_fu_2113_p3 = ((icmp_ln850_32_fu_2075_p2[0:0] === 1'b1) ? select_ln851_13_fu_2105_p3 : sext_ln850_32_fu_2071_p1);

assign select_ln850_33_fu_2241_p3 = ((icmp_ln850_33_fu_2203_p2[0:0] === 1'b1) ? select_ln851_14_fu_2233_p3 : sext_ln850_33_fu_2199_p1);

assign select_ln850_34_fu_2369_p3 = ((icmp_ln850_34_fu_2331_p2[0:0] === 1'b1) ? select_ln851_15_fu_2361_p3 : sext_ln850_34_fu_2327_p1);

assign select_ln850_fu_449_p3 = ((icmp_ln850_fu_411_p2[0:0] === 1'b1) ? select_ln851_fu_441_p3 : sext_ln850_fu_407_p1);

assign select_ln851_10_fu_1721_p3 = ((icmp_ln851_10_fu_1709_p2[0:0] === 1'b1) ? sext_ln850_29_fu_1687_p1 : add_ln700_29_fu_1715_p2);

assign select_ln851_11_fu_1849_p3 = ((icmp_ln851_11_fu_1837_p2[0:0] === 1'b1) ? sext_ln850_30_fu_1815_p1 : add_ln700_30_fu_1843_p2);

assign select_ln851_12_fu_1977_p3 = ((icmp_ln851_12_fu_1965_p2[0:0] === 1'b1) ? sext_ln850_31_fu_1943_p1 : add_ln700_31_fu_1971_p2);

assign select_ln851_13_fu_2105_p3 = ((icmp_ln851_13_fu_2093_p2[0:0] === 1'b1) ? sext_ln850_32_fu_2071_p1 : add_ln700_32_fu_2099_p2);

assign select_ln851_14_fu_2233_p3 = ((icmp_ln851_14_fu_2221_p2[0:0] === 1'b1) ? sext_ln850_33_fu_2199_p1 : add_ln700_33_fu_2227_p2);

assign select_ln851_15_fu_2361_p3 = ((icmp_ln851_15_fu_2349_p2[0:0] === 1'b1) ? sext_ln850_34_fu_2327_p1 : add_ln700_34_fu_2355_p2);

assign select_ln851_1_fu_569_p3 = ((icmp_ln851_1_fu_557_p2[0:0] === 1'b1) ? sext_ln850_20_fu_535_p1 : add_ln700_20_fu_563_p2);

assign select_ln851_2_fu_697_p3 = ((icmp_ln851_2_fu_685_p2[0:0] === 1'b1) ? sext_ln850_21_fu_663_p1 : add_ln700_21_fu_691_p2);

assign select_ln851_3_fu_825_p3 = ((icmp_ln851_3_fu_813_p2[0:0] === 1'b1) ? sext_ln850_22_fu_791_p1 : add_ln700_22_fu_819_p2);

assign select_ln851_4_fu_953_p3 = ((icmp_ln851_4_fu_941_p2[0:0] === 1'b1) ? sext_ln850_23_fu_919_p1 : add_ln700_23_fu_947_p2);

assign select_ln851_5_fu_1081_p3 = ((icmp_ln851_5_fu_1069_p2[0:0] === 1'b1) ? sext_ln850_24_fu_1047_p1 : add_ln700_24_fu_1075_p2);

assign select_ln851_6_fu_1209_p3 = ((icmp_ln851_6_fu_1197_p2[0:0] === 1'b1) ? sext_ln850_25_fu_1175_p1 : add_ln700_25_fu_1203_p2);

assign select_ln851_7_fu_1337_p3 = ((icmp_ln851_7_fu_1325_p2[0:0] === 1'b1) ? sext_ln850_26_fu_1303_p1 : add_ln700_26_fu_1331_p2);

assign select_ln851_8_fu_1465_p3 = ((icmp_ln851_8_fu_1453_p2[0:0] === 1'b1) ? sext_ln850_27_fu_1431_p1 : add_ln700_27_fu_1459_p2);

assign select_ln851_9_fu_1593_p3 = ((icmp_ln851_9_fu_1581_p2[0:0] === 1'b1) ? sext_ln850_28_fu_1559_p1 : add_ln700_28_fu_1587_p2);

assign select_ln851_fu_441_p3 = ((icmp_ln851_fu_429_p2[0:0] === 1'b1) ? sext_ln850_fu_407_p1 : add_ln700_fu_435_p2);

assign sext_ln728_20_fu_2521_p1 = $signed(tmp_62_fu_2513_p3);

assign sext_ln728_21_fu_2533_p1 = $signed(tmp_64_fu_2525_p3);

assign sext_ln728_22_fu_2545_p1 = $signed(tmp_66_fu_2537_p3);

assign sext_ln728_23_fu_2557_p1 = $signed(tmp_68_fu_2549_p3);

assign sext_ln728_24_fu_2569_p1 = $signed(tmp_70_fu_2561_p3);

assign sext_ln728_25_fu_2581_p1 = $signed(tmp_71_fu_2573_p3);

assign sext_ln728_26_fu_2593_p1 = $signed(tmp_72_fu_2585_p3);

assign sext_ln728_27_fu_2605_p1 = $signed(tmp_73_fu_2597_p3);

assign sext_ln728_28_fu_2617_p1 = $signed(tmp_74_fu_2609_p3);

assign sext_ln728_29_fu_2629_p1 = $signed(tmp_75_fu_2621_p3);

assign sext_ln728_30_fu_2641_p1 = $signed(tmp_76_fu_2633_p3);

assign sext_ln728_31_fu_2653_p1 = $signed(tmp_77_fu_2645_p3);

assign sext_ln728_32_fu_2665_p1 = $signed(tmp_78_fu_2657_p3);

assign sext_ln728_33_fu_2677_p1 = $signed(tmp_79_fu_2669_p3);

assign sext_ln728_34_fu_2689_p1 = $signed(tmp_80_fu_2681_p3);

assign sext_ln728_fu_2509_p1 = $signed(tmp_60_fu_2501_p3);

assign sext_ln850_20_fu_535_p1 = $signed(tmp_41_fu_525_p4);

assign sext_ln850_21_fu_663_p1 = $signed(tmp_43_fu_653_p4);

assign sext_ln850_22_fu_791_p1 = $signed(tmp_45_fu_781_p4);

assign sext_ln850_23_fu_919_p1 = $signed(tmp_47_fu_909_p4);

assign sext_ln850_24_fu_1047_p1 = $signed(tmp_49_fu_1037_p4);

assign sext_ln850_25_fu_1175_p1 = $signed(tmp_51_fu_1165_p4);

assign sext_ln850_26_fu_1303_p1 = $signed(tmp_53_fu_1293_p4);

assign sext_ln850_27_fu_1431_p1 = $signed(tmp_55_fu_1421_p4);

assign sext_ln850_28_fu_1559_p1 = $signed(tmp_57_fu_1549_p4);

assign sext_ln850_29_fu_1687_p1 = $signed(tmp_59_fu_1677_p4);

assign sext_ln850_30_fu_1815_p1 = $signed(tmp_61_fu_1805_p4);

assign sext_ln850_31_fu_1943_p1 = $signed(tmp_63_fu_1933_p4);

assign sext_ln850_32_fu_2071_p1 = $signed(tmp_65_fu_2061_p4);

assign sext_ln850_33_fu_2199_p1 = $signed(tmp_67_fu_2189_p4);

assign sext_ln850_34_fu_2327_p1 = $signed(tmp_69_fu_2317_p4);

assign sext_ln850_fu_407_p1 = $signed(tmp_s_fu_397_p4);

assign shl_ln1118_19_fu_645_p3 = {{data_2_V_read}, {10'd0}};

assign shl_ln1118_20_fu_773_p3 = {{data_3_V_read}, {10'd0}};

assign shl_ln1118_21_fu_901_p3 = {{data_4_V_read}, {10'd0}};

assign shl_ln1118_22_fu_1029_p3 = {{data_5_V_read}, {10'd0}};

assign shl_ln1118_23_fu_1157_p3 = {{data_6_V_read}, {10'd0}};

assign shl_ln1118_24_fu_1285_p3 = {{data_7_V_read}, {10'd0}};

assign shl_ln1118_25_fu_1413_p3 = {{data_8_V_read}, {10'd0}};

assign shl_ln1118_26_fu_1541_p3 = {{data_9_V_read}, {10'd0}};

assign shl_ln1118_27_fu_1669_p3 = {{data_10_V_read}, {10'd0}};

assign shl_ln1118_28_fu_1797_p3 = {{data_11_V_read}, {10'd0}};

assign shl_ln1118_29_fu_1925_p3 = {{data_12_V_read}, {10'd0}};

assign shl_ln1118_30_fu_2053_p3 = {{data_13_V_read}, {10'd0}};

assign shl_ln1118_31_fu_2181_p3 = {{data_14_V_read}, {10'd0}};

assign shl_ln1118_32_fu_2309_p3 = {{data_15_V_read}, {10'd0}};

assign shl_ln1118_s_fu_517_p3 = {{data_1_V_read}, {10'd0}};

assign shl_ln_fu_389_p3 = {{data_0_V_read}, {10'd0}};

assign tanh_table3_address0 = zext_ln477_fu_2437_p1;

assign tanh_table3_address1 = zext_ln477_20_fu_2441_p1;

assign tanh_table3_address10 = zext_ln477_29_fu_2477_p1;

assign tanh_table3_address11 = zext_ln477_30_fu_2481_p1;

assign tanh_table3_address12 = zext_ln477_31_fu_2485_p1;

assign tanh_table3_address13 = zext_ln477_32_fu_2489_p1;

assign tanh_table3_address14 = zext_ln477_33_fu_2493_p1;

assign tanh_table3_address15 = zext_ln477_34_fu_2497_p1;

assign tanh_table3_address2 = zext_ln477_21_fu_2445_p1;

assign tanh_table3_address3 = zext_ln477_22_fu_2449_p1;

assign tanh_table3_address4 = zext_ln477_23_fu_2453_p1;

assign tanh_table3_address5 = zext_ln477_24_fu_2457_p1;

assign tanh_table3_address6 = zext_ln477_25_fu_2461_p1;

assign tanh_table3_address7 = zext_ln477_26_fu_2465_p1;

assign tanh_table3_address8 = zext_ln477_27_fu_2469_p1;

assign tanh_table3_address9 = zext_ln477_28_fu_2473_p1;

assign tmp_100_fu_1261_p4 = {{select_ln475_6_fu_1249_p3[14:10]}};

assign tmp_101_fu_1369_p3 = add_ln473_26_fu_1357_p2[32'd15];

assign tmp_102_fu_1389_p4 = {{select_ln475_7_fu_1377_p3[14:10]}};

assign tmp_103_fu_1497_p3 = add_ln473_27_fu_1485_p2[32'd15];

assign tmp_104_fu_1517_p4 = {{select_ln475_8_fu_1505_p3[14:10]}};

assign tmp_105_fu_1625_p3 = add_ln473_28_fu_1613_p2[32'd15];

assign tmp_106_fu_1645_p4 = {{select_ln475_9_fu_1633_p3[14:10]}};

assign tmp_107_fu_1753_p3 = add_ln473_29_fu_1741_p2[32'd15];

assign tmp_108_fu_1773_p4 = {{select_ln475_10_fu_1761_p3[14:10]}};

assign tmp_109_fu_1881_p3 = add_ln473_30_fu_1869_p2[32'd15];

assign tmp_110_fu_1901_p4 = {{select_ln475_11_fu_1889_p3[14:10]}};

assign tmp_111_fu_2009_p3 = add_ln473_31_fu_1997_p2[32'd15];

assign tmp_112_fu_2029_p4 = {{select_ln475_12_fu_2017_p3[14:10]}};

assign tmp_113_fu_2137_p3 = add_ln473_32_fu_2125_p2[32'd15];

assign tmp_114_fu_2157_p4 = {{select_ln475_13_fu_2145_p3[14:10]}};

assign tmp_115_fu_2265_p3 = add_ln473_33_fu_2253_p2[32'd15];

assign tmp_116_fu_2285_p4 = {{select_ln475_14_fu_2273_p3[14:10]}};

assign tmp_117_fu_2393_p3 = add_ln473_34_fu_2381_p2[32'd15];

assign tmp_118_fu_2413_p4 = {{select_ln475_15_fu_2401_p3[14:10]}};

assign tmp_41_fu_525_p4 = {{data_1_V_read[23:9]}};

assign tmp_43_fu_653_p4 = {{data_2_V_read[23:9]}};

assign tmp_45_fu_781_p4 = {{data_3_V_read[23:9]}};

assign tmp_47_fu_909_p4 = {{data_4_V_read[23:9]}};

assign tmp_49_fu_1037_p4 = {{data_5_V_read[23:9]}};

assign tmp_51_fu_1165_p4 = {{data_6_V_read[23:9]}};

assign tmp_53_fu_1293_p4 = {{data_7_V_read[23:9]}};

assign tmp_55_fu_1421_p4 = {{data_8_V_read[23:9]}};

assign tmp_57_fu_1549_p4 = {{data_9_V_read[23:9]}};

assign tmp_59_fu_1677_p4 = {{data_10_V_read[23:9]}};

assign tmp_60_fu_2501_p3 = {{tanh_table3_q0}, {6'd0}};

assign tmp_61_fu_1805_p4 = {{data_11_V_read[23:9]}};

assign tmp_62_fu_2513_p3 = {{tanh_table3_q1}, {6'd0}};

assign tmp_63_fu_1933_p4 = {{data_12_V_read[23:9]}};

assign tmp_64_fu_2525_p3 = {{tanh_table3_q2}, {6'd0}};

assign tmp_65_fu_2061_p4 = {{data_13_V_read[23:9]}};

assign tmp_66_fu_2537_p3 = {{tanh_table3_q3}, {6'd0}};

assign tmp_67_fu_2189_p4 = {{data_14_V_read[23:9]}};

assign tmp_68_fu_2549_p3 = {{tanh_table3_q4}, {6'd0}};

assign tmp_69_fu_2317_p4 = {{data_15_V_read[23:9]}};

assign tmp_70_fu_2561_p3 = {{tanh_table3_q5}, {6'd0}};

assign tmp_71_fu_2573_p3 = {{tanh_table3_q6}, {6'd0}};

assign tmp_72_fu_2585_p3 = {{tanh_table3_q7}, {6'd0}};

assign tmp_73_fu_2597_p3 = {{tanh_table3_q8}, {6'd0}};

assign tmp_74_fu_2609_p3 = {{tanh_table3_q9}, {6'd0}};

assign tmp_75_fu_2621_p3 = {{tanh_table3_q10}, {6'd0}};

assign tmp_76_fu_2633_p3 = {{tanh_table3_q11}, {6'd0}};

assign tmp_77_fu_2645_p3 = {{tanh_table3_q12}, {6'd0}};

assign tmp_78_fu_2657_p3 = {{tanh_table3_q13}, {6'd0}};

assign tmp_79_fu_2669_p3 = {{tanh_table3_q14}, {6'd0}};

assign tmp_80_fu_2681_p3 = {{tanh_table3_q15}, {6'd0}};

assign tmp_87_fu_473_p3 = add_ln473_fu_461_p2[32'd15];

assign tmp_88_fu_493_p4 = {{select_ln475_fu_481_p3[14:10]}};

assign tmp_89_fu_601_p3 = add_ln473_20_fu_589_p2[32'd15];

assign tmp_90_fu_621_p4 = {{select_ln475_1_fu_609_p3[14:10]}};

assign tmp_91_fu_729_p3 = add_ln473_21_fu_717_p2[32'd15];

assign tmp_92_fu_749_p4 = {{select_ln475_2_fu_737_p3[14:10]}};

assign tmp_93_fu_857_p3 = add_ln473_22_fu_845_p2[32'd15];

assign tmp_94_fu_877_p4 = {{select_ln475_3_fu_865_p3[14:10]}};

assign tmp_95_fu_985_p3 = add_ln473_23_fu_973_p2[32'd15];

assign tmp_96_fu_1005_p4 = {{select_ln475_4_fu_993_p3[14:10]}};

assign tmp_97_fu_1113_p3 = add_ln473_24_fu_1101_p2[32'd15];

assign tmp_98_fu_1133_p4 = {{select_ln475_5_fu_1121_p3[14:10]}};

assign tmp_99_fu_1241_p3 = add_ln473_25_fu_1229_p2[32'd15];

assign tmp_s_fu_397_p4 = {{data_0_V_read[23:9]}};

assign trunc_ln473_20_fu_585_p1 = select_ln850_20_fu_577_p3[14:0];

assign trunc_ln473_21_fu_713_p1 = select_ln850_21_fu_705_p3[14:0];

assign trunc_ln473_22_fu_841_p1 = select_ln850_22_fu_833_p3[14:0];

assign trunc_ln473_23_fu_969_p1 = select_ln850_23_fu_961_p3[14:0];

assign trunc_ln473_24_fu_1097_p1 = select_ln850_24_fu_1089_p3[14:0];

assign trunc_ln473_25_fu_1225_p1 = select_ln850_25_fu_1217_p3[14:0];

assign trunc_ln473_26_fu_1353_p1 = select_ln850_26_fu_1345_p3[14:0];

assign trunc_ln473_27_fu_1481_p1 = select_ln850_27_fu_1473_p3[14:0];

assign trunc_ln473_28_fu_1609_p1 = select_ln850_28_fu_1601_p3[14:0];

assign trunc_ln473_29_fu_1737_p1 = select_ln850_29_fu_1729_p3[14:0];

assign trunc_ln473_30_fu_1865_p1 = select_ln850_30_fu_1857_p3[14:0];

assign trunc_ln473_31_fu_1993_p1 = select_ln850_31_fu_1985_p3[14:0];

assign trunc_ln473_32_fu_2121_p1 = select_ln850_32_fu_2113_p3[14:0];

assign trunc_ln473_33_fu_2249_p1 = select_ln850_33_fu_2241_p3[14:0];

assign trunc_ln473_34_fu_2377_p1 = select_ln850_34_fu_2369_p3[14:0];

assign trunc_ln473_fu_457_p1 = select_ln850_fu_449_p3[14:0];

assign trunc_ln475_20_fu_617_p1 = select_ln475_1_fu_609_p3[9:0];

assign trunc_ln475_21_fu_745_p1 = select_ln475_2_fu_737_p3[9:0];

assign trunc_ln475_22_fu_873_p1 = select_ln475_3_fu_865_p3[9:0];

assign trunc_ln475_23_fu_1001_p1 = select_ln475_4_fu_993_p3[9:0];

assign trunc_ln475_24_fu_1129_p1 = select_ln475_5_fu_1121_p3[9:0];

assign trunc_ln475_25_fu_1257_p1 = select_ln475_6_fu_1249_p3[9:0];

assign trunc_ln475_26_fu_1385_p1 = select_ln475_7_fu_1377_p3[9:0];

assign trunc_ln475_27_fu_1513_p1 = select_ln475_8_fu_1505_p3[9:0];

assign trunc_ln475_28_fu_1641_p1 = select_ln475_9_fu_1633_p3[9:0];

assign trunc_ln475_29_fu_1769_p1 = select_ln475_10_fu_1761_p3[9:0];

assign trunc_ln475_30_fu_1897_p1 = select_ln475_11_fu_1889_p3[9:0];

assign trunc_ln475_31_fu_2025_p1 = select_ln475_12_fu_2017_p3[9:0];

assign trunc_ln475_32_fu_2153_p1 = select_ln475_13_fu_2145_p3[9:0];

assign trunc_ln475_33_fu_2281_p1 = select_ln475_14_fu_2273_p3[9:0];

assign trunc_ln475_34_fu_2409_p1 = select_ln475_15_fu_2401_p3[9:0];

assign trunc_ln475_fu_489_p1 = select_ln475_fu_481_p3[9:0];

assign trunc_ln851_20_fu_545_p1 = data_1_V_read[8:0];

assign trunc_ln851_21_fu_673_p1 = data_2_V_read[8:0];

assign trunc_ln851_22_fu_801_p1 = data_3_V_read[8:0];

assign trunc_ln851_23_fu_929_p1 = data_4_V_read[8:0];

assign trunc_ln851_24_fu_1057_p1 = data_5_V_read[8:0];

assign trunc_ln851_25_fu_1185_p1 = data_6_V_read[8:0];

assign trunc_ln851_26_fu_1313_p1 = data_7_V_read[8:0];

assign trunc_ln851_27_fu_1441_p1 = data_8_V_read[8:0];

assign trunc_ln851_28_fu_1569_p1 = data_9_V_read[8:0];

assign trunc_ln851_29_fu_1697_p1 = data_10_V_read[8:0];

assign trunc_ln851_30_fu_1825_p1 = data_11_V_read[8:0];

assign trunc_ln851_31_fu_1953_p1 = data_12_V_read[8:0];

assign trunc_ln851_32_fu_2081_p1 = data_13_V_read[8:0];

assign trunc_ln851_33_fu_2209_p1 = data_14_V_read[8:0];

assign trunc_ln851_34_fu_2337_p1 = data_15_V_read[8:0];

assign trunc_ln851_fu_417_p1 = data_0_V_read[8:0];

assign zext_ln477_20_fu_2441_p1 = select_ln476_1_reg_2794;

assign zext_ln477_21_fu_2445_p1 = select_ln476_2_reg_2799;

assign zext_ln477_22_fu_2449_p1 = select_ln476_3_reg_2804;

assign zext_ln477_23_fu_2453_p1 = select_ln476_4_reg_2809;

assign zext_ln477_24_fu_2457_p1 = select_ln476_5_reg_2814;

assign zext_ln477_25_fu_2461_p1 = select_ln476_6_reg_2819;

assign zext_ln477_26_fu_2465_p1 = select_ln476_7_reg_2824;

assign zext_ln477_27_fu_2469_p1 = select_ln476_8_reg_2829;

assign zext_ln477_28_fu_2473_p1 = select_ln476_9_reg_2834;

assign zext_ln477_29_fu_2477_p1 = select_ln476_10_reg_2839;

assign zext_ln477_30_fu_2481_p1 = select_ln476_11_reg_2844;

assign zext_ln477_31_fu_2485_p1 = select_ln476_12_reg_2849;

assign zext_ln477_32_fu_2489_p1 = select_ln476_13_reg_2854;

assign zext_ln477_33_fu_2493_p1 = select_ln476_14_reg_2859;

assign zext_ln477_34_fu_2497_p1 = select_ln476_15_reg_2864;

assign zext_ln477_fu_2437_p1 = select_ln476_reg_2789;

endmodule //tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config10_s
