// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [23:0] data_0_V_read;
input  [23:0] data_1_V_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;

wire   [0:0] icmp_ln1494_fu_46_p2;
wire   [7:0] p_Result_s_fu_52_p4;
wire   [0:0] icmp_ln1494_1_fu_70_p2;
wire   [7:0] p_Result_1_fu_76_p4;
wire   [7:0] select_ln1494_fu_62_p3;
wire   [7:0] select_ln1494_1_fu_86_p3;

assign ap_ready = 1'b1;

assign ap_return_0 = select_ln1494_fu_62_p3;

assign ap_return_1 = select_ln1494_1_fu_86_p3;

assign icmp_ln1494_1_fu_70_p2 = (($signed(data_1_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_46_p2 = (($signed(data_0_V_read) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign p_Result_1_fu_76_p4 = {{data_1_V_read[23:16]}};

assign p_Result_s_fu_52_p4 = {{data_0_V_read[23:16]}};

assign select_ln1494_1_fu_86_p3 = ((icmp_ln1494_1_fu_70_p2[0:0] === 1'b1) ? p_Result_1_fu_76_p4 : 8'd0);

assign select_ln1494_fu_62_p3 = ((icmp_ln1494_fu_46_p2[0:0] === 1'b1) ? p_Result_s_fu_52_p4 : 8'd0);

endmodule //relu_ap_fixed_24_8_5_3_0_ap_uint_8_relu_config12_s
