// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28
);


output   ap_ready;
input  [12:0] data_0_V_read;
input  [12:0] data_1_V_read;
input  [12:0] data_2_V_read;
input  [12:0] data_3_V_read;
input  [12:0] data_4_V_read;
input  [12:0] data_5_V_read;
input  [12:0] data_6_V_read;
input  [12:0] data_7_V_read;
input  [12:0] data_8_V_read;
input  [12:0] data_9_V_read;
input  [12:0] data_10_V_read;
input  [12:0] data_11_V_read;
input  [12:0] data_12_V_read;
input  [12:0] data_13_V_read;
input  [12:0] data_14_V_read;
input  [12:0] data_15_V_read;
input  [12:0] data_16_V_read;
input  [12:0] data_17_V_read;
input  [12:0] data_18_V_read;
input  [12:0] data_19_V_read;
input  [12:0] data_20_V_read;
input  [12:0] data_21_V_read;
input  [12:0] data_22_V_read;
input  [12:0] data_23_V_read;
input  [12:0] data_24_V_read;
input  [12:0] data_25_V_read;
input  [12:0] data_26_V_read;
input  [12:0] data_27_V_read;
input  [12:0] data_28_V_read;
output  [23:0] ap_return_0;
output  [23:0] ap_return_1;
output  [23:0] ap_return_2;
output  [23:0] ap_return_3;
output  [23:0] ap_return_4;
output  [23:0] ap_return_5;
output  [23:0] ap_return_6;
output  [23:0] ap_return_7;
output  [23:0] ap_return_8;
output  [23:0] ap_return_9;
output  [23:0] ap_return_10;
output  [23:0] ap_return_11;
output  [23:0] ap_return_12;
output  [23:0] ap_return_13;
output  [23:0] ap_return_14;
output  [23:0] ap_return_15;
output  [23:0] ap_return_16;
output  [23:0] ap_return_17;
output  [23:0] ap_return_18;
output  [23:0] ap_return_19;
output  [23:0] ap_return_20;
output  [23:0] ap_return_21;
output  [23:0] ap_return_22;
output  [23:0] ap_return_23;
output  [23:0] ap_return_24;
output  [23:0] ap_return_25;
output  [23:0] ap_return_26;
output  [23:0] ap_return_27;
output  [23:0] ap_return_28;

wire   [12:0] mul_ln703_9_fu_374_p0;
wire   [12:0] mul_ln703_8_fu_375_p0;
wire   [12:0] mul_ln703_3_fu_376_p0;
wire   [12:0] mul_ln703_24_fu_378_p0;
wire   [12:0] mul_ln703_5_fu_379_p0;
wire   [12:0] mul_ln703_fu_380_p0;
wire   [12:0] mul_ln703_20_fu_382_p0;
wire   [12:0] mul_ln703_13_fu_383_p0;
wire   [12:0] mul_ln703_12_fu_384_p0;
wire   [12:0] mul_ln703_2_fu_385_p0;
wire   [12:0] mul_ln703_11_fu_386_p0;
wire   [12:0] mul_ln703_7_fu_387_p0;
wire   [12:0] mul_ln703_10_fu_388_p0;
wire   [12:0] mul_ln703_14_fu_389_p0;
wire   [12:0] mul_ln703_22_fu_390_p0;
wire   [12:0] mul_ln703_23_fu_391_p0;
wire   [12:0] mul_ln703_6_fu_392_p0;
wire   [12:0] mul_ln703_1_fu_393_p0;
wire   [12:0] mul_ln703_19_fu_394_p0;
wire   [12:0] mul_ln703_25_fu_395_p0;
wire   [12:0] mul_ln703_16_fu_396_p0;
wire   [12:0] mul_ln703_4_fu_397_p0;
wire   [12:0] mul_ln703_17_fu_399_p0;
wire   [12:0] mul_ln703_21_fu_400_p0;
wire   [12:0] mul_ln703_15_fu_401_p0;
wire   [12:0] mul_ln703_18_fu_402_p0;
wire   [21:0] mul_ln703_fu_380_p2;
wire   [21:0] add_ln703_fu_3607_p2;
wire   [21:0] mul_ln703_1_fu_393_p2;
wire   [21:0] add_ln703_1_fu_3622_p2;
wire   [14:0] shl_ln703_1_fu_3636_p3;
wire   [13:0] zext_ln703_2_fu_3632_p1;
wire   [13:0] add_ln703_2_fu_3648_p2;
wire   [16:0] zext_ln703_3_fu_3644_p1;
wire  signed [16:0] sext_ln703_2_fu_3654_p1;
wire   [16:0] add_ln703_3_fu_3658_p2;
wire   [22:0] mul_ln703_2_fu_385_p2;
wire   [22:0] add_ln703_4_fu_3673_p2;
wire   [14:0] shl_ln703_2_fu_3687_p3;
wire   [15:0] zext_ln703_5_fu_3683_p1;
wire   [15:0] zext_ln703_14_fu_3695_p1;
wire   [15:0] add_ln703_5_fu_3699_p2;
wire   [15:0] add_ln703_6_fu_3705_p2;
wire   [20:0] mul_ln703_3_fu_376_p2;
wire   [20:0] add_ln703_7_fu_3720_p2;
wire   [23:0] mul_ln703_4_fu_397_p2;
wire   [23:0] mul_ln703_5_fu_379_p2;
wire   [23:0] mul_ln703_6_fu_392_p2;
wire   [23:0] mul_ln703_7_fu_387_p2;
wire   [23:0] mul_ln703_8_fu_375_p2;
wire   [23:0] mul_ln703_9_fu_374_p2;
wire   [23:0] mul_ln703_10_fu_388_p2;
wire   [23:0] mul_ln703_11_fu_386_p2;
wire   [22:0] mul_ln703_12_fu_384_p2;
wire   [22:0] add_ln703_16_fu_3823_p2;
wire   [23:0] mul_ln703_13_fu_383_p2;
wire   [20:0] shl_ln_fu_3844_p3;
wire   [21:0] zext_ln703_30_fu_3852_p1;
wire   [21:0] add_ln703_18_fu_3856_p2;
wire   [23:0] mul_ln703_14_fu_389_p2;
wire   [23:0] mul_ln703_15_fu_401_p2;
wire   [23:0] mul_ln703_16_fu_396_p2;
wire   [23:0] mul_ln703_17_fu_399_p2;
wire   [23:0] mul_ln703_18_fu_402_p2;
wire   [23:0] mul_ln703_19_fu_394_p2;
wire   [23:0] mul_ln703_20_fu_382_p2;
wire   [23:0] mul_ln703_21_fu_400_p2;
wire   [23:0] mul_ln703_22_fu_390_p2;
wire   [23:0] mul_ln703_23_fu_391_p2;
wire   [23:0] mul_ln703_24_fu_378_p2;
wire   [23:0] mul_ln703_25_fu_395_p2;
wire  signed [23:0] sext_ln703_fu_3613_p1;
wire  signed [23:0] sext_ln703_1_fu_3628_p1;
wire  signed [23:0] sext_ln703_3_fu_3664_p1;
wire  signed [23:0] sext_ln703_4_fu_3679_p1;
wire  signed [23:0] sext_ln703_5_fu_3711_p1;
wire  signed [23:0] sext_ln703_6_fu_3726_p1;
wire   [23:0] add_ln703_8_fu_3735_p2;
wire   [23:0] add_ln703_9_fu_3746_p2;
wire   [23:0] add_ln703_10_fu_3757_p2;
wire   [23:0] add_ln703_11_fu_3768_p2;
wire   [23:0] add_ln703_12_fu_3779_p2;
wire   [23:0] add_ln703_13_fu_3790_p2;
wire   [23:0] add_ln703_14_fu_3801_p2;
wire   [23:0] add_ln703_15_fu_3812_p2;
wire  signed [23:0] sext_ln703_7_fu_3829_p1;
wire   [23:0] add_ln703_17_fu_3838_p2;
wire  signed [23:0] sext_ln703_8_fu_3862_p1;
wire   [23:0] add_ln703_19_fu_3871_p2;
wire   [23:0] add_ln703_20_fu_3882_p2;
wire   [23:0] add_ln703_21_fu_3893_p2;
wire   [23:0] add_ln703_22_fu_3904_p2;
wire   [23:0] add_ln703_23_fu_3915_p2;
wire   [23:0] add_ln703_24_fu_3926_p2;
wire   [23:0] add_ln703_25_fu_3937_p2;
wire   [23:0] add_ln703_26_fu_3948_p2;
wire   [23:0] add_ln703_27_fu_3959_p2;
wire   [23:0] add_ln703_28_fu_3970_p2;
wire   [23:0] add_ln703_29_fu_3981_p2;
wire   [23:0] add_ln703_30_fu_3992_p2;
wire   [23:0] mul_ln703_10_fu_388_p00;
wire   [23:0] mul_ln703_11_fu_386_p00;
wire   [22:0] mul_ln703_12_fu_384_p00;
wire   [23:0] mul_ln703_13_fu_383_p00;
wire   [23:0] mul_ln703_14_fu_389_p00;
wire   [23:0] mul_ln703_15_fu_401_p00;
wire   [23:0] mul_ln703_16_fu_396_p00;
wire   [23:0] mul_ln703_17_fu_399_p00;
wire   [23:0] mul_ln703_18_fu_402_p00;
wire   [23:0] mul_ln703_19_fu_394_p00;
wire   [21:0] mul_ln703_1_fu_393_p00;
wire   [23:0] mul_ln703_20_fu_382_p00;
wire   [23:0] mul_ln703_21_fu_400_p00;
wire   [23:0] mul_ln703_22_fu_390_p00;
wire   [23:0] mul_ln703_23_fu_391_p00;
wire   [23:0] mul_ln703_24_fu_378_p00;
wire   [23:0] mul_ln703_25_fu_395_p00;
wire   [22:0] mul_ln703_2_fu_385_p00;
wire   [20:0] mul_ln703_3_fu_376_p00;
wire   [23:0] mul_ln703_4_fu_397_p00;
wire   [23:0] mul_ln703_5_fu_379_p00;
wire   [23:0] mul_ln703_6_fu_392_p00;
wire   [23:0] mul_ln703_7_fu_387_p00;
wire   [23:0] mul_ln703_8_fu_375_p00;
wire   [23:0] mul_ln703_9_fu_374_p00;
wire   [21:0] mul_ln703_fu_380_p00;

assign add_ln703_10_fu_3757_p2 = ($signed(mul_ln703_6_fu_392_p2) + $signed(24'd16683238));

assign add_ln703_11_fu_3768_p2 = ($signed(mul_ln703_7_fu_387_p2) + $signed(24'd16543033));

assign add_ln703_12_fu_3779_p2 = ($signed(mul_ln703_8_fu_375_p2) + $signed(24'd16763024));

assign add_ln703_13_fu_3790_p2 = ($signed(mul_ln703_9_fu_374_p2) + $signed(24'd16731911));

assign add_ln703_14_fu_3801_p2 = ($signed(mul_ln703_10_fu_388_p2) + $signed(24'd16735877));

assign add_ln703_15_fu_3812_p2 = (mul_ln703_11_fu_386_p2 + 24'd34856);

assign add_ln703_16_fu_3823_p2 = ($signed(mul_ln703_12_fu_384_p2) + $signed(23'd8352215));

assign add_ln703_17_fu_3838_p2 = (mul_ln703_13_fu_383_p2 + 24'd111739);

assign add_ln703_18_fu_3856_p2 = ($signed(zext_ln703_30_fu_3852_p1) + $signed(22'd4185806));

assign add_ln703_19_fu_3871_p2 = ($signed(mul_ln703_14_fu_389_p2) + $signed(24'd16716297));

assign add_ln703_1_fu_3622_p2 = ($signed(mul_ln703_1_fu_393_p2) + $signed(22'd4113058));

assign add_ln703_20_fu_3882_p2 = ($signed(mul_ln703_15_fu_401_p2) + $signed(24'd16715287));

assign add_ln703_21_fu_3893_p2 = (mul_ln703_16_fu_396_p2 + 24'd3631);

assign add_ln703_22_fu_3904_p2 = (mul_ln703_17_fu_399_p2 + 24'd2977);

assign add_ln703_23_fu_3915_p2 = ($signed(mul_ln703_18_fu_402_p2) + $signed(24'd16746163));

assign add_ln703_24_fu_3926_p2 = (mul_ln703_19_fu_394_p2 + 24'd14962);

assign add_ln703_25_fu_3937_p2 = ($signed(mul_ln703_20_fu_382_p2) + $signed(24'd16673734));

assign add_ln703_26_fu_3948_p2 = ($signed(mul_ln703_21_fu_400_p2) + $signed(24'd16602293));

assign add_ln703_27_fu_3959_p2 = ($signed(mul_ln703_22_fu_390_p2) + $signed(24'd16682178));

assign add_ln703_28_fu_3970_p2 = ($signed(mul_ln703_23_fu_391_p2) + $signed(24'd16674595));

assign add_ln703_29_fu_3981_p2 = ($signed(mul_ln703_24_fu_378_p2) + $signed(24'd16701115));

assign add_ln703_2_fu_3648_p2 = ($signed(zext_ln703_2_fu_3632_p1) + $signed(14'd10746));

assign add_ln703_30_fu_3992_p2 = ($signed(mul_ln703_25_fu_395_p2) + $signed(24'd16735530));

assign add_ln703_3_fu_3658_p2 = ($signed(zext_ln703_3_fu_3644_p1) + $signed(sext_ln703_2_fu_3654_p1));

assign add_ln703_4_fu_3673_p2 = ($signed(mul_ln703_2_fu_385_p2) + $signed(23'd8139556));

assign add_ln703_5_fu_3699_p2 = ($signed(zext_ln703_5_fu_3683_p1) + $signed(16'd46186));

assign add_ln703_6_fu_3705_p2 = (zext_ln703_14_fu_3695_p1 + add_ln703_5_fu_3699_p2);

assign add_ln703_7_fu_3720_p2 = ($signed(mul_ln703_3_fu_376_p2) + $signed(21'd1886239));

assign add_ln703_8_fu_3735_p2 = ($signed(mul_ln703_4_fu_397_p2) + $signed(24'd16600467));

assign add_ln703_9_fu_3746_p2 = ($signed(mul_ln703_5_fu_379_p2) + $signed(24'd16624836));

assign add_ln703_fu_3607_p2 = ($signed(mul_ln703_fu_380_p2) + $signed(22'd4127148));

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln703_fu_3613_p1;

assign ap_return_1 = sext_ln703_1_fu_3628_p1;

assign ap_return_10 = add_ln703_12_fu_3779_p2;

assign ap_return_11 = add_ln703_13_fu_3790_p2;

assign ap_return_12 = add_ln703_14_fu_3801_p2;

assign ap_return_13 = add_ln703_15_fu_3812_p2;

assign ap_return_14 = sext_ln703_7_fu_3829_p1;

assign ap_return_15 = add_ln703_17_fu_3838_p2;

assign ap_return_16 = sext_ln703_8_fu_3862_p1;

assign ap_return_17 = add_ln703_19_fu_3871_p2;

assign ap_return_18 = add_ln703_20_fu_3882_p2;

assign ap_return_19 = add_ln703_21_fu_3893_p2;

assign ap_return_2 = sext_ln703_3_fu_3664_p1;

assign ap_return_20 = add_ln703_22_fu_3904_p2;

assign ap_return_21 = add_ln703_23_fu_3915_p2;

assign ap_return_22 = add_ln703_24_fu_3926_p2;

assign ap_return_23 = add_ln703_25_fu_3937_p2;

assign ap_return_24 = add_ln703_26_fu_3948_p2;

assign ap_return_25 = add_ln703_27_fu_3959_p2;

assign ap_return_26 = add_ln703_28_fu_3970_p2;

assign ap_return_27 = add_ln703_29_fu_3981_p2;

assign ap_return_28 = add_ln703_30_fu_3992_p2;

assign ap_return_3 = sext_ln703_4_fu_3679_p1;

assign ap_return_4 = sext_ln703_5_fu_3711_p1;

assign ap_return_5 = sext_ln703_6_fu_3726_p1;

assign ap_return_6 = add_ln703_8_fu_3735_p2;

assign ap_return_7 = add_ln703_9_fu_3746_p2;

assign ap_return_8 = add_ln703_10_fu_3757_p2;

assign ap_return_9 = add_ln703_11_fu_3768_p2;

assign mul_ln703_10_fu_388_p0 = mul_ln703_10_fu_388_p00;

assign mul_ln703_10_fu_388_p00 = data_12_V_read;

assign mul_ln703_10_fu_388_p2 = (mul_ln703_10_fu_388_p0 * $signed('h15F6));

assign mul_ln703_11_fu_386_p0 = mul_ln703_11_fu_386_p00;

assign mul_ln703_11_fu_386_p00 = data_13_V_read;

assign mul_ln703_11_fu_386_p2 = (mul_ln703_11_fu_386_p0 * $signed('h1676));

assign mul_ln703_12_fu_384_p0 = mul_ln703_12_fu_384_p00;

assign mul_ln703_12_fu_384_p00 = data_14_V_read;

assign mul_ln703_12_fu_384_p2 = (mul_ln703_12_fu_384_p0 * $signed('h178));

assign mul_ln703_13_fu_383_p0 = mul_ln703_13_fu_383_p00;

assign mul_ln703_13_fu_383_p00 = data_15_V_read;

assign mul_ln703_13_fu_383_p2 = (mul_ln703_13_fu_383_p0 * $signed('h6E6));

assign mul_ln703_14_fu_389_p0 = mul_ln703_14_fu_389_p00;

assign mul_ln703_14_fu_389_p00 = data_17_V_read;

assign mul_ln703_14_fu_389_p2 = (mul_ln703_14_fu_389_p0 * $signed('h61B));

assign mul_ln703_15_fu_401_p0 = mul_ln703_15_fu_401_p00;

assign mul_ln703_15_fu_401_p00 = data_18_V_read;

assign mul_ln703_15_fu_401_p2 = (mul_ln703_15_fu_401_p0 * $signed('h4465));

assign mul_ln703_16_fu_396_p0 = mul_ln703_16_fu_396_p00;

assign mul_ln703_16_fu_396_p00 = data_19_V_read;

assign mul_ln703_16_fu_396_p2 = (mul_ln703_16_fu_396_p0 * $signed('h85CB));

assign mul_ln703_17_fu_399_p0 = mul_ln703_17_fu_399_p00;

assign mul_ln703_17_fu_399_p00 = data_20_V_read;

assign mul_ln703_17_fu_399_p2 = ($signed({{1'b0}, {mul_ln703_17_fu_399_p0}}) * $signed(-'h2E22));

assign mul_ln703_18_fu_402_p0 = mul_ln703_18_fu_402_p00;

assign mul_ln703_18_fu_402_p00 = data_21_V_read;

assign mul_ln703_18_fu_402_p2 = (mul_ln703_18_fu_402_p0 * $signed('h7151));

assign mul_ln703_19_fu_394_p0 = mul_ln703_19_fu_394_p00;

assign mul_ln703_19_fu_394_p00 = data_22_V_read;

assign mul_ln703_19_fu_394_p2 = (mul_ln703_19_fu_394_p0 * $signed('h303C));

assign mul_ln703_1_fu_393_p0 = mul_ln703_1_fu_393_p00;

assign mul_ln703_1_fu_393_p00 = data_1_V_read;

assign mul_ln703_1_fu_393_p2 = (mul_ln703_1_fu_393_p0 * $signed('h106));

assign mul_ln703_20_fu_382_p0 = mul_ln703_20_fu_382_p00;

assign mul_ln703_20_fu_382_p00 = data_23_V_read;

assign mul_ln703_20_fu_382_p2 = (mul_ln703_20_fu_382_p0 * $signed('h6269));

assign mul_ln703_21_fu_400_p0 = mul_ln703_21_fu_400_p00;

assign mul_ln703_21_fu_400_p00 = data_24_V_read;

assign mul_ln703_21_fu_400_p2 = (mul_ln703_21_fu_400_p0 * $signed('h3E62));

assign mul_ln703_22_fu_390_p0 = mul_ln703_22_fu_390_p00;

assign mul_ln703_22_fu_390_p00 = data_25_V_read;

assign mul_ln703_22_fu_390_p2 = (mul_ln703_22_fu_390_p0 * $signed('h20F6));

assign mul_ln703_23_fu_391_p0 = mul_ln703_23_fu_391_p00;

assign mul_ln703_23_fu_391_p00 = data_26_V_read;

assign mul_ln703_23_fu_391_p2 = (mul_ln703_23_fu_391_p0 * $signed('h581A));

assign mul_ln703_24_fu_378_p0 = mul_ln703_24_fu_378_p00;

assign mul_ln703_24_fu_378_p00 = data_27_V_read;

assign mul_ln703_24_fu_378_p2 = (mul_ln703_24_fu_378_p0 * $signed('h1DAF));

assign mul_ln703_25_fu_395_p0 = mul_ln703_25_fu_395_p00;

assign mul_ln703_25_fu_395_p00 = data_28_V_read;

assign mul_ln703_25_fu_395_p2 = (mul_ln703_25_fu_395_p0 * $signed('hEF7));

assign mul_ln703_2_fu_385_p0 = mul_ln703_2_fu_385_p00;

assign mul_ln703_2_fu_385_p00 = data_3_V_read;

assign mul_ln703_2_fu_385_p2 = (mul_ln703_2_fu_385_p0 * $signed('h17B));

assign mul_ln703_3_fu_376_p0 = mul_ln703_3_fu_376_p00;

assign mul_ln703_3_fu_376_p00 = data_5_V_read;

assign mul_ln703_3_fu_376_p2 = (mul_ln703_3_fu_376_p0 * $signed('h87));

assign mul_ln703_4_fu_397_p0 = mul_ln703_4_fu_397_p00;

assign mul_ln703_4_fu_397_p00 = data_6_V_read;

assign mul_ln703_4_fu_397_p2 = (mul_ln703_4_fu_397_p0 * $signed('h4E838));

assign mul_ln703_5_fu_379_p0 = mul_ln703_5_fu_379_p00;

assign mul_ln703_5_fu_379_p00 = data_7_V_read;

assign mul_ln703_5_fu_379_p2 = (mul_ln703_5_fu_379_p0 * $signed('h36F28));

assign mul_ln703_6_fu_392_p0 = mul_ln703_6_fu_392_p00;

assign mul_ln703_6_fu_392_p00 = data_8_V_read;

assign mul_ln703_6_fu_392_p2 = (mul_ln703_6_fu_392_p0 * $signed('hD814));

assign mul_ln703_7_fu_387_p0 = mul_ln703_7_fu_387_p00;

assign mul_ln703_7_fu_387_p00 = data_9_V_read;

assign mul_ln703_7_fu_387_p2 = (mul_ln703_7_fu_387_p0 * $signed('h6D924));

assign mul_ln703_8_fu_375_p0 = mul_ln703_8_fu_375_p00;

assign mul_ln703_8_fu_375_p00 = data_10_V_read;

assign mul_ln703_8_fu_375_p2 = (mul_ln703_8_fu_375_p0 * $signed('hC8EA));

assign mul_ln703_9_fu_374_p0 = mul_ln703_9_fu_374_p00;

assign mul_ln703_9_fu_374_p00 = data_11_V_read;

assign mul_ln703_9_fu_374_p2 = (mul_ln703_9_fu_374_p0 * $signed('h111A7));

assign mul_ln703_fu_380_p0 = mul_ln703_fu_380_p00;

assign mul_ln703_fu_380_p00 = data_0_V_read;

assign mul_ln703_fu_380_p2 = (mul_ln703_fu_380_p0 * $signed('hF2));

assign sext_ln703_1_fu_3628_p1 = $signed(add_ln703_1_fu_3622_p2);

assign sext_ln703_2_fu_3654_p1 = $signed(add_ln703_2_fu_3648_p2);

assign sext_ln703_3_fu_3664_p1 = $signed(add_ln703_3_fu_3658_p2);

assign sext_ln703_4_fu_3679_p1 = $signed(add_ln703_4_fu_3673_p2);

assign sext_ln703_5_fu_3711_p1 = $signed(add_ln703_6_fu_3705_p2);

assign sext_ln703_6_fu_3726_p1 = $signed(add_ln703_7_fu_3720_p2);

assign sext_ln703_7_fu_3829_p1 = $signed(add_ln703_16_fu_3823_p2);

assign sext_ln703_8_fu_3862_p1 = $signed(add_ln703_18_fu_3856_p2);

assign sext_ln703_fu_3613_p1 = $signed(add_ln703_fu_3607_p2);

assign shl_ln703_1_fu_3636_p3 = {{data_2_V_read}, {2'd0}};

assign shl_ln703_2_fu_3687_p3 = {{data_4_V_read}, {2'd0}};

assign shl_ln_fu_3844_p3 = {{data_16_V_read}, {8'd0}};

assign zext_ln703_14_fu_3695_p1 = shl_ln703_2_fu_3687_p3;

assign zext_ln703_2_fu_3632_p1 = data_2_V_read;

assign zext_ln703_30_fu_3852_p1 = shl_ln_fu_3844_p3;

assign zext_ln703_3_fu_3644_p1 = shl_ln703_1_fu_3636_p3;

assign zext_ln703_5_fu_3683_p1 = data_4_V_read;

endmodule //normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s
