// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] data_0_V_read;
input  [23:0] data_1_V_read;
input  [23:0] data_2_V_read;
input  [23:0] data_3_V_read;
input  [23:0] data_4_V_read;
input  [23:0] data_5_V_read;
input  [23:0] data_6_V_read;
input  [23:0] data_7_V_read;
input  [23:0] data_8_V_read;
input  [23:0] data_9_V_read;
input  [23:0] data_10_V_read;
input  [23:0] data_11_V_read;
input  [23:0] data_12_V_read;
input  [23:0] data_13_V_read;
input  [23:0] data_14_V_read;
input  [23:0] data_15_V_read;
input  [23:0] data_16_V_read;
input  [23:0] data_17_V_read;
input  [23:0] data_18_V_read;
input  [23:0] data_19_V_read;
output  [23:0] ap_return_0;
output  [23:0] ap_return_1;
output  [23:0] ap_return_2;
output  [23:0] ap_return_3;
output  [23:0] ap_return_4;
output  [23:0] ap_return_5;
output  [23:0] ap_return_6;
output  [23:0] ap_return_7;
output  [23:0] ap_return_8;
output  [23:0] ap_return_9;
output  [23:0] ap_return_10;
output  [23:0] ap_return_11;
output  [23:0] ap_return_12;
output  [23:0] ap_return_13;
output  [23:0] ap_return_14;
output  [23:0] ap_return_15;
output  [23:0] ap_return_16;
output  [23:0] ap_return_17;
output  [23:0] ap_return_18;
output  [23:0] ap_return_19;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] tanh_table1_address0;
reg    tanh_table1_ce0;
wire   [10:0] tanh_table1_q0;
wire   [9:0] tanh_table1_address1;
reg    tanh_table1_ce1;
wire   [10:0] tanh_table1_q1;
wire   [9:0] tanh_table1_address2;
reg    tanh_table1_ce2;
wire   [10:0] tanh_table1_q2;
wire   [9:0] tanh_table1_address3;
reg    tanh_table1_ce3;
wire   [10:0] tanh_table1_q3;
wire   [9:0] tanh_table1_address4;
reg    tanh_table1_ce4;
wire   [10:0] tanh_table1_q4;
wire   [9:0] tanh_table1_address5;
reg    tanh_table1_ce5;
wire   [10:0] tanh_table1_q5;
wire   [9:0] tanh_table1_address6;
reg    tanh_table1_ce6;
wire   [10:0] tanh_table1_q6;
wire   [9:0] tanh_table1_address7;
reg    tanh_table1_ce7;
wire   [10:0] tanh_table1_q7;
wire   [9:0] tanh_table1_address8;
reg    tanh_table1_ce8;
wire   [10:0] tanh_table1_q8;
wire   [9:0] tanh_table1_address9;
reg    tanh_table1_ce9;
wire   [10:0] tanh_table1_q9;
wire   [9:0] tanh_table1_address10;
reg    tanh_table1_ce10;
wire   [10:0] tanh_table1_q10;
wire   [9:0] tanh_table1_address11;
reg    tanh_table1_ce11;
wire   [10:0] tanh_table1_q11;
wire   [9:0] tanh_table1_address12;
reg    tanh_table1_ce12;
wire   [10:0] tanh_table1_q12;
wire   [9:0] tanh_table1_address13;
reg    tanh_table1_ce13;
wire   [10:0] tanh_table1_q13;
wire   [9:0] tanh_table1_address14;
reg    tanh_table1_ce14;
wire   [10:0] tanh_table1_q14;
wire   [9:0] tanh_table1_address15;
reg    tanh_table1_ce15;
wire   [10:0] tanh_table1_q15;
wire   [9:0] tanh_table1_address16;
reg    tanh_table1_ce16;
wire   [10:0] tanh_table1_q16;
wire   [9:0] tanh_table1_address17;
reg    tanh_table1_ce17;
wire   [10:0] tanh_table1_q17;
wire   [9:0] tanh_table1_address18;
reg    tanh_table1_ce18;
wire   [10:0] tanh_table1_q18;
wire   [9:0] tanh_table1_address19;
reg    tanh_table1_ce19;
wire   [10:0] tanh_table1_q19;
wire   [9:0] select_ln476_fu_589_p3;
reg   [9:0] select_ln476_reg_3469;
wire   [9:0] select_ln476_1_fu_717_p3;
reg   [9:0] select_ln476_1_reg_3474;
wire   [9:0] select_ln476_2_fu_845_p3;
reg   [9:0] select_ln476_2_reg_3479;
wire   [9:0] select_ln476_3_fu_973_p3;
reg   [9:0] select_ln476_3_reg_3484;
wire   [9:0] select_ln476_4_fu_1101_p3;
reg   [9:0] select_ln476_4_reg_3489;
wire   [9:0] select_ln476_5_fu_1229_p3;
reg   [9:0] select_ln476_5_reg_3494;
wire   [9:0] select_ln476_6_fu_1357_p3;
reg   [9:0] select_ln476_6_reg_3499;
wire   [9:0] select_ln476_7_fu_1485_p3;
reg   [9:0] select_ln476_7_reg_3504;
wire   [9:0] select_ln476_8_fu_1613_p3;
reg   [9:0] select_ln476_8_reg_3509;
wire   [9:0] select_ln476_9_fu_1741_p3;
reg   [9:0] select_ln476_9_reg_3514;
wire   [9:0] select_ln476_10_fu_1869_p3;
reg   [9:0] select_ln476_10_reg_3519;
wire   [9:0] select_ln476_11_fu_1997_p3;
reg   [9:0] select_ln476_11_reg_3524;
wire   [9:0] select_ln476_12_fu_2125_p3;
reg   [9:0] select_ln476_12_reg_3529;
wire   [9:0] select_ln476_13_fu_2253_p3;
reg   [9:0] select_ln476_13_reg_3534;
wire   [9:0] select_ln476_14_fu_2381_p3;
reg   [9:0] select_ln476_14_reg_3539;
wire   [9:0] select_ln476_15_fu_2509_p3;
reg   [9:0] select_ln476_15_reg_3544;
wire   [9:0] select_ln476_16_fu_2637_p3;
reg   [9:0] select_ln476_16_reg_3549;
wire   [9:0] select_ln476_17_fu_2765_p3;
reg   [9:0] select_ln476_17_reg_3554;
wire   [9:0] select_ln476_18_fu_2893_p3;
reg   [9:0] select_ln476_18_reg_3559;
wire   [9:0] select_ln476_19_fu_3021_p3;
reg   [9:0] select_ln476_19_reg_3564;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln477_fu_3029_p1;
wire   [63:0] zext_ln477_1_fu_3033_p1;
wire   [63:0] zext_ln477_2_fu_3037_p1;
wire   [63:0] zext_ln477_3_fu_3041_p1;
wire   [63:0] zext_ln477_4_fu_3045_p1;
wire   [63:0] zext_ln477_5_fu_3049_p1;
wire   [63:0] zext_ln477_6_fu_3053_p1;
wire   [63:0] zext_ln477_7_fu_3057_p1;
wire   [63:0] zext_ln477_8_fu_3061_p1;
wire   [63:0] zext_ln477_9_fu_3065_p1;
wire   [63:0] zext_ln477_10_fu_3069_p1;
wire   [63:0] zext_ln477_11_fu_3073_p1;
wire   [63:0] zext_ln477_12_fu_3077_p1;
wire   [63:0] zext_ln477_13_fu_3081_p1;
wire   [63:0] zext_ln477_14_fu_3085_p1;
wire   [63:0] zext_ln477_15_fu_3089_p1;
wire   [63:0] zext_ln477_16_fu_3093_p1;
wire   [63:0] zext_ln477_17_fu_3097_p1;
wire   [63:0] zext_ln477_18_fu_3101_p1;
wire   [63:0] zext_ln477_19_fu_3105_p1;
wire   [14:0] tmp_1_fu_477_p4;
wire   [33:0] shl_ln_fu_469_p3;
wire   [8:0] trunc_ln851_fu_497_p1;
wire   [15:0] p_Result_2_fu_501_p3;
wire  signed [15:0] sext_ln850_fu_487_p1;
wire   [0:0] icmp_ln851_fu_509_p2;
wire   [15:0] add_ln700_fu_515_p2;
wire   [0:0] icmp_ln850_fu_491_p2;
wire   [15:0] select_ln851_fu_521_p3;
wire   [15:0] select_ln850_fu_529_p3;
wire   [14:0] trunc_ln473_fu_537_p1;
wire   [15:0] add_ln473_fu_541_p2;
wire   [0:0] tmp_2_fu_553_p3;
wire   [14:0] add_ln473_20_fu_547_p2;
wire   [14:0] select_ln475_fu_561_p3;
wire   [4:0] tmp_4_fu_573_p4;
wire   [0:0] icmp_ln476_fu_583_p2;
wire   [9:0] trunc_ln475_fu_569_p1;
wire   [14:0] tmp_3_fu_605_p4;
wire   [33:0] shl_ln1118_1_fu_597_p3;
wire   [8:0] trunc_ln851_1_fu_625_p1;
wire   [15:0] p_Result_2_1_fu_629_p3;
wire  signed [15:0] sext_ln850_1_fu_615_p1;
wire   [0:0] icmp_ln851_1_fu_637_p2;
wire   [15:0] add_ln700_1_fu_643_p2;
wire   [0:0] icmp_ln850_1_fu_619_p2;
wire   [15:0] select_ln851_1_fu_649_p3;
wire   [15:0] select_ln850_1_fu_657_p3;
wire   [14:0] trunc_ln473_1_fu_665_p1;
wire   [15:0] add_ln473_1_fu_669_p2;
wire   [0:0] tmp_6_fu_681_p3;
wire   [14:0] add_ln473_21_fu_675_p2;
wire   [14:0] select_ln475_1_fu_689_p3;
wire   [4:0] tmp_8_fu_701_p4;
wire   [0:0] icmp_ln476_1_fu_711_p2;
wire   [9:0] trunc_ln475_1_fu_697_p1;
wire   [14:0] tmp_5_fu_733_p4;
wire   [33:0] shl_ln1118_2_fu_725_p3;
wire   [8:0] trunc_ln851_2_fu_753_p1;
wire   [15:0] p_Result_2_2_fu_757_p3;
wire  signed [15:0] sext_ln850_2_fu_743_p1;
wire   [0:0] icmp_ln851_2_fu_765_p2;
wire   [15:0] add_ln700_2_fu_771_p2;
wire   [0:0] icmp_ln850_2_fu_747_p2;
wire   [15:0] select_ln851_2_fu_777_p3;
wire   [15:0] select_ln850_2_fu_785_p3;
wire   [14:0] trunc_ln473_2_fu_793_p1;
wire   [15:0] add_ln473_2_fu_797_p2;
wire   [0:0] tmp_13_fu_809_p3;
wire   [14:0] add_ln473_22_fu_803_p2;
wire   [14:0] select_ln475_2_fu_817_p3;
wire   [4:0] tmp_15_fu_829_p4;
wire   [0:0] icmp_ln476_2_fu_839_p2;
wire   [9:0] trunc_ln475_2_fu_825_p1;
wire   [14:0] tmp_7_fu_861_p4;
wire   [33:0] shl_ln1118_3_fu_853_p3;
wire   [8:0] trunc_ln851_3_fu_881_p1;
wire   [15:0] p_Result_2_3_fu_885_p3;
wire  signed [15:0] sext_ln850_3_fu_871_p1;
wire   [0:0] icmp_ln851_3_fu_893_p2;
wire   [15:0] add_ln700_3_fu_899_p2;
wire   [0:0] icmp_ln850_3_fu_875_p2;
wire   [15:0] select_ln851_3_fu_905_p3;
wire   [15:0] select_ln850_3_fu_913_p3;
wire   [14:0] trunc_ln473_3_fu_921_p1;
wire   [15:0] add_ln473_3_fu_925_p2;
wire   [0:0] tmp_19_fu_937_p3;
wire   [14:0] add_ln473_23_fu_931_p2;
wire   [14:0] select_ln475_3_fu_945_p3;
wire   [4:0] tmp_21_fu_957_p4;
wire   [0:0] icmp_ln476_3_fu_967_p2;
wire   [9:0] trunc_ln475_3_fu_953_p1;
wire   [14:0] tmp_9_fu_989_p4;
wire   [33:0] shl_ln1118_4_fu_981_p3;
wire   [8:0] trunc_ln851_4_fu_1009_p1;
wire   [15:0] p_Result_2_4_fu_1013_p3;
wire  signed [15:0] sext_ln850_4_fu_999_p1;
wire   [0:0] icmp_ln851_4_fu_1021_p2;
wire   [15:0] add_ln700_4_fu_1027_p2;
wire   [0:0] icmp_ln850_4_fu_1003_p2;
wire   [15:0] select_ln851_4_fu_1033_p3;
wire   [15:0] select_ln850_4_fu_1041_p3;
wire   [14:0] trunc_ln473_4_fu_1049_p1;
wire   [15:0] add_ln473_4_fu_1053_p2;
wire   [0:0] tmp_25_fu_1065_p3;
wire   [14:0] add_ln473_24_fu_1059_p2;
wire   [14:0] select_ln475_4_fu_1073_p3;
wire   [4:0] tmp_27_fu_1085_p4;
wire   [0:0] icmp_ln476_4_fu_1095_p2;
wire   [9:0] trunc_ln475_4_fu_1081_p1;
wire   [14:0] tmp_10_fu_1117_p4;
wire   [33:0] shl_ln1118_5_fu_1109_p3;
wire   [8:0] trunc_ln851_5_fu_1137_p1;
wire   [15:0] p_Result_2_5_fu_1141_p3;
wire  signed [15:0] sext_ln850_5_fu_1127_p1;
wire   [0:0] icmp_ln851_5_fu_1149_p2;
wire   [15:0] add_ln700_5_fu_1155_p2;
wire   [0:0] icmp_ln850_5_fu_1131_p2;
wire   [15:0] select_ln851_5_fu_1161_p3;
wire   [15:0] select_ln850_5_fu_1169_p3;
wire   [14:0] trunc_ln473_5_fu_1177_p1;
wire   [15:0] add_ln473_5_fu_1181_p2;
wire   [0:0] tmp_31_fu_1193_p3;
wire   [14:0] add_ln473_25_fu_1187_p2;
wire   [14:0] select_ln475_5_fu_1201_p3;
wire   [4:0] tmp_33_fu_1213_p4;
wire   [0:0] icmp_ln476_5_fu_1223_p2;
wire   [9:0] trunc_ln475_5_fu_1209_p1;
wire   [14:0] tmp_12_fu_1245_p4;
wire   [33:0] shl_ln1118_6_fu_1237_p3;
wire   [8:0] trunc_ln851_6_fu_1265_p1;
wire   [15:0] p_Result_2_6_fu_1269_p3;
wire  signed [15:0] sext_ln850_6_fu_1255_p1;
wire   [0:0] icmp_ln851_6_fu_1277_p2;
wire   [15:0] add_ln700_6_fu_1283_p2;
wire   [0:0] icmp_ln850_6_fu_1259_p2;
wire   [15:0] select_ln851_6_fu_1289_p3;
wire   [15:0] select_ln850_6_fu_1297_p3;
wire   [14:0] trunc_ln473_6_fu_1305_p1;
wire   [15:0] add_ln473_6_fu_1309_p2;
wire   [0:0] tmp_37_fu_1321_p3;
wire   [14:0] add_ln473_26_fu_1315_p2;
wire   [14:0] select_ln475_6_fu_1329_p3;
wire   [4:0] tmp_39_fu_1341_p4;
wire   [0:0] icmp_ln476_6_fu_1351_p2;
wire   [9:0] trunc_ln475_6_fu_1337_p1;
wire   [14:0] tmp_14_fu_1373_p4;
wire   [33:0] shl_ln1118_7_fu_1365_p3;
wire   [8:0] trunc_ln851_7_fu_1393_p1;
wire   [15:0] p_Result_2_7_fu_1397_p3;
wire  signed [15:0] sext_ln850_7_fu_1383_p1;
wire   [0:0] icmp_ln851_7_fu_1405_p2;
wire   [15:0] add_ln700_7_fu_1411_p2;
wire   [0:0] icmp_ln850_7_fu_1387_p2;
wire   [15:0] select_ln851_7_fu_1417_p3;
wire   [15:0] select_ln850_7_fu_1425_p3;
wire   [14:0] trunc_ln473_7_fu_1433_p1;
wire   [15:0] add_ln473_7_fu_1437_p2;
wire   [0:0] tmp_41_fu_1449_p3;
wire   [14:0] add_ln473_27_fu_1443_p2;
wire   [14:0] select_ln475_7_fu_1457_p3;
wire   [4:0] tmp_42_fu_1469_p4;
wire   [0:0] icmp_ln476_7_fu_1479_p2;
wire   [9:0] trunc_ln475_7_fu_1465_p1;
wire   [14:0] tmp_16_fu_1501_p4;
wire   [33:0] shl_ln1118_8_fu_1493_p3;
wire   [8:0] trunc_ln851_8_fu_1521_p1;
wire   [15:0] p_Result_2_8_fu_1525_p3;
wire  signed [15:0] sext_ln850_8_fu_1511_p1;
wire   [0:0] icmp_ln851_8_fu_1533_p2;
wire   [15:0] add_ln700_8_fu_1539_p2;
wire   [0:0] icmp_ln850_8_fu_1515_p2;
wire   [15:0] select_ln851_8_fu_1545_p3;
wire   [15:0] select_ln850_8_fu_1553_p3;
wire   [14:0] trunc_ln473_8_fu_1561_p1;
wire   [15:0] add_ln473_8_fu_1565_p2;
wire   [0:0] tmp_44_fu_1577_p3;
wire   [14:0] add_ln473_28_fu_1571_p2;
wire   [14:0] select_ln475_8_fu_1585_p3;
wire   [4:0] tmp_45_fu_1597_p4;
wire   [0:0] icmp_ln476_8_fu_1607_p2;
wire   [9:0] trunc_ln475_8_fu_1593_p1;
wire   [14:0] tmp_18_fu_1629_p4;
wire   [33:0] shl_ln1118_9_fu_1621_p3;
wire   [8:0] trunc_ln851_9_fu_1649_p1;
wire   [15:0] p_Result_2_9_fu_1653_p3;
wire  signed [15:0] sext_ln850_9_fu_1639_p1;
wire   [0:0] icmp_ln851_9_fu_1661_p2;
wire   [15:0] add_ln700_9_fu_1667_p2;
wire   [0:0] icmp_ln850_9_fu_1643_p2;
wire   [15:0] select_ln851_9_fu_1673_p3;
wire   [15:0] select_ln850_9_fu_1681_p3;
wire   [14:0] trunc_ln473_9_fu_1689_p1;
wire   [15:0] add_ln473_9_fu_1693_p2;
wire   [0:0] tmp_47_fu_1705_p3;
wire   [14:0] add_ln473_29_fu_1699_p2;
wire   [14:0] select_ln475_9_fu_1713_p3;
wire   [4:0] tmp_48_fu_1725_p4;
wire   [0:0] icmp_ln476_9_fu_1735_p2;
wire   [9:0] trunc_ln475_9_fu_1721_p1;
wire   [14:0] tmp_20_fu_1757_p4;
wire   [33:0] shl_ln1118_s_fu_1749_p3;
wire   [8:0] trunc_ln851_10_fu_1777_p1;
wire   [15:0] p_Result_2_s_fu_1781_p3;
wire  signed [15:0] sext_ln850_10_fu_1767_p1;
wire   [0:0] icmp_ln851_10_fu_1789_p2;
wire   [15:0] add_ln700_10_fu_1795_p2;
wire   [0:0] icmp_ln850_10_fu_1771_p2;
wire   [15:0] select_ln851_10_fu_1801_p3;
wire   [15:0] select_ln850_10_fu_1809_p3;
wire   [14:0] trunc_ln473_10_fu_1817_p1;
wire   [15:0] add_ln473_10_fu_1821_p2;
wire   [0:0] tmp_60_fu_1833_p3;
wire   [14:0] add_ln473_30_fu_1827_p2;
wire   [14:0] select_ln475_10_fu_1841_p3;
wire   [4:0] tmp_61_fu_1853_p4;
wire   [0:0] icmp_ln476_10_fu_1863_p2;
wire   [9:0] trunc_ln475_10_fu_1849_p1;
wire   [14:0] tmp_22_fu_1885_p4;
wire   [33:0] shl_ln1118_10_fu_1877_p3;
wire   [8:0] trunc_ln851_11_fu_1905_p1;
wire   [15:0] p_Result_2_10_fu_1909_p3;
wire  signed [15:0] sext_ln850_11_fu_1895_p1;
wire   [0:0] icmp_ln851_11_fu_1917_p2;
wire   [15:0] add_ln700_11_fu_1923_p2;
wire   [0:0] icmp_ln850_11_fu_1899_p2;
wire   [15:0] select_ln851_11_fu_1929_p3;
wire   [15:0] select_ln850_11_fu_1937_p3;
wire   [14:0] trunc_ln473_11_fu_1945_p1;
wire   [15:0] add_ln473_11_fu_1949_p2;
wire   [0:0] tmp_62_fu_1961_p3;
wire   [14:0] add_ln473_31_fu_1955_p2;
wire   [14:0] select_ln475_11_fu_1969_p3;
wire   [4:0] tmp_63_fu_1981_p4;
wire   [0:0] icmp_ln476_11_fu_1991_p2;
wire   [9:0] trunc_ln475_11_fu_1977_p1;
wire   [14:0] tmp_24_fu_2013_p4;
wire   [33:0] shl_ln1118_11_fu_2005_p3;
wire   [8:0] trunc_ln851_12_fu_2033_p1;
wire   [15:0] p_Result_2_11_fu_2037_p3;
wire  signed [15:0] sext_ln850_12_fu_2023_p1;
wire   [0:0] icmp_ln851_12_fu_2045_p2;
wire   [15:0] add_ln700_12_fu_2051_p2;
wire   [0:0] icmp_ln850_12_fu_2027_p2;
wire   [15:0] select_ln851_12_fu_2057_p3;
wire   [15:0] select_ln850_12_fu_2065_p3;
wire   [14:0] trunc_ln473_12_fu_2073_p1;
wire   [15:0] add_ln473_12_fu_2077_p2;
wire   [0:0] tmp_64_fu_2089_p3;
wire   [14:0] add_ln473_32_fu_2083_p2;
wire   [14:0] select_ln475_12_fu_2097_p3;
wire   [4:0] tmp_65_fu_2109_p4;
wire   [0:0] icmp_ln476_12_fu_2119_p2;
wire   [9:0] trunc_ln475_12_fu_2105_p1;
wire   [14:0] tmp_26_fu_2141_p4;
wire   [33:0] shl_ln1118_12_fu_2133_p3;
wire   [8:0] trunc_ln851_13_fu_2161_p1;
wire   [15:0] p_Result_2_12_fu_2165_p3;
wire  signed [15:0] sext_ln850_13_fu_2151_p1;
wire   [0:0] icmp_ln851_13_fu_2173_p2;
wire   [15:0] add_ln700_13_fu_2179_p2;
wire   [0:0] icmp_ln850_13_fu_2155_p2;
wire   [15:0] select_ln851_13_fu_2185_p3;
wire   [15:0] select_ln850_13_fu_2193_p3;
wire   [14:0] trunc_ln473_13_fu_2201_p1;
wire   [15:0] add_ln473_13_fu_2205_p2;
wire   [0:0] tmp_66_fu_2217_p3;
wire   [14:0] add_ln473_33_fu_2211_p2;
wire   [14:0] select_ln475_13_fu_2225_p3;
wire   [4:0] tmp_67_fu_2237_p4;
wire   [0:0] icmp_ln476_13_fu_2247_p2;
wire   [9:0] trunc_ln475_13_fu_2233_p1;
wire   [14:0] tmp_28_fu_2269_p4;
wire   [33:0] shl_ln1118_13_fu_2261_p3;
wire   [8:0] trunc_ln851_14_fu_2289_p1;
wire   [15:0] p_Result_2_13_fu_2293_p3;
wire  signed [15:0] sext_ln850_14_fu_2279_p1;
wire   [0:0] icmp_ln851_14_fu_2301_p2;
wire   [15:0] add_ln700_14_fu_2307_p2;
wire   [0:0] icmp_ln850_14_fu_2283_p2;
wire   [15:0] select_ln851_14_fu_2313_p3;
wire   [15:0] select_ln850_14_fu_2321_p3;
wire   [14:0] trunc_ln473_14_fu_2329_p1;
wire   [15:0] add_ln473_14_fu_2333_p2;
wire   [0:0] tmp_68_fu_2345_p3;
wire   [14:0] add_ln473_34_fu_2339_p2;
wire   [14:0] select_ln475_14_fu_2353_p3;
wire   [4:0] tmp_69_fu_2365_p4;
wire   [0:0] icmp_ln476_14_fu_2375_p2;
wire   [9:0] trunc_ln475_14_fu_2361_p1;
wire   [14:0] tmp_30_fu_2397_p4;
wire   [33:0] shl_ln1118_14_fu_2389_p3;
wire   [8:0] trunc_ln851_15_fu_2417_p1;
wire   [15:0] p_Result_2_14_fu_2421_p3;
wire  signed [15:0] sext_ln850_15_fu_2407_p1;
wire   [0:0] icmp_ln851_15_fu_2429_p2;
wire   [15:0] add_ln700_15_fu_2435_p2;
wire   [0:0] icmp_ln850_15_fu_2411_p2;
wire   [15:0] select_ln851_15_fu_2441_p3;
wire   [15:0] select_ln850_15_fu_2449_p3;
wire   [14:0] trunc_ln473_15_fu_2457_p1;
wire   [15:0] add_ln473_15_fu_2461_p2;
wire   [0:0] tmp_70_fu_2473_p3;
wire   [14:0] add_ln473_35_fu_2467_p2;
wire   [14:0] select_ln475_15_fu_2481_p3;
wire   [4:0] tmp_71_fu_2493_p4;
wire   [0:0] icmp_ln476_15_fu_2503_p2;
wire   [9:0] trunc_ln475_15_fu_2489_p1;
wire   [14:0] tmp_32_fu_2525_p4;
wire   [33:0] shl_ln1118_15_fu_2517_p3;
wire   [8:0] trunc_ln851_16_fu_2545_p1;
wire   [15:0] p_Result_2_15_fu_2549_p3;
wire  signed [15:0] sext_ln850_16_fu_2535_p1;
wire   [0:0] icmp_ln851_16_fu_2557_p2;
wire   [15:0] add_ln700_16_fu_2563_p2;
wire   [0:0] icmp_ln850_16_fu_2539_p2;
wire   [15:0] select_ln851_16_fu_2569_p3;
wire   [15:0] select_ln850_16_fu_2577_p3;
wire   [14:0] trunc_ln473_16_fu_2585_p1;
wire   [15:0] add_ln473_16_fu_2589_p2;
wire   [0:0] tmp_72_fu_2601_p3;
wire   [14:0] add_ln473_36_fu_2595_p2;
wire   [14:0] select_ln475_16_fu_2609_p3;
wire   [4:0] tmp_73_fu_2621_p4;
wire   [0:0] icmp_ln476_16_fu_2631_p2;
wire   [9:0] trunc_ln475_16_fu_2617_p1;
wire   [14:0] tmp_34_fu_2653_p4;
wire   [33:0] shl_ln1118_16_fu_2645_p3;
wire   [8:0] trunc_ln851_17_fu_2673_p1;
wire   [15:0] p_Result_2_16_fu_2677_p3;
wire  signed [15:0] sext_ln850_17_fu_2663_p1;
wire   [0:0] icmp_ln851_17_fu_2685_p2;
wire   [15:0] add_ln700_17_fu_2691_p2;
wire   [0:0] icmp_ln850_17_fu_2667_p2;
wire   [15:0] select_ln851_17_fu_2697_p3;
wire   [15:0] select_ln850_17_fu_2705_p3;
wire   [14:0] trunc_ln473_17_fu_2713_p1;
wire   [15:0] add_ln473_17_fu_2717_p2;
wire   [0:0] tmp_74_fu_2729_p3;
wire   [14:0] add_ln473_37_fu_2723_p2;
wire   [14:0] select_ln475_17_fu_2737_p3;
wire   [4:0] tmp_75_fu_2749_p4;
wire   [0:0] icmp_ln476_17_fu_2759_p2;
wire   [9:0] trunc_ln475_17_fu_2745_p1;
wire   [14:0] tmp_36_fu_2781_p4;
wire   [33:0] shl_ln1118_17_fu_2773_p3;
wire   [8:0] trunc_ln851_18_fu_2801_p1;
wire   [15:0] p_Result_2_17_fu_2805_p3;
wire  signed [15:0] sext_ln850_18_fu_2791_p1;
wire   [0:0] icmp_ln851_18_fu_2813_p2;
wire   [15:0] add_ln700_18_fu_2819_p2;
wire   [0:0] icmp_ln850_18_fu_2795_p2;
wire   [15:0] select_ln851_18_fu_2825_p3;
wire   [15:0] select_ln850_18_fu_2833_p3;
wire   [14:0] trunc_ln473_18_fu_2841_p1;
wire   [15:0] add_ln473_18_fu_2845_p2;
wire   [0:0] tmp_76_fu_2857_p3;
wire   [14:0] add_ln473_38_fu_2851_p2;
wire   [14:0] select_ln475_18_fu_2865_p3;
wire   [4:0] tmp_77_fu_2877_p4;
wire   [0:0] icmp_ln476_18_fu_2887_p2;
wire   [9:0] trunc_ln475_18_fu_2873_p1;
wire   [14:0] tmp_38_fu_2909_p4;
wire   [33:0] shl_ln1118_18_fu_2901_p3;
wire   [8:0] trunc_ln851_19_fu_2929_p1;
wire   [15:0] p_Result_2_18_fu_2933_p3;
wire  signed [15:0] sext_ln850_19_fu_2919_p1;
wire   [0:0] icmp_ln851_19_fu_2941_p2;
wire   [15:0] add_ln700_19_fu_2947_p2;
wire   [0:0] icmp_ln850_19_fu_2923_p2;
wire   [15:0] select_ln851_19_fu_2953_p3;
wire   [15:0] select_ln850_19_fu_2961_p3;
wire   [14:0] trunc_ln473_19_fu_2969_p1;
wire   [15:0] add_ln473_19_fu_2973_p2;
wire   [0:0] tmp_78_fu_2985_p3;
wire   [14:0] add_ln473_39_fu_2979_p2;
wire   [14:0] select_ln475_19_fu_2993_p3;
wire   [4:0] tmp_79_fu_3005_p4;
wire   [0:0] icmp_ln476_19_fu_3015_p2;
wire   [9:0] trunc_ln475_19_fu_3001_p1;
wire   [16:0] tmp_s_fu_3109_p3;
wire   [16:0] tmp_11_fu_3121_p3;
wire   [16:0] tmp_17_fu_3133_p3;
wire   [16:0] tmp_23_fu_3145_p3;
wire   [16:0] tmp_29_fu_3157_p3;
wire   [16:0] tmp_35_fu_3169_p3;
wire   [16:0] tmp_40_fu_3181_p3;
wire   [16:0] tmp_43_fu_3193_p3;
wire   [16:0] tmp_46_fu_3205_p3;
wire   [16:0] tmp_49_fu_3217_p3;
wire   [16:0] tmp_50_fu_3229_p3;
wire   [16:0] tmp_51_fu_3241_p3;
wire   [16:0] tmp_52_fu_3253_p3;
wire   [16:0] tmp_53_fu_3265_p3;
wire   [16:0] tmp_54_fu_3277_p3;
wire   [16:0] tmp_55_fu_3289_p3;
wire   [16:0] tmp_56_fu_3301_p3;
wire   [16:0] tmp_57_fu_3313_p3;
wire   [16:0] tmp_58_fu_3325_p3;
wire   [16:0] tmp_59_fu_3337_p3;
wire  signed [23:0] sext_ln728_fu_3117_p1;
wire  signed [23:0] sext_ln728_1_fu_3129_p1;
wire  signed [23:0] sext_ln728_2_fu_3141_p1;
wire  signed [23:0] sext_ln728_3_fu_3153_p1;
wire  signed [23:0] sext_ln728_4_fu_3165_p1;
wire  signed [23:0] sext_ln728_5_fu_3177_p1;
wire  signed [23:0] sext_ln728_6_fu_3189_p1;
wire  signed [23:0] sext_ln728_7_fu_3201_p1;
wire  signed [23:0] sext_ln728_8_fu_3213_p1;
wire  signed [23:0] sext_ln728_9_fu_3225_p1;
wire  signed [23:0] sext_ln728_10_fu_3237_p1;
wire  signed [23:0] sext_ln728_11_fu_3249_p1;
wire  signed [23:0] sext_ln728_12_fu_3261_p1;
wire  signed [23:0] sext_ln728_13_fu_3273_p1;
wire  signed [23:0] sext_ln728_14_fu_3285_p1;
wire  signed [23:0] sext_ln728_15_fu_3297_p1;
wire  signed [23:0] sext_ln728_16_fu_3309_p1;
wire  signed [23:0] sext_ln728_17_fu_3321_p1;
wire  signed [23:0] sext_ln728_18_fu_3333_p1;
wire  signed [23:0] sext_ln728_19_fu_3345_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s_tanh_tabbkb #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tanh_table1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tanh_table1_address0),
    .ce0(tanh_table1_ce0),
    .q0(tanh_table1_q0),
    .address1(tanh_table1_address1),
    .ce1(tanh_table1_ce1),
    .q1(tanh_table1_q1),
    .address2(tanh_table1_address2),
    .ce2(tanh_table1_ce2),
    .q2(tanh_table1_q2),
    .address3(tanh_table1_address3),
    .ce3(tanh_table1_ce3),
    .q3(tanh_table1_q3),
    .address4(tanh_table1_address4),
    .ce4(tanh_table1_ce4),
    .q4(tanh_table1_q4),
    .address5(tanh_table1_address5),
    .ce5(tanh_table1_ce5),
    .q5(tanh_table1_q5),
    .address6(tanh_table1_address6),
    .ce6(tanh_table1_ce6),
    .q6(tanh_table1_q6),
    .address7(tanh_table1_address7),
    .ce7(tanh_table1_ce7),
    .q7(tanh_table1_q7),
    .address8(tanh_table1_address8),
    .ce8(tanh_table1_ce8),
    .q8(tanh_table1_q8),
    .address9(tanh_table1_address9),
    .ce9(tanh_table1_ce9),
    .q9(tanh_table1_q9),
    .address10(tanh_table1_address10),
    .ce10(tanh_table1_ce10),
    .q10(tanh_table1_q10),
    .address11(tanh_table1_address11),
    .ce11(tanh_table1_ce11),
    .q11(tanh_table1_q11),
    .address12(tanh_table1_address12),
    .ce12(tanh_table1_ce12),
    .q12(tanh_table1_q12),
    .address13(tanh_table1_address13),
    .ce13(tanh_table1_ce13),
    .q13(tanh_table1_q13),
    .address14(tanh_table1_address14),
    .ce14(tanh_table1_ce14),
    .q14(tanh_table1_q14),
    .address15(tanh_table1_address15),
    .ce15(tanh_table1_ce15),
    .q15(tanh_table1_q15),
    .address16(tanh_table1_address16),
    .ce16(tanh_table1_ce16),
    .q16(tanh_table1_q16),
    .address17(tanh_table1_address17),
    .ce17(tanh_table1_ce17),
    .q17(tanh_table1_q17),
    .address18(tanh_table1_address18),
    .ce18(tanh_table1_ce18),
    .q18(tanh_table1_q18),
    .address19(tanh_table1_address19),
    .ce19(tanh_table1_ce19),
    .q19(tanh_table1_q19)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln476_10_reg_3519 <= select_ln476_10_fu_1869_p3;
        select_ln476_11_reg_3524 <= select_ln476_11_fu_1997_p3;
        select_ln476_12_reg_3529 <= select_ln476_12_fu_2125_p3;
        select_ln476_13_reg_3534 <= select_ln476_13_fu_2253_p3;
        select_ln476_14_reg_3539 <= select_ln476_14_fu_2381_p3;
        select_ln476_15_reg_3544 <= select_ln476_15_fu_2509_p3;
        select_ln476_16_reg_3549 <= select_ln476_16_fu_2637_p3;
        select_ln476_17_reg_3554 <= select_ln476_17_fu_2765_p3;
        select_ln476_18_reg_3559 <= select_ln476_18_fu_2893_p3;
        select_ln476_19_reg_3564 <= select_ln476_19_fu_3021_p3;
        select_ln476_1_reg_3474 <= select_ln476_1_fu_717_p3;
        select_ln476_2_reg_3479 <= select_ln476_2_fu_845_p3;
        select_ln476_3_reg_3484 <= select_ln476_3_fu_973_p3;
        select_ln476_4_reg_3489 <= select_ln476_4_fu_1101_p3;
        select_ln476_5_reg_3494 <= select_ln476_5_fu_1229_p3;
        select_ln476_6_reg_3499 <= select_ln476_6_fu_1357_p3;
        select_ln476_7_reg_3504 <= select_ln476_7_fu_1485_p3;
        select_ln476_8_reg_3509 <= select_ln476_8_fu_1613_p3;
        select_ln476_9_reg_3514 <= select_ln476_9_fu_1741_p3;
        select_ln476_reg_3469 <= select_ln476_fu_589_p3;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce0 = 1'b1;
    end else begin
        tanh_table1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce1 = 1'b1;
    end else begin
        tanh_table1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce10 = 1'b1;
    end else begin
        tanh_table1_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce11 = 1'b1;
    end else begin
        tanh_table1_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce12 = 1'b1;
    end else begin
        tanh_table1_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce13 = 1'b1;
    end else begin
        tanh_table1_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce14 = 1'b1;
    end else begin
        tanh_table1_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce15 = 1'b1;
    end else begin
        tanh_table1_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce16 = 1'b1;
    end else begin
        tanh_table1_ce16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce17 = 1'b1;
    end else begin
        tanh_table1_ce17 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce18 = 1'b1;
    end else begin
        tanh_table1_ce18 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce19 = 1'b1;
    end else begin
        tanh_table1_ce19 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce2 = 1'b1;
    end else begin
        tanh_table1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce3 = 1'b1;
    end else begin
        tanh_table1_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce4 = 1'b1;
    end else begin
        tanh_table1_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce5 = 1'b1;
    end else begin
        tanh_table1_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce6 = 1'b1;
    end else begin
        tanh_table1_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce7 = 1'b1;
    end else begin
        tanh_table1_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce8 = 1'b1;
    end else begin
        tanh_table1_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table1_ce9 = 1'b1;
    end else begin
        tanh_table1_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln473_10_fu_1821_p2 = (16'd512 + select_ln850_10_fu_1809_p3);

assign add_ln473_11_fu_1949_p2 = (16'd512 + select_ln850_11_fu_1937_p3);

assign add_ln473_12_fu_2077_p2 = (16'd512 + select_ln850_12_fu_2065_p3);

assign add_ln473_13_fu_2205_p2 = (16'd512 + select_ln850_13_fu_2193_p3);

assign add_ln473_14_fu_2333_p2 = (16'd512 + select_ln850_14_fu_2321_p3);

assign add_ln473_15_fu_2461_p2 = (16'd512 + select_ln850_15_fu_2449_p3);

assign add_ln473_16_fu_2589_p2 = (16'd512 + select_ln850_16_fu_2577_p3);

assign add_ln473_17_fu_2717_p2 = (16'd512 + select_ln850_17_fu_2705_p3);

assign add_ln473_18_fu_2845_p2 = (16'd512 + select_ln850_18_fu_2833_p3);

assign add_ln473_19_fu_2973_p2 = (16'd512 + select_ln850_19_fu_2961_p3);

assign add_ln473_1_fu_669_p2 = (16'd512 + select_ln850_1_fu_657_p3);

assign add_ln473_20_fu_547_p2 = (15'd512 + trunc_ln473_fu_537_p1);

assign add_ln473_21_fu_675_p2 = (15'd512 + trunc_ln473_1_fu_665_p1);

assign add_ln473_22_fu_803_p2 = (15'd512 + trunc_ln473_2_fu_793_p1);

assign add_ln473_23_fu_931_p2 = (15'd512 + trunc_ln473_3_fu_921_p1);

assign add_ln473_24_fu_1059_p2 = (15'd512 + trunc_ln473_4_fu_1049_p1);

assign add_ln473_25_fu_1187_p2 = (15'd512 + trunc_ln473_5_fu_1177_p1);

assign add_ln473_26_fu_1315_p2 = (15'd512 + trunc_ln473_6_fu_1305_p1);

assign add_ln473_27_fu_1443_p2 = (15'd512 + trunc_ln473_7_fu_1433_p1);

assign add_ln473_28_fu_1571_p2 = (15'd512 + trunc_ln473_8_fu_1561_p1);

assign add_ln473_29_fu_1699_p2 = (15'd512 + trunc_ln473_9_fu_1689_p1);

assign add_ln473_2_fu_797_p2 = (16'd512 + select_ln850_2_fu_785_p3);

assign add_ln473_30_fu_1827_p2 = (15'd512 + trunc_ln473_10_fu_1817_p1);

assign add_ln473_31_fu_1955_p2 = (15'd512 + trunc_ln473_11_fu_1945_p1);

assign add_ln473_32_fu_2083_p2 = (15'd512 + trunc_ln473_12_fu_2073_p1);

assign add_ln473_33_fu_2211_p2 = (15'd512 + trunc_ln473_13_fu_2201_p1);

assign add_ln473_34_fu_2339_p2 = (15'd512 + trunc_ln473_14_fu_2329_p1);

assign add_ln473_35_fu_2467_p2 = (15'd512 + trunc_ln473_15_fu_2457_p1);

assign add_ln473_36_fu_2595_p2 = (15'd512 + trunc_ln473_16_fu_2585_p1);

assign add_ln473_37_fu_2723_p2 = (15'd512 + trunc_ln473_17_fu_2713_p1);

assign add_ln473_38_fu_2851_p2 = (15'd512 + trunc_ln473_18_fu_2841_p1);

assign add_ln473_39_fu_2979_p2 = (15'd512 + trunc_ln473_19_fu_2969_p1);

assign add_ln473_3_fu_925_p2 = (16'd512 + select_ln850_3_fu_913_p3);

assign add_ln473_4_fu_1053_p2 = (16'd512 + select_ln850_4_fu_1041_p3);

assign add_ln473_5_fu_1181_p2 = (16'd512 + select_ln850_5_fu_1169_p3);

assign add_ln473_6_fu_1309_p2 = (16'd512 + select_ln850_6_fu_1297_p3);

assign add_ln473_7_fu_1437_p2 = (16'd512 + select_ln850_7_fu_1425_p3);

assign add_ln473_8_fu_1565_p2 = (16'd512 + select_ln850_8_fu_1553_p3);

assign add_ln473_9_fu_1693_p2 = (16'd512 + select_ln850_9_fu_1681_p3);

assign add_ln473_fu_541_p2 = (16'd512 + select_ln850_fu_529_p3);

assign add_ln700_10_fu_1795_p2 = ($signed(16'd1) + $signed(sext_ln850_10_fu_1767_p1));

assign add_ln700_11_fu_1923_p2 = ($signed(16'd1) + $signed(sext_ln850_11_fu_1895_p1));

assign add_ln700_12_fu_2051_p2 = ($signed(16'd1) + $signed(sext_ln850_12_fu_2023_p1));

assign add_ln700_13_fu_2179_p2 = ($signed(16'd1) + $signed(sext_ln850_13_fu_2151_p1));

assign add_ln700_14_fu_2307_p2 = ($signed(16'd1) + $signed(sext_ln850_14_fu_2279_p1));

assign add_ln700_15_fu_2435_p2 = ($signed(16'd1) + $signed(sext_ln850_15_fu_2407_p1));

assign add_ln700_16_fu_2563_p2 = ($signed(16'd1) + $signed(sext_ln850_16_fu_2535_p1));

assign add_ln700_17_fu_2691_p2 = ($signed(16'd1) + $signed(sext_ln850_17_fu_2663_p1));

assign add_ln700_18_fu_2819_p2 = ($signed(16'd1) + $signed(sext_ln850_18_fu_2791_p1));

assign add_ln700_19_fu_2947_p2 = ($signed(16'd1) + $signed(sext_ln850_19_fu_2919_p1));

assign add_ln700_1_fu_643_p2 = ($signed(16'd1) + $signed(sext_ln850_1_fu_615_p1));

assign add_ln700_2_fu_771_p2 = ($signed(16'd1) + $signed(sext_ln850_2_fu_743_p1));

assign add_ln700_3_fu_899_p2 = ($signed(16'd1) + $signed(sext_ln850_3_fu_871_p1));

assign add_ln700_4_fu_1027_p2 = ($signed(16'd1) + $signed(sext_ln850_4_fu_999_p1));

assign add_ln700_5_fu_1155_p2 = ($signed(16'd1) + $signed(sext_ln850_5_fu_1127_p1));

assign add_ln700_6_fu_1283_p2 = ($signed(16'd1) + $signed(sext_ln850_6_fu_1255_p1));

assign add_ln700_7_fu_1411_p2 = ($signed(16'd1) + $signed(sext_ln850_7_fu_1383_p1));

assign add_ln700_8_fu_1539_p2 = ($signed(16'd1) + $signed(sext_ln850_8_fu_1511_p1));

assign add_ln700_9_fu_1667_p2 = ($signed(16'd1) + $signed(sext_ln850_9_fu_1639_p1));

assign add_ln700_fu_515_p2 = ($signed(16'd1) + $signed(sext_ln850_fu_487_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln728_fu_3117_p1;

assign ap_return_1 = sext_ln728_1_fu_3129_p1;

assign ap_return_10 = sext_ln728_10_fu_3237_p1;

assign ap_return_11 = sext_ln728_11_fu_3249_p1;

assign ap_return_12 = sext_ln728_12_fu_3261_p1;

assign ap_return_13 = sext_ln728_13_fu_3273_p1;

assign ap_return_14 = sext_ln728_14_fu_3285_p1;

assign ap_return_15 = sext_ln728_15_fu_3297_p1;

assign ap_return_16 = sext_ln728_16_fu_3309_p1;

assign ap_return_17 = sext_ln728_17_fu_3321_p1;

assign ap_return_18 = sext_ln728_18_fu_3333_p1;

assign ap_return_19 = sext_ln728_19_fu_3345_p1;

assign ap_return_2 = sext_ln728_2_fu_3141_p1;

assign ap_return_3 = sext_ln728_3_fu_3153_p1;

assign ap_return_4 = sext_ln728_4_fu_3165_p1;

assign ap_return_5 = sext_ln728_5_fu_3177_p1;

assign ap_return_6 = sext_ln728_6_fu_3189_p1;

assign ap_return_7 = sext_ln728_7_fu_3201_p1;

assign ap_return_8 = sext_ln728_8_fu_3213_p1;

assign ap_return_9 = sext_ln728_9_fu_3225_p1;

assign icmp_ln476_10_fu_1863_p2 = ((tmp_61_fu_1853_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_11_fu_1991_p2 = ((tmp_63_fu_1981_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_12_fu_2119_p2 = ((tmp_65_fu_2109_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_13_fu_2247_p2 = ((tmp_67_fu_2237_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_14_fu_2375_p2 = ((tmp_69_fu_2365_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_15_fu_2503_p2 = ((tmp_71_fu_2493_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_16_fu_2631_p2 = ((tmp_73_fu_2621_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_17_fu_2759_p2 = ((tmp_75_fu_2749_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_18_fu_2887_p2 = ((tmp_77_fu_2877_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_19_fu_3015_p2 = ((tmp_79_fu_3005_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_1_fu_711_p2 = ((tmp_8_fu_701_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_2_fu_839_p2 = ((tmp_15_fu_829_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_3_fu_967_p2 = ((tmp_21_fu_957_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_4_fu_1095_p2 = ((tmp_27_fu_1085_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_5_fu_1223_p2 = ((tmp_33_fu_1213_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_6_fu_1351_p2 = ((tmp_39_fu_1341_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_7_fu_1479_p2 = ((tmp_42_fu_1469_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_8_fu_1607_p2 = ((tmp_45_fu_1597_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_9_fu_1735_p2 = ((tmp_48_fu_1725_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_fu_583_p2 = ((tmp_4_fu_573_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln850_10_fu_1771_p2 = (($signed(shl_ln1118_s_fu_1749_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_11_fu_1899_p2 = (($signed(shl_ln1118_10_fu_1877_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_12_fu_2027_p2 = (($signed(shl_ln1118_11_fu_2005_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_13_fu_2155_p2 = (($signed(shl_ln1118_12_fu_2133_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_14_fu_2283_p2 = (($signed(shl_ln1118_13_fu_2261_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_15_fu_2411_p2 = (($signed(shl_ln1118_14_fu_2389_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_16_fu_2539_p2 = (($signed(shl_ln1118_15_fu_2517_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_17_fu_2667_p2 = (($signed(shl_ln1118_16_fu_2645_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_18_fu_2795_p2 = (($signed(shl_ln1118_17_fu_2773_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_19_fu_2923_p2 = (($signed(shl_ln1118_18_fu_2901_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_1_fu_619_p2 = (($signed(shl_ln1118_1_fu_597_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_2_fu_747_p2 = (($signed(shl_ln1118_2_fu_725_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_3_fu_875_p2 = (($signed(shl_ln1118_3_fu_853_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_4_fu_1003_p2 = (($signed(shl_ln1118_4_fu_981_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_5_fu_1131_p2 = (($signed(shl_ln1118_5_fu_1109_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_6_fu_1259_p2 = (($signed(shl_ln1118_6_fu_1237_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_7_fu_1387_p2 = (($signed(shl_ln1118_7_fu_1365_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_8_fu_1515_p2 = (($signed(shl_ln1118_8_fu_1493_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_9_fu_1643_p2 = (($signed(shl_ln1118_9_fu_1621_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln850_fu_491_p2 = (($signed(shl_ln_fu_469_p3) < $signed(34'd17179869177)) ? 1'b1 : 1'b0);

assign icmp_ln851_10_fu_1789_p2 = ((p_Result_2_s_fu_1781_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_11_fu_1917_p2 = ((p_Result_2_10_fu_1909_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_12_fu_2045_p2 = ((p_Result_2_11_fu_2037_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_13_fu_2173_p2 = ((p_Result_2_12_fu_2165_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_14_fu_2301_p2 = ((p_Result_2_13_fu_2293_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_15_fu_2429_p2 = ((p_Result_2_14_fu_2421_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_16_fu_2557_p2 = ((p_Result_2_15_fu_2549_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_17_fu_2685_p2 = ((p_Result_2_16_fu_2677_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_18_fu_2813_p2 = ((p_Result_2_17_fu_2805_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_19_fu_2941_p2 = ((p_Result_2_18_fu_2933_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_1_fu_637_p2 = ((p_Result_2_1_fu_629_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_2_fu_765_p2 = ((p_Result_2_2_fu_757_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_3_fu_893_p2 = ((p_Result_2_3_fu_885_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_4_fu_1021_p2 = ((p_Result_2_4_fu_1013_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_5_fu_1149_p2 = ((p_Result_2_5_fu_1141_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_6_fu_1277_p2 = ((p_Result_2_6_fu_1269_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_7_fu_1405_p2 = ((p_Result_2_7_fu_1397_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_8_fu_1533_p2 = ((p_Result_2_8_fu_1525_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_9_fu_1661_p2 = ((p_Result_2_9_fu_1653_p3 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_fu_509_p2 = ((p_Result_2_fu_501_p3 == 16'd0) ? 1'b1 : 1'b0);

assign p_Result_2_10_fu_1909_p3 = {{trunc_ln851_11_fu_1905_p1}, {7'd0}};

assign p_Result_2_11_fu_2037_p3 = {{trunc_ln851_12_fu_2033_p1}, {7'd0}};

assign p_Result_2_12_fu_2165_p3 = {{trunc_ln851_13_fu_2161_p1}, {7'd0}};

assign p_Result_2_13_fu_2293_p3 = {{trunc_ln851_14_fu_2289_p1}, {7'd0}};

assign p_Result_2_14_fu_2421_p3 = {{trunc_ln851_15_fu_2417_p1}, {7'd0}};

assign p_Result_2_15_fu_2549_p3 = {{trunc_ln851_16_fu_2545_p1}, {7'd0}};

assign p_Result_2_16_fu_2677_p3 = {{trunc_ln851_17_fu_2673_p1}, {7'd0}};

assign p_Result_2_17_fu_2805_p3 = {{trunc_ln851_18_fu_2801_p1}, {7'd0}};

assign p_Result_2_18_fu_2933_p3 = {{trunc_ln851_19_fu_2929_p1}, {7'd0}};

assign p_Result_2_1_fu_629_p3 = {{trunc_ln851_1_fu_625_p1}, {7'd0}};

assign p_Result_2_2_fu_757_p3 = {{trunc_ln851_2_fu_753_p1}, {7'd0}};

assign p_Result_2_3_fu_885_p3 = {{trunc_ln851_3_fu_881_p1}, {7'd0}};

assign p_Result_2_4_fu_1013_p3 = {{trunc_ln851_4_fu_1009_p1}, {7'd0}};

assign p_Result_2_5_fu_1141_p3 = {{trunc_ln851_5_fu_1137_p1}, {7'd0}};

assign p_Result_2_6_fu_1269_p3 = {{trunc_ln851_6_fu_1265_p1}, {7'd0}};

assign p_Result_2_7_fu_1397_p3 = {{trunc_ln851_7_fu_1393_p1}, {7'd0}};

assign p_Result_2_8_fu_1525_p3 = {{trunc_ln851_8_fu_1521_p1}, {7'd0}};

assign p_Result_2_9_fu_1653_p3 = {{trunc_ln851_9_fu_1649_p1}, {7'd0}};

assign p_Result_2_fu_501_p3 = {{trunc_ln851_fu_497_p1}, {7'd0}};

assign p_Result_2_s_fu_1781_p3 = {{trunc_ln851_10_fu_1777_p1}, {7'd0}};

assign select_ln475_10_fu_1841_p3 = ((tmp_60_fu_1833_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_30_fu_1827_p2);

assign select_ln475_11_fu_1969_p3 = ((tmp_62_fu_1961_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_31_fu_1955_p2);

assign select_ln475_12_fu_2097_p3 = ((tmp_64_fu_2089_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_32_fu_2083_p2);

assign select_ln475_13_fu_2225_p3 = ((tmp_66_fu_2217_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_33_fu_2211_p2);

assign select_ln475_14_fu_2353_p3 = ((tmp_68_fu_2345_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_34_fu_2339_p2);

assign select_ln475_15_fu_2481_p3 = ((tmp_70_fu_2473_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_35_fu_2467_p2);

assign select_ln475_16_fu_2609_p3 = ((tmp_72_fu_2601_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_36_fu_2595_p2);

assign select_ln475_17_fu_2737_p3 = ((tmp_74_fu_2729_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_37_fu_2723_p2);

assign select_ln475_18_fu_2865_p3 = ((tmp_76_fu_2857_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_38_fu_2851_p2);

assign select_ln475_19_fu_2993_p3 = ((tmp_78_fu_2985_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_39_fu_2979_p2);

assign select_ln475_1_fu_689_p3 = ((tmp_6_fu_681_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_21_fu_675_p2);

assign select_ln475_2_fu_817_p3 = ((tmp_13_fu_809_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_22_fu_803_p2);

assign select_ln475_3_fu_945_p3 = ((tmp_19_fu_937_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_23_fu_931_p2);

assign select_ln475_4_fu_1073_p3 = ((tmp_25_fu_1065_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_24_fu_1059_p2);

assign select_ln475_5_fu_1201_p3 = ((tmp_31_fu_1193_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_25_fu_1187_p2);

assign select_ln475_6_fu_1329_p3 = ((tmp_37_fu_1321_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_26_fu_1315_p2);

assign select_ln475_7_fu_1457_p3 = ((tmp_41_fu_1449_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_27_fu_1443_p2);

assign select_ln475_8_fu_1585_p3 = ((tmp_44_fu_1577_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_28_fu_1571_p2);

assign select_ln475_9_fu_1713_p3 = ((tmp_47_fu_1705_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_29_fu_1699_p2);

assign select_ln475_fu_561_p3 = ((tmp_2_fu_553_p3[0:0] === 1'b1) ? 15'd0 : add_ln473_20_fu_547_p2);

assign select_ln476_10_fu_1869_p3 = ((icmp_ln476_10_fu_1863_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_10_fu_1849_p1);

assign select_ln476_11_fu_1997_p3 = ((icmp_ln476_11_fu_1991_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_11_fu_1977_p1);

assign select_ln476_12_fu_2125_p3 = ((icmp_ln476_12_fu_2119_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_12_fu_2105_p1);

assign select_ln476_13_fu_2253_p3 = ((icmp_ln476_13_fu_2247_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_13_fu_2233_p1);

assign select_ln476_14_fu_2381_p3 = ((icmp_ln476_14_fu_2375_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_14_fu_2361_p1);

assign select_ln476_15_fu_2509_p3 = ((icmp_ln476_15_fu_2503_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_15_fu_2489_p1);

assign select_ln476_16_fu_2637_p3 = ((icmp_ln476_16_fu_2631_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_16_fu_2617_p1);

assign select_ln476_17_fu_2765_p3 = ((icmp_ln476_17_fu_2759_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_17_fu_2745_p1);

assign select_ln476_18_fu_2893_p3 = ((icmp_ln476_18_fu_2887_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_18_fu_2873_p1);

assign select_ln476_19_fu_3021_p3 = ((icmp_ln476_19_fu_3015_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_19_fu_3001_p1);

assign select_ln476_1_fu_717_p3 = ((icmp_ln476_1_fu_711_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_1_fu_697_p1);

assign select_ln476_2_fu_845_p3 = ((icmp_ln476_2_fu_839_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_2_fu_825_p1);

assign select_ln476_3_fu_973_p3 = ((icmp_ln476_3_fu_967_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_3_fu_953_p1);

assign select_ln476_4_fu_1101_p3 = ((icmp_ln476_4_fu_1095_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_4_fu_1081_p1);

assign select_ln476_5_fu_1229_p3 = ((icmp_ln476_5_fu_1223_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_5_fu_1209_p1);

assign select_ln476_6_fu_1357_p3 = ((icmp_ln476_6_fu_1351_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_6_fu_1337_p1);

assign select_ln476_7_fu_1485_p3 = ((icmp_ln476_7_fu_1479_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_7_fu_1465_p1);

assign select_ln476_8_fu_1613_p3 = ((icmp_ln476_8_fu_1607_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_8_fu_1593_p1);

assign select_ln476_9_fu_1741_p3 = ((icmp_ln476_9_fu_1735_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_9_fu_1721_p1);

assign select_ln476_fu_589_p3 = ((icmp_ln476_fu_583_p2[0:0] === 1'b1) ? 10'd1023 : trunc_ln475_fu_569_p1);

assign select_ln850_10_fu_1809_p3 = ((icmp_ln850_10_fu_1771_p2[0:0] === 1'b1) ? select_ln851_10_fu_1801_p3 : sext_ln850_10_fu_1767_p1);

assign select_ln850_11_fu_1937_p3 = ((icmp_ln850_11_fu_1899_p2[0:0] === 1'b1) ? select_ln851_11_fu_1929_p3 : sext_ln850_11_fu_1895_p1);

assign select_ln850_12_fu_2065_p3 = ((icmp_ln850_12_fu_2027_p2[0:0] === 1'b1) ? select_ln851_12_fu_2057_p3 : sext_ln850_12_fu_2023_p1);

assign select_ln850_13_fu_2193_p3 = ((icmp_ln850_13_fu_2155_p2[0:0] === 1'b1) ? select_ln851_13_fu_2185_p3 : sext_ln850_13_fu_2151_p1);

assign select_ln850_14_fu_2321_p3 = ((icmp_ln850_14_fu_2283_p2[0:0] === 1'b1) ? select_ln851_14_fu_2313_p3 : sext_ln850_14_fu_2279_p1);

assign select_ln850_15_fu_2449_p3 = ((icmp_ln850_15_fu_2411_p2[0:0] === 1'b1) ? select_ln851_15_fu_2441_p3 : sext_ln850_15_fu_2407_p1);

assign select_ln850_16_fu_2577_p3 = ((icmp_ln850_16_fu_2539_p2[0:0] === 1'b1) ? select_ln851_16_fu_2569_p3 : sext_ln850_16_fu_2535_p1);

assign select_ln850_17_fu_2705_p3 = ((icmp_ln850_17_fu_2667_p2[0:0] === 1'b1) ? select_ln851_17_fu_2697_p3 : sext_ln850_17_fu_2663_p1);

assign select_ln850_18_fu_2833_p3 = ((icmp_ln850_18_fu_2795_p2[0:0] === 1'b1) ? select_ln851_18_fu_2825_p3 : sext_ln850_18_fu_2791_p1);

assign select_ln850_19_fu_2961_p3 = ((icmp_ln850_19_fu_2923_p2[0:0] === 1'b1) ? select_ln851_19_fu_2953_p3 : sext_ln850_19_fu_2919_p1);

assign select_ln850_1_fu_657_p3 = ((icmp_ln850_1_fu_619_p2[0:0] === 1'b1) ? select_ln851_1_fu_649_p3 : sext_ln850_1_fu_615_p1);

assign select_ln850_2_fu_785_p3 = ((icmp_ln850_2_fu_747_p2[0:0] === 1'b1) ? select_ln851_2_fu_777_p3 : sext_ln850_2_fu_743_p1);

assign select_ln850_3_fu_913_p3 = ((icmp_ln850_3_fu_875_p2[0:0] === 1'b1) ? select_ln851_3_fu_905_p3 : sext_ln850_3_fu_871_p1);

assign select_ln850_4_fu_1041_p3 = ((icmp_ln850_4_fu_1003_p2[0:0] === 1'b1) ? select_ln851_4_fu_1033_p3 : sext_ln850_4_fu_999_p1);

assign select_ln850_5_fu_1169_p3 = ((icmp_ln850_5_fu_1131_p2[0:0] === 1'b1) ? select_ln851_5_fu_1161_p3 : sext_ln850_5_fu_1127_p1);

assign select_ln850_6_fu_1297_p3 = ((icmp_ln850_6_fu_1259_p2[0:0] === 1'b1) ? select_ln851_6_fu_1289_p3 : sext_ln850_6_fu_1255_p1);

assign select_ln850_7_fu_1425_p3 = ((icmp_ln850_7_fu_1387_p2[0:0] === 1'b1) ? select_ln851_7_fu_1417_p3 : sext_ln850_7_fu_1383_p1);

assign select_ln850_8_fu_1553_p3 = ((icmp_ln850_8_fu_1515_p2[0:0] === 1'b1) ? select_ln851_8_fu_1545_p3 : sext_ln850_8_fu_1511_p1);

assign select_ln850_9_fu_1681_p3 = ((icmp_ln850_9_fu_1643_p2[0:0] === 1'b1) ? select_ln851_9_fu_1673_p3 : sext_ln850_9_fu_1639_p1);

assign select_ln850_fu_529_p3 = ((icmp_ln850_fu_491_p2[0:0] === 1'b1) ? select_ln851_fu_521_p3 : sext_ln850_fu_487_p1);

assign select_ln851_10_fu_1801_p3 = ((icmp_ln851_10_fu_1789_p2[0:0] === 1'b1) ? sext_ln850_10_fu_1767_p1 : add_ln700_10_fu_1795_p2);

assign select_ln851_11_fu_1929_p3 = ((icmp_ln851_11_fu_1917_p2[0:0] === 1'b1) ? sext_ln850_11_fu_1895_p1 : add_ln700_11_fu_1923_p2);

assign select_ln851_12_fu_2057_p3 = ((icmp_ln851_12_fu_2045_p2[0:0] === 1'b1) ? sext_ln850_12_fu_2023_p1 : add_ln700_12_fu_2051_p2);

assign select_ln851_13_fu_2185_p3 = ((icmp_ln851_13_fu_2173_p2[0:0] === 1'b1) ? sext_ln850_13_fu_2151_p1 : add_ln700_13_fu_2179_p2);

assign select_ln851_14_fu_2313_p3 = ((icmp_ln851_14_fu_2301_p2[0:0] === 1'b1) ? sext_ln850_14_fu_2279_p1 : add_ln700_14_fu_2307_p2);

assign select_ln851_15_fu_2441_p3 = ((icmp_ln851_15_fu_2429_p2[0:0] === 1'b1) ? sext_ln850_15_fu_2407_p1 : add_ln700_15_fu_2435_p2);

assign select_ln851_16_fu_2569_p3 = ((icmp_ln851_16_fu_2557_p2[0:0] === 1'b1) ? sext_ln850_16_fu_2535_p1 : add_ln700_16_fu_2563_p2);

assign select_ln851_17_fu_2697_p3 = ((icmp_ln851_17_fu_2685_p2[0:0] === 1'b1) ? sext_ln850_17_fu_2663_p1 : add_ln700_17_fu_2691_p2);

assign select_ln851_18_fu_2825_p3 = ((icmp_ln851_18_fu_2813_p2[0:0] === 1'b1) ? sext_ln850_18_fu_2791_p1 : add_ln700_18_fu_2819_p2);

assign select_ln851_19_fu_2953_p3 = ((icmp_ln851_19_fu_2941_p2[0:0] === 1'b1) ? sext_ln850_19_fu_2919_p1 : add_ln700_19_fu_2947_p2);

assign select_ln851_1_fu_649_p3 = ((icmp_ln851_1_fu_637_p2[0:0] === 1'b1) ? sext_ln850_1_fu_615_p1 : add_ln700_1_fu_643_p2);

assign select_ln851_2_fu_777_p3 = ((icmp_ln851_2_fu_765_p2[0:0] === 1'b1) ? sext_ln850_2_fu_743_p1 : add_ln700_2_fu_771_p2);

assign select_ln851_3_fu_905_p3 = ((icmp_ln851_3_fu_893_p2[0:0] === 1'b1) ? sext_ln850_3_fu_871_p1 : add_ln700_3_fu_899_p2);

assign select_ln851_4_fu_1033_p3 = ((icmp_ln851_4_fu_1021_p2[0:0] === 1'b1) ? sext_ln850_4_fu_999_p1 : add_ln700_4_fu_1027_p2);

assign select_ln851_5_fu_1161_p3 = ((icmp_ln851_5_fu_1149_p2[0:0] === 1'b1) ? sext_ln850_5_fu_1127_p1 : add_ln700_5_fu_1155_p2);

assign select_ln851_6_fu_1289_p3 = ((icmp_ln851_6_fu_1277_p2[0:0] === 1'b1) ? sext_ln850_6_fu_1255_p1 : add_ln700_6_fu_1283_p2);

assign select_ln851_7_fu_1417_p3 = ((icmp_ln851_7_fu_1405_p2[0:0] === 1'b1) ? sext_ln850_7_fu_1383_p1 : add_ln700_7_fu_1411_p2);

assign select_ln851_8_fu_1545_p3 = ((icmp_ln851_8_fu_1533_p2[0:0] === 1'b1) ? sext_ln850_8_fu_1511_p1 : add_ln700_8_fu_1539_p2);

assign select_ln851_9_fu_1673_p3 = ((icmp_ln851_9_fu_1661_p2[0:0] === 1'b1) ? sext_ln850_9_fu_1639_p1 : add_ln700_9_fu_1667_p2);

assign select_ln851_fu_521_p3 = ((icmp_ln851_fu_509_p2[0:0] === 1'b1) ? sext_ln850_fu_487_p1 : add_ln700_fu_515_p2);

assign sext_ln728_10_fu_3237_p1 = $signed(tmp_50_fu_3229_p3);

assign sext_ln728_11_fu_3249_p1 = $signed(tmp_51_fu_3241_p3);

assign sext_ln728_12_fu_3261_p1 = $signed(tmp_52_fu_3253_p3);

assign sext_ln728_13_fu_3273_p1 = $signed(tmp_53_fu_3265_p3);

assign sext_ln728_14_fu_3285_p1 = $signed(tmp_54_fu_3277_p3);

assign sext_ln728_15_fu_3297_p1 = $signed(tmp_55_fu_3289_p3);

assign sext_ln728_16_fu_3309_p1 = $signed(tmp_56_fu_3301_p3);

assign sext_ln728_17_fu_3321_p1 = $signed(tmp_57_fu_3313_p3);

assign sext_ln728_18_fu_3333_p1 = $signed(tmp_58_fu_3325_p3);

assign sext_ln728_19_fu_3345_p1 = $signed(tmp_59_fu_3337_p3);

assign sext_ln728_1_fu_3129_p1 = $signed(tmp_11_fu_3121_p3);

assign sext_ln728_2_fu_3141_p1 = $signed(tmp_17_fu_3133_p3);

assign sext_ln728_3_fu_3153_p1 = $signed(tmp_23_fu_3145_p3);

assign sext_ln728_4_fu_3165_p1 = $signed(tmp_29_fu_3157_p3);

assign sext_ln728_5_fu_3177_p1 = $signed(tmp_35_fu_3169_p3);

assign sext_ln728_6_fu_3189_p1 = $signed(tmp_40_fu_3181_p3);

assign sext_ln728_7_fu_3201_p1 = $signed(tmp_43_fu_3193_p3);

assign sext_ln728_8_fu_3213_p1 = $signed(tmp_46_fu_3205_p3);

assign sext_ln728_9_fu_3225_p1 = $signed(tmp_49_fu_3217_p3);

assign sext_ln728_fu_3117_p1 = $signed(tmp_s_fu_3109_p3);

assign sext_ln850_10_fu_1767_p1 = $signed(tmp_20_fu_1757_p4);

assign sext_ln850_11_fu_1895_p1 = $signed(tmp_22_fu_1885_p4);

assign sext_ln850_12_fu_2023_p1 = $signed(tmp_24_fu_2013_p4);

assign sext_ln850_13_fu_2151_p1 = $signed(tmp_26_fu_2141_p4);

assign sext_ln850_14_fu_2279_p1 = $signed(tmp_28_fu_2269_p4);

assign sext_ln850_15_fu_2407_p1 = $signed(tmp_30_fu_2397_p4);

assign sext_ln850_16_fu_2535_p1 = $signed(tmp_32_fu_2525_p4);

assign sext_ln850_17_fu_2663_p1 = $signed(tmp_34_fu_2653_p4);

assign sext_ln850_18_fu_2791_p1 = $signed(tmp_36_fu_2781_p4);

assign sext_ln850_19_fu_2919_p1 = $signed(tmp_38_fu_2909_p4);

assign sext_ln850_1_fu_615_p1 = $signed(tmp_3_fu_605_p4);

assign sext_ln850_2_fu_743_p1 = $signed(tmp_5_fu_733_p4);

assign sext_ln850_3_fu_871_p1 = $signed(tmp_7_fu_861_p4);

assign sext_ln850_4_fu_999_p1 = $signed(tmp_9_fu_989_p4);

assign sext_ln850_5_fu_1127_p1 = $signed(tmp_10_fu_1117_p4);

assign sext_ln850_6_fu_1255_p1 = $signed(tmp_12_fu_1245_p4);

assign sext_ln850_7_fu_1383_p1 = $signed(tmp_14_fu_1373_p4);

assign sext_ln850_8_fu_1511_p1 = $signed(tmp_16_fu_1501_p4);

assign sext_ln850_9_fu_1639_p1 = $signed(tmp_18_fu_1629_p4);

assign sext_ln850_fu_487_p1 = $signed(tmp_1_fu_477_p4);

assign shl_ln1118_10_fu_1877_p3 = {{data_11_V_read}, {10'd0}};

assign shl_ln1118_11_fu_2005_p3 = {{data_12_V_read}, {10'd0}};

assign shl_ln1118_12_fu_2133_p3 = {{data_13_V_read}, {10'd0}};

assign shl_ln1118_13_fu_2261_p3 = {{data_14_V_read}, {10'd0}};

assign shl_ln1118_14_fu_2389_p3 = {{data_15_V_read}, {10'd0}};

assign shl_ln1118_15_fu_2517_p3 = {{data_16_V_read}, {10'd0}};

assign shl_ln1118_16_fu_2645_p3 = {{data_17_V_read}, {10'd0}};

assign shl_ln1118_17_fu_2773_p3 = {{data_18_V_read}, {10'd0}};

assign shl_ln1118_18_fu_2901_p3 = {{data_19_V_read}, {10'd0}};

assign shl_ln1118_1_fu_597_p3 = {{data_1_V_read}, {10'd0}};

assign shl_ln1118_2_fu_725_p3 = {{data_2_V_read}, {10'd0}};

assign shl_ln1118_3_fu_853_p3 = {{data_3_V_read}, {10'd0}};

assign shl_ln1118_4_fu_981_p3 = {{data_4_V_read}, {10'd0}};

assign shl_ln1118_5_fu_1109_p3 = {{data_5_V_read}, {10'd0}};

assign shl_ln1118_6_fu_1237_p3 = {{data_6_V_read}, {10'd0}};

assign shl_ln1118_7_fu_1365_p3 = {{data_7_V_read}, {10'd0}};

assign shl_ln1118_8_fu_1493_p3 = {{data_8_V_read}, {10'd0}};

assign shl_ln1118_9_fu_1621_p3 = {{data_9_V_read}, {10'd0}};

assign shl_ln1118_s_fu_1749_p3 = {{data_10_V_read}, {10'd0}};

assign shl_ln_fu_469_p3 = {{data_0_V_read}, {10'd0}};

assign tanh_table1_address0 = zext_ln477_fu_3029_p1;

assign tanh_table1_address1 = zext_ln477_1_fu_3033_p1;

assign tanh_table1_address10 = zext_ln477_10_fu_3069_p1;

assign tanh_table1_address11 = zext_ln477_11_fu_3073_p1;

assign tanh_table1_address12 = zext_ln477_12_fu_3077_p1;

assign tanh_table1_address13 = zext_ln477_13_fu_3081_p1;

assign tanh_table1_address14 = zext_ln477_14_fu_3085_p1;

assign tanh_table1_address15 = zext_ln477_15_fu_3089_p1;

assign tanh_table1_address16 = zext_ln477_16_fu_3093_p1;

assign tanh_table1_address17 = zext_ln477_17_fu_3097_p1;

assign tanh_table1_address18 = zext_ln477_18_fu_3101_p1;

assign tanh_table1_address19 = zext_ln477_19_fu_3105_p1;

assign tanh_table1_address2 = zext_ln477_2_fu_3037_p1;

assign tanh_table1_address3 = zext_ln477_3_fu_3041_p1;

assign tanh_table1_address4 = zext_ln477_4_fu_3045_p1;

assign tanh_table1_address5 = zext_ln477_5_fu_3049_p1;

assign tanh_table1_address6 = zext_ln477_6_fu_3053_p1;

assign tanh_table1_address7 = zext_ln477_7_fu_3057_p1;

assign tanh_table1_address8 = zext_ln477_8_fu_3061_p1;

assign tanh_table1_address9 = zext_ln477_9_fu_3065_p1;

assign tmp_10_fu_1117_p4 = {{data_5_V_read[23:9]}};

assign tmp_11_fu_3121_p3 = {{tanh_table1_q1}, {6'd0}};

assign tmp_12_fu_1245_p4 = {{data_6_V_read[23:9]}};

assign tmp_13_fu_809_p3 = add_ln473_2_fu_797_p2[32'd15];

assign tmp_14_fu_1373_p4 = {{data_7_V_read[23:9]}};

assign tmp_15_fu_829_p4 = {{select_ln475_2_fu_817_p3[14:10]}};

assign tmp_16_fu_1501_p4 = {{data_8_V_read[23:9]}};

assign tmp_17_fu_3133_p3 = {{tanh_table1_q2}, {6'd0}};

assign tmp_18_fu_1629_p4 = {{data_9_V_read[23:9]}};

assign tmp_19_fu_937_p3 = add_ln473_3_fu_925_p2[32'd15];

assign tmp_1_fu_477_p4 = {{data_0_V_read[23:9]}};

assign tmp_20_fu_1757_p4 = {{data_10_V_read[23:9]}};

assign tmp_21_fu_957_p4 = {{select_ln475_3_fu_945_p3[14:10]}};

assign tmp_22_fu_1885_p4 = {{data_11_V_read[23:9]}};

assign tmp_23_fu_3145_p3 = {{tanh_table1_q3}, {6'd0}};

assign tmp_24_fu_2013_p4 = {{data_12_V_read[23:9]}};

assign tmp_25_fu_1065_p3 = add_ln473_4_fu_1053_p2[32'd15];

assign tmp_26_fu_2141_p4 = {{data_13_V_read[23:9]}};

assign tmp_27_fu_1085_p4 = {{select_ln475_4_fu_1073_p3[14:10]}};

assign tmp_28_fu_2269_p4 = {{data_14_V_read[23:9]}};

assign tmp_29_fu_3157_p3 = {{tanh_table1_q4}, {6'd0}};

assign tmp_2_fu_553_p3 = add_ln473_fu_541_p2[32'd15];

assign tmp_30_fu_2397_p4 = {{data_15_V_read[23:9]}};

assign tmp_31_fu_1193_p3 = add_ln473_5_fu_1181_p2[32'd15];

assign tmp_32_fu_2525_p4 = {{data_16_V_read[23:9]}};

assign tmp_33_fu_1213_p4 = {{select_ln475_5_fu_1201_p3[14:10]}};

assign tmp_34_fu_2653_p4 = {{data_17_V_read[23:9]}};

assign tmp_35_fu_3169_p3 = {{tanh_table1_q5}, {6'd0}};

assign tmp_36_fu_2781_p4 = {{data_18_V_read[23:9]}};

assign tmp_37_fu_1321_p3 = add_ln473_6_fu_1309_p2[32'd15];

assign tmp_38_fu_2909_p4 = {{data_19_V_read[23:9]}};

assign tmp_39_fu_1341_p4 = {{select_ln475_6_fu_1329_p3[14:10]}};

assign tmp_3_fu_605_p4 = {{data_1_V_read[23:9]}};

assign tmp_40_fu_3181_p3 = {{tanh_table1_q6}, {6'd0}};

assign tmp_41_fu_1449_p3 = add_ln473_7_fu_1437_p2[32'd15];

assign tmp_42_fu_1469_p4 = {{select_ln475_7_fu_1457_p3[14:10]}};

assign tmp_43_fu_3193_p3 = {{tanh_table1_q7}, {6'd0}};

assign tmp_44_fu_1577_p3 = add_ln473_8_fu_1565_p2[32'd15];

assign tmp_45_fu_1597_p4 = {{select_ln475_8_fu_1585_p3[14:10]}};

assign tmp_46_fu_3205_p3 = {{tanh_table1_q8}, {6'd0}};

assign tmp_47_fu_1705_p3 = add_ln473_9_fu_1693_p2[32'd15];

assign tmp_48_fu_1725_p4 = {{select_ln475_9_fu_1713_p3[14:10]}};

assign tmp_49_fu_3217_p3 = {{tanh_table1_q9}, {6'd0}};

assign tmp_4_fu_573_p4 = {{select_ln475_fu_561_p3[14:10]}};

assign tmp_50_fu_3229_p3 = {{tanh_table1_q10}, {6'd0}};

assign tmp_51_fu_3241_p3 = {{tanh_table1_q11}, {6'd0}};

assign tmp_52_fu_3253_p3 = {{tanh_table1_q12}, {6'd0}};

assign tmp_53_fu_3265_p3 = {{tanh_table1_q13}, {6'd0}};

assign tmp_54_fu_3277_p3 = {{tanh_table1_q14}, {6'd0}};

assign tmp_55_fu_3289_p3 = {{tanh_table1_q15}, {6'd0}};

assign tmp_56_fu_3301_p3 = {{tanh_table1_q16}, {6'd0}};

assign tmp_57_fu_3313_p3 = {{tanh_table1_q17}, {6'd0}};

assign tmp_58_fu_3325_p3 = {{tanh_table1_q18}, {6'd0}};

assign tmp_59_fu_3337_p3 = {{tanh_table1_q19}, {6'd0}};

assign tmp_5_fu_733_p4 = {{data_2_V_read[23:9]}};

assign tmp_60_fu_1833_p3 = add_ln473_10_fu_1821_p2[32'd15];

assign tmp_61_fu_1853_p4 = {{select_ln475_10_fu_1841_p3[14:10]}};

assign tmp_62_fu_1961_p3 = add_ln473_11_fu_1949_p2[32'd15];

assign tmp_63_fu_1981_p4 = {{select_ln475_11_fu_1969_p3[14:10]}};

assign tmp_64_fu_2089_p3 = add_ln473_12_fu_2077_p2[32'd15];

assign tmp_65_fu_2109_p4 = {{select_ln475_12_fu_2097_p3[14:10]}};

assign tmp_66_fu_2217_p3 = add_ln473_13_fu_2205_p2[32'd15];

assign tmp_67_fu_2237_p4 = {{select_ln475_13_fu_2225_p3[14:10]}};

assign tmp_68_fu_2345_p3 = add_ln473_14_fu_2333_p2[32'd15];

assign tmp_69_fu_2365_p4 = {{select_ln475_14_fu_2353_p3[14:10]}};

assign tmp_6_fu_681_p3 = add_ln473_1_fu_669_p2[32'd15];

assign tmp_70_fu_2473_p3 = add_ln473_15_fu_2461_p2[32'd15];

assign tmp_71_fu_2493_p4 = {{select_ln475_15_fu_2481_p3[14:10]}};

assign tmp_72_fu_2601_p3 = add_ln473_16_fu_2589_p2[32'd15];

assign tmp_73_fu_2621_p4 = {{select_ln475_16_fu_2609_p3[14:10]}};

assign tmp_74_fu_2729_p3 = add_ln473_17_fu_2717_p2[32'd15];

assign tmp_75_fu_2749_p4 = {{select_ln475_17_fu_2737_p3[14:10]}};

assign tmp_76_fu_2857_p3 = add_ln473_18_fu_2845_p2[32'd15];

assign tmp_77_fu_2877_p4 = {{select_ln475_18_fu_2865_p3[14:10]}};

assign tmp_78_fu_2985_p3 = add_ln473_19_fu_2973_p2[32'd15];

assign tmp_79_fu_3005_p4 = {{select_ln475_19_fu_2993_p3[14:10]}};

assign tmp_7_fu_861_p4 = {{data_3_V_read[23:9]}};

assign tmp_8_fu_701_p4 = {{select_ln475_1_fu_689_p3[14:10]}};

assign tmp_9_fu_989_p4 = {{data_4_V_read[23:9]}};

assign tmp_s_fu_3109_p3 = {{tanh_table1_q0}, {6'd0}};

assign trunc_ln473_10_fu_1817_p1 = select_ln850_10_fu_1809_p3[14:0];

assign trunc_ln473_11_fu_1945_p1 = select_ln850_11_fu_1937_p3[14:0];

assign trunc_ln473_12_fu_2073_p1 = select_ln850_12_fu_2065_p3[14:0];

assign trunc_ln473_13_fu_2201_p1 = select_ln850_13_fu_2193_p3[14:0];

assign trunc_ln473_14_fu_2329_p1 = select_ln850_14_fu_2321_p3[14:0];

assign trunc_ln473_15_fu_2457_p1 = select_ln850_15_fu_2449_p3[14:0];

assign trunc_ln473_16_fu_2585_p1 = select_ln850_16_fu_2577_p3[14:0];

assign trunc_ln473_17_fu_2713_p1 = select_ln850_17_fu_2705_p3[14:0];

assign trunc_ln473_18_fu_2841_p1 = select_ln850_18_fu_2833_p3[14:0];

assign trunc_ln473_19_fu_2969_p1 = select_ln850_19_fu_2961_p3[14:0];

assign trunc_ln473_1_fu_665_p1 = select_ln850_1_fu_657_p3[14:0];

assign trunc_ln473_2_fu_793_p1 = select_ln850_2_fu_785_p3[14:0];

assign trunc_ln473_3_fu_921_p1 = select_ln850_3_fu_913_p3[14:0];

assign trunc_ln473_4_fu_1049_p1 = select_ln850_4_fu_1041_p3[14:0];

assign trunc_ln473_5_fu_1177_p1 = select_ln850_5_fu_1169_p3[14:0];

assign trunc_ln473_6_fu_1305_p1 = select_ln850_6_fu_1297_p3[14:0];

assign trunc_ln473_7_fu_1433_p1 = select_ln850_7_fu_1425_p3[14:0];

assign trunc_ln473_8_fu_1561_p1 = select_ln850_8_fu_1553_p3[14:0];

assign trunc_ln473_9_fu_1689_p1 = select_ln850_9_fu_1681_p3[14:0];

assign trunc_ln473_fu_537_p1 = select_ln850_fu_529_p3[14:0];

assign trunc_ln475_10_fu_1849_p1 = select_ln475_10_fu_1841_p3[9:0];

assign trunc_ln475_11_fu_1977_p1 = select_ln475_11_fu_1969_p3[9:0];

assign trunc_ln475_12_fu_2105_p1 = select_ln475_12_fu_2097_p3[9:0];

assign trunc_ln475_13_fu_2233_p1 = select_ln475_13_fu_2225_p3[9:0];

assign trunc_ln475_14_fu_2361_p1 = select_ln475_14_fu_2353_p3[9:0];

assign trunc_ln475_15_fu_2489_p1 = select_ln475_15_fu_2481_p3[9:0];

assign trunc_ln475_16_fu_2617_p1 = select_ln475_16_fu_2609_p3[9:0];

assign trunc_ln475_17_fu_2745_p1 = select_ln475_17_fu_2737_p3[9:0];

assign trunc_ln475_18_fu_2873_p1 = select_ln475_18_fu_2865_p3[9:0];

assign trunc_ln475_19_fu_3001_p1 = select_ln475_19_fu_2993_p3[9:0];

assign trunc_ln475_1_fu_697_p1 = select_ln475_1_fu_689_p3[9:0];

assign trunc_ln475_2_fu_825_p1 = select_ln475_2_fu_817_p3[9:0];

assign trunc_ln475_3_fu_953_p1 = select_ln475_3_fu_945_p3[9:0];

assign trunc_ln475_4_fu_1081_p1 = select_ln475_4_fu_1073_p3[9:0];

assign trunc_ln475_5_fu_1209_p1 = select_ln475_5_fu_1201_p3[9:0];

assign trunc_ln475_6_fu_1337_p1 = select_ln475_6_fu_1329_p3[9:0];

assign trunc_ln475_7_fu_1465_p1 = select_ln475_7_fu_1457_p3[9:0];

assign trunc_ln475_8_fu_1593_p1 = select_ln475_8_fu_1585_p3[9:0];

assign trunc_ln475_9_fu_1721_p1 = select_ln475_9_fu_1713_p3[9:0];

assign trunc_ln475_fu_569_p1 = select_ln475_fu_561_p3[9:0];

assign trunc_ln851_10_fu_1777_p1 = data_10_V_read[8:0];

assign trunc_ln851_11_fu_1905_p1 = data_11_V_read[8:0];

assign trunc_ln851_12_fu_2033_p1 = data_12_V_read[8:0];

assign trunc_ln851_13_fu_2161_p1 = data_13_V_read[8:0];

assign trunc_ln851_14_fu_2289_p1 = data_14_V_read[8:0];

assign trunc_ln851_15_fu_2417_p1 = data_15_V_read[8:0];

assign trunc_ln851_16_fu_2545_p1 = data_16_V_read[8:0];

assign trunc_ln851_17_fu_2673_p1 = data_17_V_read[8:0];

assign trunc_ln851_18_fu_2801_p1 = data_18_V_read[8:0];

assign trunc_ln851_19_fu_2929_p1 = data_19_V_read[8:0];

assign trunc_ln851_1_fu_625_p1 = data_1_V_read[8:0];

assign trunc_ln851_2_fu_753_p1 = data_2_V_read[8:0];

assign trunc_ln851_3_fu_881_p1 = data_3_V_read[8:0];

assign trunc_ln851_4_fu_1009_p1 = data_4_V_read[8:0];

assign trunc_ln851_5_fu_1137_p1 = data_5_V_read[8:0];

assign trunc_ln851_6_fu_1265_p1 = data_6_V_read[8:0];

assign trunc_ln851_7_fu_1393_p1 = data_7_V_read[8:0];

assign trunc_ln851_8_fu_1521_p1 = data_8_V_read[8:0];

assign trunc_ln851_9_fu_1649_p1 = data_9_V_read[8:0];

assign trunc_ln851_fu_497_p1 = data_0_V_read[8:0];

assign zext_ln477_10_fu_3069_p1 = select_ln476_10_reg_3519;

assign zext_ln477_11_fu_3073_p1 = select_ln476_11_reg_3524;

assign zext_ln477_12_fu_3077_p1 = select_ln476_12_reg_3529;

assign zext_ln477_13_fu_3081_p1 = select_ln476_13_reg_3534;

assign zext_ln477_14_fu_3085_p1 = select_ln476_14_reg_3539;

assign zext_ln477_15_fu_3089_p1 = select_ln476_15_reg_3544;

assign zext_ln477_16_fu_3093_p1 = select_ln476_16_reg_3549;

assign zext_ln477_17_fu_3097_p1 = select_ln476_17_reg_3554;

assign zext_ln477_18_fu_3101_p1 = select_ln476_18_reg_3559;

assign zext_ln477_19_fu_3105_p1 = select_ln476_19_reg_3564;

assign zext_ln477_1_fu_3033_p1 = select_ln476_1_reg_3474;

assign zext_ln477_2_fu_3037_p1 = select_ln476_2_reg_3479;

assign zext_ln477_3_fu_3041_p1 = select_ln476_3_reg_3484;

assign zext_ln477_4_fu_3045_p1 = select_ln476_4_reg_3489;

assign zext_ln477_5_fu_3049_p1 = select_ln476_5_reg_3494;

assign zext_ln477_6_fu_3053_p1 = select_ln476_6_reg_3499;

assign zext_ln477_7_fu_3057_p1 = select_ln476_7_reg_3504;

assign zext_ln477_8_fu_3061_p1 = select_ln476_8_reg_3509;

assign zext_ln477_9_fu_3065_p1 = select_ln476_9_reg_3514;

assign zext_ln477_fu_3029_p1 = select_ln476_reg_3469;

endmodule //tanh_ap_fixed_ap_fixed_24_8_5_3_0_tanh_config6_s
