#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("input1_0_V", 13, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("input1_1_V", 13, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("input1_2_V", 13, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("input1_3_V", 13, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("input1_4_V", 13, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("input1_5_V", 13, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("input1_6_V", 13, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("input1_7_V", 13, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("input1_8_V", 13, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("input1_9_V", 13, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("input1_10_V", 13, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("input1_11_V", 13, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("input1_12_V", 13, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("input1_13_V", 13, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("input1_14_V", 13, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("input1_15_V", 13, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("input1_16_V", 13, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("input1_17_V", 13, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("input1_18_V", 13, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("input1_19_V", 13, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("input1_20_V", 13, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("input1_21_V", 13, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("input1_22_V", 13, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("input1_23_V", 13, hls_in, 23, "ap_none", "in_data", 1),
	Port_Property("input1_24_V", 13, hls_in, 24, "ap_none", "in_data", 1),
	Port_Property("input1_25_V", 13, hls_in, 25, "ap_none", "in_data", 1),
	Port_Property("input1_26_V", 13, hls_in, 26, "ap_none", "in_data", 1),
	Port_Property("input1_27_V", 13, hls_in, 27, "ap_none", "in_data", 1),
	Port_Property("input1_28_V", 13, hls_in, 28, "ap_none", "in_data", 1),
	Port_Property("layer12_out_0_V", 8, hls_out, 29, "ap_vld", "out_data", 1),
	Port_Property("layer12_out_0_V_ap_vld", 1, hls_out, 29, "ap_vld", "out_vld", 1),
	Port_Property("layer12_out_1_V", 8, hls_out, 30, "ap_vld", "out_data", 1),
	Port_Property("layer12_out_1_V_ap_vld", 1, hls_out, 30, "ap_vld", "out_vld", 1),
	Port_Property("const_size_in_1", 16, hls_out, 31, "ap_vld", "out_data", 1),
	Port_Property("const_size_in_1_ap_vld", 1, hls_out, 31, "ap_vld", "out_vld", 1),
	Port_Property("const_size_out_1", 16, hls_out, 32, "ap_vld", "out_data", 1),
	Port_Property("const_size_out_1_ap_vld", 1, hls_out, 32, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "emtfptnn";
